### ISSUE TITLE
Option to send unparsed lines to a log file

### ISSUE THREAD

**Issue by Mikeput** [kauffman12/EQLogParser#10]
Could we have an option or a default option for its to send unrecognized lines to a file for example, raid event messages, to a separate file.   Would probably help to work out event bugs easier e.g. the recent T2 ones for Grolik

**Comment by kauffman12** [comment]
This could cause performance problems so I added it as a debugging option. I don't recommend using it all the time or for most people to do it. Here's the steps to enable it:

Close the Parser
Open C:\Users\yourname\AppData\Roaming\EQLogParser\config\settings.txt
Added the line to the bottom: Debug=True
Open the Parser
Load a log file and look at C:\Users\yourname\AppData\Roaming\EQLogParser\logs\UnprocessedLines.log
