### ISSUE TITLE
Request: Ability to add more Patterns

### ISSUE THREAD

**Issue by Echuir** [kauffman12/EQLogParser#100]
Need the ability to add more than 2 patterns to **Timer End Early Settings**.

**Comment by kauffman12** [comment]
How many do you need? I was trying to keep things simple. You also can have a regex that contains an or.
Example: search string one|search string two

**Comment by esr-sudo** [comment]
`full syntax would be (string one|string two)`  be sure to check the use regex button.

**Comment by kauffman12** [comment]
Closing this for now as the example above should work. Unless there's some example where more are really needed. Maybe another solution to the problem could be implemented.
