### ISSUE TITLE
Looted Items issues

### ISSUE THREAD

**Issue by Kashmirre** [kauffman12/EQLogParser#101]
I could have sworn there used to be a filter for NPC on the looted items. If there wasn't can one be added? 

Also, looted currency is not being displayed.  I'm also on the most current version .23

**Comment by kauffman12** [comment]
Do you have a log line that isn't being parsed as an example? I'm seeing currency when I loot and when others loot a raid chest.

![image](https://github.com/kauffman12/EQLogParser/assets/771335/e3fe6936-8a75-4b6f-bb49-cb637591094c)

**Comment by Kashmirre** [comment]
![image](https://github.com/kauffman12/EQLogParser/assets/88602424/1f133107-266c-41e1-a79b-37fdf36928e5)

![image](https://github.com/kauffman12/EQLogParser/assets/88602424/4aef1cd3-f242-4eb5-b5be-f2bc31fdcc53)

**Comment by kauffman12** [comment]
I see. It's only working for splits. I can update that and filtering on NPC should be easy enough.

**Comment by Kashmirre** [comment]
Awesome Thanks!

**Comment by kauffman12** [comment]
Checkout 2.1.24 for this fix.
