### ISSUE TITLE
Feature Request - Dropdown/Selector for fast swapping between characters

### ISSUE THREAD

**Issue by KestrelKitezh** [kauffman12/EQLogParser#103]
A  fast way to swap between logfiles would have been really awesome. Right now it feels a bit awkward.

**Comment by KestrelKitezh** [comment]
like the 5 most played characters f.ex

**Comment by kauffman12** [comment]
Try 2.1.25.

https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-2.1.25.msi
