### ISSUE TITLE
Run Eqlogparser and no screen windows 11

### ISSUE THREAD

**Issue by grayfox230** [kauffman12/EQLogParser#104]
With Windows 11, I install the program with the net and trusted certificate. However, when I click on the icon on the taskbar, the parser icon comes up, but the program does not appear on any of my monitors. The program used to work flawlessly. I have tried to repair the program, and I have cut off all AV. Still, nothing. I am at wits end with this program. I have tried running the compatibility troubleshooter as well. Running the program as admin. I have the new version of the program as well. I even used Revo to pull everything off with a fresh install. Please help thank you!
![Screenshot 2023-08-10 191731](https://github.com/kauffman12/EQLogParser/assets/141970942/10af4b96-2f9f-43b8-bf03-a2c8b2c9b278)

Adam

**Comment by kauffman12** [comment]
If you think it's off-screen somewhere you can try closing it and editing your user's AppData\Roaming\EQLogParser\config\settings.txt file. Remove the WindowLeft, WindowsTop, WindowHeight, and WindowWidth lines and save/restart. It should go back to the default position and size.

**Comment by grayfox230** [comment]
You are amazing! Thank you! It worked!

**Comment by kauffman12** [comment]
Great!
