### ISSUE TITLE
GINA tags

### ISSUE THREAD

**Issue by Echuir** [kauffman12/EQLogParser#106]
Is there a way to get a list like this for Log Parser. I know one of the functions {L} doesn't convert over 1:1 and need to know what I should use instead? Or just include all of these tokens in Log Parser.

GINA supports the following tags in triggers:

{C} - This is replaced with the character's name, and can be used in Search Text, Display Text, Text to Say, and Timer Name fields.

{S} - This is a wildcard that can match any string. This can be used in Search Text, Display Text, Text to Say, and Timer Name fields.

{S1}, {S2}, etc -- Work the same as {S}, just gives you more wildcards.

{N} - This is a wildcard that matches a number. If you only want the trigger to match if the number meets a certain critera, you can use syntax such as {N>=50000} and the tag will only match if the number is greater than 50k. This can be used in Search Text, Display Text, Text to Say, and Timer Name fields. (The >=50000 portion should only be used in the Search Text field. Just use {N} in the rest of the fields.)

{N1}, {N2}, etc. -- Work the same as {N}, just gives you more wildcards.

{L} -- This is replaced with the whole line of text when a trigger is matched. This can be used in Display Text, Text to Say, and Timer Name fields, but not in the Search Text field.

{COUNTER} - Resolves to the number of times a trigger has been matched (tracked per character). This can be used in Display Text, Text to Say, and Timer Name fields.

{TS} - This matches a time span and is used to set a timer duration dynamically. This tag can only be used in the Search Text field. If this tag is present in the Search Text field and the trigger's Timer Type is set to Timer or Repeating Timer, this result of this match will be used as the Timer Duration when the trigger is matched. The tag will match the format D:H:M:S.L where D = days, H = hours, M = minutes, S = seconds, and L = fraction of second, and only the S (seconds) value is required. Examples of supported matches are:
90 (start 90 second timer)
20.5 (start 20 second 500 millisecond timer)
5:30 (start timer 5 minute 30 second timer)
1:00:00 (start 1 hour timer)
2:12:15:20 (start 2 day 12 hour 15 minute 20 second timer -- note: log off, take a break from the game!)

**Comment by kauffman12** [comment]
What are you trying to accomplish with L exactly? Do you have an example?

The help right now is in the description at the bottom when you select a field. See what it says for Pattern in the screenshot? I could add more details to each field to make it clearer but I'd rather keep this info in the parser itself than on a website.

![image](https://github.com/kauffman12/EQLogParser/assets/771335/ac926ec1-1112-4413-988c-8b916d0f340d)

**Comment by kauffman12** [comment]
I added a document you can read under Help -> Using Trigger Variables to make this easier.
