### ISSUE TITLE
 Timer duration greater than 59:59?

### ISSUE THREAD

**Issue by esr-sudo** [kauffman12/EQLogParser#109]
I'm just getting around to importing triggers into EQLP.  It looks like the maximum timer duration is 59:59.  Could this be extended?  It might sound weird, but since the everquest UI is so small (and there are so many buffs) for certain buffs I have always used a timer bar as a quick way of telling if the buff was still on or not.

Thanks!

**Comment by kauffman12** [comment]
This should also be in 2.1.35.
