### ISSUE TITLE
Shadowknight Bloodletting Coalition

### ISSUE THREAD

**Issue by Treesmasha** [kauffman12/EQLogParser#11]
It appears the parser does not pick up the latest version of the shadowknight covenant line of spells, Bloodletting Coalition. This was true in both versions 1.7.17 and 1.7.20.

Keep up the good work.

**Comment by kauffman12** [comment]
There may be a bug with the spell itself. I'm looking at my log files and it appears like our SKs are casting Coalition.
[Sun Feb 21 19:39:32 2021] Ketruh begins casting Bloodletting Coalition Rk. III.

But then the resolution part of the spell is the latest from Covenant.
Ketruh hit a primal guardian for 3047350 points of magic damage by Bloodletting Resolution III Caza.

I'm seeing spell counts show up OK for Coalition so I'm thinking it's working as best as it can.
