### ISSUE TITLE
a few feature requests such as a count-up timer selection

### ISSUE THREAD

**Issue by esr-sudo** [kauffman12/EQLogParser#110]
#1 In triggers, can a countup timer be added as an option?  (hopefully with the same timer end early settings field, and if possible, a maximum duration setting would also be great!)

#2 In overlays, can clear be added as a selection for the background color?

#3 In triggers, I'm unable to get the use custom color to work.  If a trigger is added to an overlay, it seems to always use the overlay setting for the text color.  Am I doing something wrong?

#4 Would it be possible to add a custom active color to a trigger?  (ie: that would be used in the overlay.)  Where I'm going with this are ultimately things that GINA handled with categories.  I'm aware you're trying to keep things simple, these requests might be out of scope.  If so I totally understand.  :) 

PS: I can't help but feel like the guy in Fight Club asking if the icon could be made in cornflower blue.

**Comment by kauffman12** [comment]
#2 You can select Transparent as the color by using the slider on the right. All the way at the bottom is 100% transparent. In the middle is 50% transparent, etc.

![image](https://github.com/kauffman12/EQLogParser/assets/771335/9a15f6b4-b0a9-49c2-a7da-75d18fb0ce7b)


#3 The custom color is only for text overlays. I could make it work for timer text i guess but not sure some people want it to change both. As far as adding more custom colors. At what point could you just make a 2nd overlay? Or are you really making like 5 timer bars all with different colors?

**Comment by esr-sudo** [comment]
Ooops!  I didn't notice the slider at all!  A second overlay could work, but having an option to have two triggers of related but distinct purposes would be useful.  For example some people who play buffing classes track short duration buffs that they cast on other players with an overlay.  Buff1 could be color-a, and buff2 could be color-b.  Ultimately using one overlay that has more visually distinct display could be preferable than having multiple overlays, especially if their preference is to have fewer overlays.

**Comment by kauffman12** [comment]
Well if the only two changes are making the custom font color work for timer overlays and adding a custom active color that should be fine.

**Comment by kauffman12** [comment]
I'd also consider some other options. Would you prefer if colors changed as duration is running out or something? Like instead of the cooldown timer options there could be a warning timer. Maybe you say at 2 minutes the timer color starts transitioning to another color. Or something like that.

**Comment by esr-sudo** [comment]
Hmm, if it's a matter of preference between the two, I think I would lean towards a custom color in the overlay for a specific trigger.  I don't think I would personally use the color changing as the time runs out, but, I think others might like your suggestion as well.  Both sounds great!

**Comment by kauffman12** [comment]
The two custom color changes are dont but they're part of a larger rework I'm doing so not sure when I'll have a new version. Maybe this weekend if everything happens to work As far as a countup timer that's something for a bit later.

**Comment by kauffman12** [comment]
I don't have anything for count up yet and I do have other things to work on so note sure when I'll get to it. But try 2.1.40. It has a lot of changes and they do include the custom color for the active timer.

**Comment by kauffman12** [comment]
How does a count up timer work exactly? 

1. Does it end when a maximum count has been reached?
2. If the count you specify is say 10 should each time the pattern is seen increase the size of the timer bar by 10%?
3. When it gets to 10 I assume it would use the End Text/Display options to do something and then start counting again from 0? So it would go away at that point until the pattern is seen again.
4. I imagine you'd want to see the current count in the timer bar as well. Like maybe a  {timerStatus} field you could put in the timer name that prints something like  4/10 if it's counted 4 times so far.
5. And if it had a max duration where it goes away and starts over. Is it enough to have it do the End Early text/sound or would it need a Trigger Timed Out Text to Display or something?

**Comment by esr-sudo** [comment]
My personal use case (and a couple guildmates who use some variant of the same timer set for dots) is that the count-up timer starts when a dot spell has worn off a target.  We set end early text to auto-clear it, such as from the same target taking damage from that same dot, or what I personally like to use, by casting that same dot.   It's basically a separate timer to remind us that a given dot (or debuff effect such as tash or slow) has worn off a target, and the goal is to get it re-applied asap, and we set end early text for the mob dying or the debuff being reapplied by the caster.

Currently, as far as I am aware Gina does not support a maximum duration on the count-up timers, which could be helpful if that maximum duration was something we could configure.

Put simply, it's the opposite of a countdown timer.  A raid timer for example, starts when the emote text for the event starting is seen, and is set in the trigger for whatever length the maximum raid completion time is.   Your recent addition of allowing custom timer bars to be configured in the trigger text does allow us to make a count-down timer that is visually distinct from the others, so we could use that in the same overlay for tracking our dots/debuffs provided we set a maximum duration on that timer.  So that does function as a work-around to not having a count-up timer, albeit the ultimate goal with the countdown timer for dots/debuffs would of course to have all of them at the maximum duration (thus the timer bar would be full) whereas the ultimate goal for the countdup timer in my proposed use case would be for the timer bar to be as small as possible, or not exist.  

I don't know what you mean by the count getting to 10, I think perhaps I could have explained the request more clearly.  I think you're talking about a timer bar that keeps track of how many times a certain string has been seen in the log. 

I'm sure you're familiar with the timer (countdown) setting in GINA, which EQLP already supports that function.   I'm talking about the Stopwatch (Count Up) located in the same section of GINA.

**Comment by kauffman12** [comment]
I'm not too familiar with all the GINA features. I've used a few simple timers and audio triggers myself. And I've been relying on people to explain exactly what they want in case there's a better way to do things. I did think you meant counting of some kind based on some pattern. This sounds just like another request I had the other day.

It also sounds vaguely similar to how the current Cooldown timer/overlay combo works. Maybe it just needs some tweaks. Right now, it allows you to start a timer like normal. Say from seeing a DoT landing although the main use case is for managing buffs. Then when the timer finishes it starts counting back up based on a value you enter. For a buff it's the recast time of the spell but in this case it could be used as your max duration value. When that duration is reached the timer bar displays as full and just sits there on your screen until it sees the buff/adps again. Although, I did add a max time for it to sit in the ready state before going away entirely and It also allows 3 different colors for the various states. And additionally if it sees the original pattern again it starts over like normal.

So, I think all the Cooldown timer is lacking is a 'enter reset state early based on pattern' sort of option to handle your mob dying or dot wearing off. I'll do some testing and see if I can figure something simple out now that I know what you're trying to do.

**Comment by esr-sudo** [comment]
Couple points if I can add them.   I'm activating the countdown timer for dots or debuffs by a hotkey for /inspect mine.   The game outputs a standard output for what effects you have on the mob, and it also provides a duration of how much time is left on it.  So  if the user excludes for effects they do not want to have tracked in the countdown timer, they would have the duration of the timer as well as easy options for end early text to include the mob dying or the effect wearing off or getting ovewrwritten so the existing options already handle that.

If I understand you correctly about the timer function being able to start counting up after it has already worn off, that would not necessarily be ideal behavior.  It sounds great in theory, but there are a lot of encounters where a mob will despawn or clear all detrimental effects as a part of the mechanic of the raid.  If the countdown timer would automatically flip to a countup timer, it would be incorrect for these events.

**Comment by kauffman12** [comment]
It still sounds to me like you're describing a normal timer. Is the only difference really whether the timer bars start big and go down or start small and go up? I mean I could add a checkbox to the Timer overlay settings to either visualize the timer bars going up or down. Then the trigger options don't have to get more complicated. Do you normally group your counter up timers together so them all being in the same overlay would make sense?

**Comment by esr-sudo** [comment]
Yeah, it's because it would allow them to be sorted with the shortest duration being at the top, as those would receive the most immediate response.  The `{TS}` variant assigns the duration of how long the debuff has remaining on it from the /inspectbuffs mine hotkey.   Debuffs wearing off as a count-up timer would start with 0 duration so they would be at the top.

**Comment by kauffman12** [comment]
So let's say the dropdown in the Trigger has the count up option. The duration would still be useful so you have a way to scale how big the timer bar gets. So duration is your max duration. But what do you want to happen when it reaches the max? It just goes away at that point?

**Comment by esr-sudo** [comment]
In my use case...yeah, the count up timer would just stop.   That would account for scenarios where a person went afk or the event ended and they were celebrating the victory and taking screenshots, salivating over loot, etc...it would end on it's own eventually for scenarios where there is no applicable end early text.

**Comment by kauffman12** [comment]
Alright give this a try in 2.1.41. I googled some naming options and went with Progress as the timer type. It's exactly the same as a regular countdown timer except it visually starts small and gets bigger and the time it displays counts up. I didn't change anything else. Just don't use them with Standardize Time enables on an overlay. I didn't put in any special exception for that to be ignored. Do you even use that on these sorts of timers?

**Comment by esr-sudo** [comment]
I'm not familiar with the use standardized time setting of your timers...but I just tried out the 2.1.41 update, and well...my initial thoughts are that it is

AMAZING

**Comment by kauffman12** [comment]
Hmm yeah the {C} is a little broken if you're setting up multiple log files. Forgot to get back to fixing that. Right now, it's using the character name you type in when adding a log instead of trying to parse the name from the log file you selected. I'll fix that for the next version. I'll probably have something later this week.

Just FYI. The standardize time setting is kinda useful sometimes. What it does is make the bars relative to the longest time. The simplest way to put it is if one timer pops up with 1 minute duration it'll use the full length of the overlay. Then if a 2nd bar pops up with 2 min duration the first bar automatically shrinks to 50% since 1 min is half of 2 mins. Then the length of the bars themselves represent the same length of time. When I tested that with a count up timer it went from zero to 50% which didn't make any sense. I'll have to think more about how that should actually work. I'm sure it's pretty simple but I'm working on too many other things lol.

**Comment by esr-sudo** [comment]
Ah, that would explain why I am unfamiliar with that setting.  For the use case I am mostly interested in here (for managing dots)  The relative length of the bars has not mattered so much as most of them have a relatively comparable duration of time and it's mostly about just being easy to identify which dots to refresh first...and they auto-sort so it's all good.

I would imagine people using "countdown" and "progress" timers for managing buffs or raid events would be more familiar with that setting.   At any rate, I love the update.  Thank you!

**Comment by kauffman12** [comment]
Thanks. No prob!
