### ISSUE TITLE
[Enhancement] - Only Give End Phrase Text-To-Speech On Early End

### ISSUE THREAD

**Issue by Ewiclip** [kauffman12/EQLogParser#113]
Hey! I'm happy to help with coding this but I wanted to reach out before I just start trying to make changes on my own in case you already had plans or in case you liked this idea and could knock it out quicker than I could. 

I'd like to make countdown timers we don't see (specifically so I can wait for an end-early phrase for Nth amount of time without cluttering the UI)

In addition to that I'd like to make End-Early phrases that only go off when it ends early. If the timer makes it to zero we'd hear nothing. 

This is to accomodate for events where you only need to run if you have a certain debuff on yourself.  (Think Thinning Skin in Spirit Fades Raid)

**Comment by kauffman12** [comment]
I did test the end early suggestion and it is working in the current version. As far as time based counters, etc it is something you could add if you want. Otherwise it does sound useful so I'll add it to the list of things to do. I'd get to it eventually.
