### ISSUE TITLE
Logic is inverted on "Self only" check box - Shows self when unchecked

### ISSUE THREAD

**Issue by Ahamay** [kauffman12/EQLogParser#114]
Logic is inverted on "Self only" check box - Shows self when unchecked
To reproduce, gather data and log parse to show ADPS timeline. 
Check the Self Only box
Result: Others ADPS is displayed
Expected Result: Only ADPS that applies to player is displayed
![image](https://github.com/kauffman12/EQLogParser/assets/147348823/1b25dbbd-33ca-4b6b-b922-e8435da58c8b)

**Comment by kauffman12** [comment]
It's worded poorly. Some ADPS shows in the log file for everyone to see. That's the stuff that is shown by default so you cam compare players and people to yourself. That checkbox is supposed to turn on stuff that nobody sees but you.

**Comment by kauffman12** [comment]
I updated the wording in 2.1.40 so hopefully it's clear.
