### ISSUE TITLE
Potential Heals Per Second

### ISSUE THREAD

**Issue by ZipeXoop** [kauffman12/EQLogParser#115]
Hello,

Damn, the other day I was kinda bind and I posted this enhancement request on the EQspellparser project. But just saw you added it on last update... so thanks!

Max potential heals will help us to parse actual spell power of some spells.

Potential heals per second would be good too. It would be cool to check it for comparing single target healing power. Would it be possible?

Thanks

**Comment by kauffman12** [comment]
Yeah I saw the email. I'll look at adding more.

**Comment by kauffman12** [comment]
Try 2.1.42
