### ISSUE TITLE
Request: Middle click to close tab

### ISSUE THREAD

**Issue by Rhiven** [kauffman12/EQLogParser#117]
This isn't a high priority item by any means since it is easy enough to click the X, but if it would be easy to implement then it would be nice to be able to click with the middle mouse button to be able to close a tab just like you can do in a browser. This is something that has become muscle memory for me and almost every time I go to close a tab I first try middle clicking it to close before then having to click the X on the tab.

**Comment by kauffman12** [comment]
This is in 2.1.46.
