### ISSUE TITLE
Highlight multiple characters

### ISSUE THREAD

**Issue by BalforH** [kauffman12/EQLogParser#119]
Many triggers are used by all of most characters. would be nice to highlight multiple characters and active/deactivate triggers vs going the the list multiple times,, thanks

**Comment by kauffman12** [comment]
True but you only have to do it once. I think if you could highlight multiple people would accidentally enable things on too many chars.

**Comment by BalforH** [comment]
> True but you only have to do it once. I think if you could highlight multiple people would accidentally enable things on too many chars.

I personally never had that issue..although I understand the concern as Im certain others would..  right now with beta I have 2 sets of chars live vs beta.. would have been nice If I highlighted beta chars and activated just beta triggers ,, for me its kinda mute and I have already individually activated all the common and char specific triggers.. how about a copy so If I have to log my friends ranger in I can just copy my rangers trigger set.. ,, again thanks for all you are doing

**Comment by kauffman12** [comment]
Ok I could add a right-click Copy To menu. That would be hard to mess up. Then you could either copy all your triggers to another character or copy the settings for a single folder (and down).

**Comment by kauffman12** [comment]
2.1.46 has a right-click option for copying settings to another character.

**Comment by BalforH** [comment]
Awesome thanks
