### ISSUE TITLE
Spell counts different

### ISSUE THREAD

**Issue by eqdialup** [kauffman12/EQLogParser#12]
![eqlogparser_example_healing_breakdown](https://user-images.githubusercontent.com/76068973/111833620-6edce200-88c0-11eb-86ee-a34885e66bc7.png)
![eqlogparser_example_spellcount](https://user-images.githubusercontent.com/76068973/111833621-6edce200-88c0-11eb-9344-5ad889401b8c.png)

When posting my screen shots this morning from last night's raid, I noticed my Complete Heal counts looked wrong. I was in a CH chain for a long fight, and it only showed 13. The healing breakdown looks correct, just not the spell counts. I can get you a log or whatever you need for this. Attached are two screen shots that show the difference.

**Comment by eqdialup** [comment]
On another note - full screen now covers the task bar. Not sure if that was intentional or not.

**Comment by kauffman12** [comment]
If you can send a log or at least copy/paste and lines with the words
complete that would help. It should just be looking for normal spell
casting messages.

The taskbar thing is weird. I'll google that one. Not quite sure how that
was even possible hmm.

**Comment by eqdialup** [comment]
[ch.log](https://github.com/kauffman12/EQLogParser/files/6177525/ch.log)

**Comment by kauffman12** [comment]
Could you try opening all three summaries. The damage, tanking, and
healing. Then looking at the right-click spell counts on each one? I wonder
if one of them is showing them all.

The log file looks good but it also all depends on seeing damage to know
what period of time to count. Maybe you were too far away or one of the
other summaries are counting better. Hmm.

**Comment by eqdialup** [comment]
All three are short. If I select just the initial form of the main mob, the counts are correct. Fight shows 1660 seconds. She flips in and out of a Vulnerable state. If I select the initial form and everything till the end, the counts are correct. As soon as I select a fight before the final fight, I starts chopping off the counts and timeline by the difference between the first fight and the end.  Fight before final started 8 minutes before the final fight. I lose 8 minutes off the counts and timeline. I can send you a  complete log of the night, but would rather not attach it. Is there some other way to get it to  you?

**Comment by kauffman12** [comment]
Oh I see. If more than one fight is selected.. It's OK I just made it
happen with one of my logs. Should be able to fix it.

**Comment by kauffman12** [comment]
Try and see what happens with version 1.7.33.

**Comment by eqdialup** [comment]
Just tested with 1.7.36. Looks great, and see the window issue got changed also. Thanks for the great tool.

**Comment by kauffman12** [comment]
No prob!
