### ISSUE TITLE
Suggestion: clipped text

### ISSUE THREAD

**Issue by viruleq** [kauffman12/EQLogParser#120]
Was wondering if it would be possible to add a clipped text option to triggers. For events where you have to do certain /bow commands on or similiar would be usefull if you could just clip the txt and paste into eq when emoted.

**Comment by kauffman12** [comment]
2.1.48 should have that with the Text to Share option.

**Comment by viruleq** [comment]
Gotcha, i hadnt updated past 2.1.47 yet. Appreciate  the response.
