### ISSUE TITLE
Only open the app once now?

### ISSUE THREAD

**Issue by cjgade** [kauffman12/EQLogParser#121]
Hi, 

I am used to opening the app 2 times for 2 different purposes of logging, today after either version .48 or .49 I am only able to open the app once? Or am I doing something wrong? I did not run the program after .48, so not sure if this happened after .48 or .49.

It has been really helpful to be able to run at least to instances of the application, so I would hope we would be able to continue doing that.

Thanks,
cjgade

**Comment by kauffman12** [comment]
Ok try 2.1.50.
