### ISSUE TITLE
Log Rotation

### ISSUE THREAD

**Issue by ehuntercommer** [kauffman12/EQLogParser#122]
I'd suggest adding this to the Triggers section so it can manage all of the logs. Adding a Log file rotation for all of the monitored logs would be a great feature so the logs don't get overly large. (Much like Gina has).

**Comment by kauffman12** [comment]
It's on the list of things to do. Not sure when exactly.

**Comment by kauffman12** [comment]
2.1.65 has a basic version of this. It's under Tools -> Log Management and should be fairly self explanatory but the release notes discusses the details. Hopefully it's enough.
