### ISSUE TITLE
EQ LOG PARSER

### ISSUE THREAD

**Issue by nymetz86** [kauffman12/EQLogParser#123]
was time parse results would show characters name ....not class......cannot denote comparing CERTAIN players if its just listing enchanter mage etc and not the character name....not sure what has changed for me on it.

**Comment by kauffman12** [comment]
Is the Name column turned off or something?

**Comment by nymetz86** [comment]
sometimes a dunce needs a lil push...not sure how that got unchecked from one update to other...wasnt sure honestly where that option was. I thank you for your help

**Comment by kauffman12** [comment]
No prob.
