### ISSUE TITLE
Problem with a changement Name

### ISSUE THREAD

**Issue by Elloriatoanto** [kauffman12/EQLogParser#124]
Hello, 

I changed my name in the game in order to get my old school name back, but since then I have reset the software or re-installed it, nothing changes and I no longer have anything displayed as before? Will there be a manipulation to do or another restoration so that I can have this magnificent software which helps with DPS? Thank you for your response and time reading.

**Comment by Elloriatoanto** [comment]
name txt. 

before easy find now same place but new name = C:/jeux gamer/EQ/Logs/eqlog_NewName_ServerName.txt 

but nothing =(((((( rolf

**Comment by kauffman12** [comment]
Make sure you type /log on in EQ. They might be off by default with new character files.

**Comment by Elloriatoanto** [comment]
it is do ..... /log on and nothing meter ... perhaps something else
________________________________
De : kauffman12 ***@***.***>
Envoyé : mardi 14 novembre 2023 00:43
À : kauffman12/EQLogParser ***@***.***>
Cc : Elloriatoanto ***@***.***>; Author ***@***.***>
Objet : Re: [kauffman12/EQLogParser] Problem with a changement Name (Issue #124)


Make sure you type /log on in EQ. They might be off by default with new character files.

**Comment by kauffman12** [comment]
And you don't have chat filtered? It is odd. The only other thing is maybe look in Program Files\EQLogParser\data\npcs.txt and see if your new name is also an NPC name. Could try removing it from that file if it is. I don't think that should cause a problem anymore but couldn't hurt to test.
