### ISSUE TITLE
Multiple triggers with the same pattern issue

### ISSUE THREAD

**Issue by KentCarmine** [kauffman12/EQLogParser#125]
Thanks for building this wonderful tool!
I think I may have found an issue that causes triggers not to fire if multiple triggers (including timer ending early triggers) share the same pattern to match. My goal was to have 2 triggers. 
Trigger 1 would start a countdown timer bar whenever "/inspectbuffs mine" showed Poison Bolt as being on the target. That part works fine.
Trigger 2 would start a progress timer bar whenever it parsed that my Poison Bolt had worn off a target. This also works fine. However, it is also set  so that while that timer is running, if I "/inspectbuffs mine" again and Poison Bolt has been reapplied to the target, it should clear the timer and play an alert sound. This part does not work.
Screenshots of my timer settings are below:
Trigger 1
![image](https://github.com/kauffman12/EQLogParser/assets/5168853/85111b6b-59b4-42f9-b1e7-cc634670f5e0)

Trigger 2
![image](https://github.com/kauffman12/EQLogParser/assets/5168853/10ee14fb-166f-47a9-b228-3d3e0ec897e3)

**Comment by kauffman12** [comment]
Interesting. I'll give it a try sometime this week to see what the issue is.

**Comment by kauffman12** [comment]
Try 2.1.52. Haven't had a chance to test this exactly but it definitely wouldn't have worked before. Should be good now.

**Comment by KentCarmine** [comment]
I just tested it and it appears to be working perfectly. Thanks so much for the incredibly fast fix!
