### ISSUE TITLE
QoL Feature Suggestion: Adding icons to timers

### ISSUE THREAD

**Issue by KentCarmine** [kauffman12/EQLogParser#127]
One feature that might be useful would be the ability to display a user-selected icon next to (or on, or above, etc) a timer bar (or possibley even a text alert?). This would allow users to, for example, put a spell icon next to a cooldown bar.

**Comment by kauffman12** [comment]
I added a Timer Icon to the Trigger config. It shows it to the left of the timer. It does resize the icon's height to be the same as the timer bar so it's probably good to specify icons that are natively about the right height to avoid quality going down. I'd take a screenshot of your timer bars and measure the sizes in photoshop or something. With the different font styles and sizes there's good value to recommend.
