### ISSUE TITLE
Feature Request: Indefinite display of text triggers

### ISSUE THREAD

**Issue by KentCarmine** [kauffman12/EQLogParser#128]
One feature I thought would be helpful (provided it's feasible) would be a means of making a text alert display indefinitely (until a trigger cleared it), instead of for 20 seconds or less. At present, there's no way to have text permanently display in response to a trigger, then disappear in response to another trigger.
The use case I am thinking about for this is refreshing key buffs and/or debuffs. When a trigger's pattern matches the 'wears off' log line, the trigger could display a message telling you to reapply it. This message would remain visible until another pattern (matching the 'you applied buff X' log line) was matched.

**Comment by esr-sudo** [comment]
The functionality you are looking for already exists.  They are timers.

**Comment by esr-sudo** [comment]
You're aware of timers, that is obvious from another post you have made.  Timers can do exactly what you are asking (and more).  Timers don't have to just be short, they can be for whatever duration you specify them to be.   They can end early when whatever event you define is received, and you can even use the warning function to prompt an additional audio and/or text.

**Comment by kauffman12** [comment]
Yeah I'd try to use timers as they make more sense for this case. Text windows are really for scrolling text.
