### ISSUE TITLE
Bloodfury

### ISSUE THREAD

**Issue by Kashmirre** [kauffman12/EQLogParser#129]
Is there any way to remove the Zerker Bloodfury from the fight list? It's a self-inflicted dmg/ability.

**Comment by kauffman12** [comment]
Can you just uncheck the Tanking checkbox to hide stuff that isn't taking damage?

**Comment by Kashmirre** [comment]
I can do that yeah.

**Comment by kauffman12** [comment]
Well some people like seeing all the effects doing damage to them whether it's a raid aura/AE of some kind of player spells. Especially the ones that do a lot of damage and might results in them dying. But that's also why I added the checkboxes so you can look at those things or not.
