### ISSUE TITLE
Name combined parses.

### ISSUE THREAD

**Issue by eqdialup** [kauffman12/EQLogParser#13]
Very low priority wish list item. When you select multiple fights, have the ability to name the fight. For example Mayong Mistmoore fight in DSK always picks up the name of the first gargoyle you fight. Would be nice to have this show in exports and screen shots as MM instead of R'kazzi

**Comment by kauffman12** [comment]
Is that something you do a lot? Could it be a textbox on the Parse Preview window or is that too annoying to bring up every time?

I'm thinking either something next to the Damage dropdown on that preview window at the bottom. Or I guess it could go above or below the Fight list somewhere.

https://i.imgur.com/m8riwvg.png

**Comment by eqdialup** [comment]
After every raid we always group up everything and post damage and healing parses, so at least 3-5 a week. The preview parse pane would be fine.

**Comment by kauffman12** [comment]
Ok I have this in 1.7.60.

https://i.imgur.com/oFBQWcp.png
