### ISSUE TITLE
When two Characters are enabled, switching between individual triggers prompts save

### ISSUE THREAD

**Issue by Ahamay** [kauffman12/EQLogParser#131]
When I have two characters enabled, I can click on one individual trigger. Selecting another trigger without making any changes will sometimes prompt for a save before moving to the next trigger. I'm not sure what is causing it, there is something in the background that makes the app think the form is dirty. These two triggers pasted will cause the issue
<img width="826" alt="image" src="https://github.com/kauffman12/EQLogParser/assets/147348823/e4afecf1-f5a9-4861-97e7-7124e68fdb12">

<img width="821" alt="image" src="https://github.com/kauffman12/EQLogParser/assets/147348823/adb03e7e-a920-4725-8b3b-17fb78a80506">

**Comment by kauffman12** [comment]
Does deleting and remaking them help?  I'm not able to get this to happen. Were they imported maybe? Wondering if they could have some hidden values that don't show up because of the timer settings.

**Comment by kauffman12** [comment]
If this still happens with.2.1.60 re-open.
