### ISSUE TITLE
Merge All Mobs in Combat for DPS Overlay?

### ISSUE THREAD

**Issue by DoubleStuffin** [kauffman12/EQLogParser#134]
I believe GAMParse did this , but it would be a nice/more accurate reflection of DPS especially for classes that can AOE if the overlay displayed the 'whole' DPS against all mobs currently in combat vs just your specific target at the time. Would make the overlay seem a lot more 'accurate' in AOE scenarios without having to refer to the actual parse program to see exactly what happened damage wise.

**Comment by kauffman12** [comment]
Do you use the Reset on Kill option? The Reset 60s option is what I use on raids.

**Comment by DoubleStuffin** [comment]
I run reset 30s , its not the continuing tally that I mean though, I mean...
Tank pulls 5 mobs -> Group burns -> any given person only sees damage dealt to 1 mob rather than the combined damage dealt to all 5. 
Having the overlay sum the combined fight vs single NPC for all mobs currently taking damage would give a clearer picture of whats going on as a whole, or at least an option to do that.

**Comment by kauffman12** [comment]
If all the mobs have the same name it may look like 1 but it should show the damage done to everything. Not sure why it wouldn't be doing that. Unless some players have filters on in EQ so their log file only shows their own damage.

**Comment by DoubleStuffin** [comment]
I'll double check tonight in missions, but from previous guild groups and stuff it didn't feel like it was merging all. Will close out ticket/provide more details depending what I see

**Comment by DoubleStuffin** [comment]
Nope you were right, its successfully merging - I had a crazy out of date install (auto update got borked at some point I think) got new version seems good.

Any chance of a shorter Reset on out of combat timer? 5, 10s interval? Something more suitable for group content too?

**Comment by kauffman12** [comment]
5 might be a little too short but adding more options is easy enough. at least 10 and 20 maybe.
