### ISSUE TITLE
Feature Request: separate view for tracking random rolls. 

### ISSUE THREAD

**Issue by BronsonMagnan** [kauffman12/EQLogParser#137]
Feature Request: separate view for tracking random rolls. 
Just another view from the logs for tracking random rolls.
Maybe group highlight similar max numbers.
Highlight the highest roll detected so far.
Would make random loot stuff really easy.

**Comment by kauffman12** [comment]
Have you used the one under View -> Events -> Random Rolls? Is this different?

**Comment by BronsonMagnan** [comment]
that is perfect, just didnt know it was there, can close or delete issue.

**Comment by BronsonMagnan** [comment]
duplicate feature

**Comment by kauffman12** [comment]
Ok cool.
