### ISSUE TITLE
Feature request - Highlight player name in View->Events->Random Rolls when it matches the player name of the log file being parsed

### ISSUE THREAD

**Issue by yeroca** [kauffman12/EQLogParser#138]
I would like for the name of the top roller to be in another color, say green, when the player name who won matches the log file being monitored.  That way it's easy to spot when I've won a roll on an item.

An additional feature would be to color friend's names in another color, say yellow, when they are the top roller. This would require adding a friend list feature as well.

**Comment by esr-sudo** [comment]
I like the first suggestion!

**Comment by esr-sudo** [comment]
I really like the first suggestion!

**Comment by yeroca** [comment]
I wrote a little rolls parser in powershell that creates a HTML file as output, and I can attest that the highlighting really helps a lot.  I was thinking of implementing the friends feature, but ran across your implementation in eqlp which is better than my script in several ways.

**Comment by kauffman12** [comment]
Highlighting the winner green shouldn't be too bad. I did want to come back to this UI and make some improvements.

**Comment by yeroca** [comment]
Great! Thank you!
