### ISSUE TITLE
EQ Color changes

### ISSUE THREAD

**Issue by SusanTN** [kauffman12/EQLogParser#14]
This is from MQ2 but may affect your parser too

Credit CWTN & Sic
color 301 is now "Critical" for self
color 302 is not Critical Dots AND Spells for self
-- this requires checking handlenonmelee and handledot
--- this can cause error in debug reporting, but that is expected.
color 305 this is other pet flurry
updated note for 328 for my pet hit
331 is My Pet Flurry
332 is now My Pet Critical
356 is now My Flurry
added "stabs" to OtherHits

**Comment by kauffman12** [comment]
Thanks but the log file doesn't have any of the color info in it so it shouldn't be a problem.
