### ISSUE TITLE
Random Rolls Feature Not Working on Project Quarm

### ISSUE THREAD

**Issue by alphablueofficial** [kauffman12/EQLogParser#140]
It looks like the random rolls feature isn't working on Project Quarm. 

I'm not sure if it's something on my end that isn't allowing EQLP to see the rolls or if it's not able to use the TAKP / Quarm logs. Another program is able to see them, but I'd prefer to use EQLP!

**Comment by kauffman12** [comment]
What do randoms look like on that server? Copy an example into a code block if you can. It may be a lot different or just missing a comma that breaks it.

They look like this on live. 
`[Sun Feb 11 22:14:56 2024] **A Magic Die is rolled by Kizant. It could have been any number from 0 to 100, but this time it turned up a 95.`

**Comment by alphablueofficial** [comment]
Sorry for the delay here! This is what it looks like

``[Thu Feb 15 12:21:58 2024] **A Magic Die is rolled by Kaldayan.``
``[Thu Feb 15 12:21:58 2024] **It could have been any number from 0 to 100, but this time it turned up a 65.``

**Comment by yeroca** [comment]
Yikes, that's split across two lines.  What the heck!?  what if two people roll at the same time? You might get

A magic die has been rolled by Steve.
A magic die has been rolled by Jessica.
It could have been ...
It could have been ...

**Comment by alphablueofficial** [comment]
> Yikes, that's split across two lines. What the heck!? what if two people roll at the same time? You might get
> 
> A magic die is rolled by Steve. A magic die is rolled by Jessica. It could have been ... It could have been ...

It looks like it comes out as one message, even though it's split into two lines. It doesn't look like they get overlapped at all - see below:

``[Thu Feb 15 17:04:23 2024] **A Magic Die is rolled by Therapist.``
``[Thu Feb 15 17:04:23 2024] **It could have been any number from 0 to 6666, but this time it turned up a 4309.``
``[Thu Feb 15 17:04:23 2024] **A Magic Die is rolled by Fizzlefizzle.``
``[Thu Feb 15 17:04:23 2024] **It could have been any number from 0 to 6666, but this time it turned up a 5467.``

**Comment by kauffman12** [comment]
Ok try 2.1.67.
