### ISSUE TITLE
EQLP stops recognizing/reporting triggers ~15 minutes into raid. 

### ISSUE THREAD

**Issue by JustTheFeedbackMaam** [kauffman12/EQLogParser#141]
Title says it all. This started about 2 or 3 weeks ago. Let me know how I can help and provide more information/testing.

**Comment by kauffman12** [comment]
I guess check for errors in the log and make sure you're using 2.1.69. You could also turn off triggers that you don't need. Maybe narrow it down to something that's breaking things.

I just ran an hour long replay of raids and didn't see any issues. I added some extra triggers so I had the last 3 expansions turned on plus all my regular ones. So I tested with a decent amount.

**Comment by kauffman12** [comment]
2.1.70 also has some tweaks that may help so definitely try with the latest.

**Comment by kauffman12** [comment]
Haven't heard back on this and nobody has reported it so closing for now.
