### ISSUE TITLE
Log Management not archiving unless you reload program

### ISSUE THREAD

**Issue by chadw** [kauffman12/EQLogParser#143]
The log management feature only seems to archive properly if you unload and reload the program. Is this intended or is there a work around I am missing?

**Comment by kauffman12** [comment]
Yeah it is pretty simple right now. Any time a file is opened it does a check. So, when you load a parse or turn a characters triggers on or off.  Nobody wants it to do a backup in the middle of something important and I didn't want to make the options really complicated. Eventually I might have it check for backups if basically nothing is happening. I don't know. It's on the list of things to improve.

**Comment by chadw** [comment]
Ok yeah makes sense. I know GINA does it whenever and some might not like it (I didn't care either way), but one thing that your parser does is that it identifies inactivity, so it might be a good time to do it if the log matches the threshold during inactivity. Maybe a simple checkbox to bypass/allow archiving during inactivity period or whenever it reaches the threshold selected (for those of us who don't care).

**Comment by kauffman12** [comment]
I updated log management to also check when you zone. Hopefully that works out ok.
