### ISSUE TITLE
Changing log file path results in program crashing on launch.

### ISSUE THREAD

**Issue by tputs** [kauffman12/EQLogParser#144]
```
Application: EQLogParser.exe
CoreCLR Version: 6.0.1122.52304
.NET Version: 6.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'EQLogParser.MainWindow' that matches the specified binding constraints threw an exception.
 ---> System.ArgumentException: The directory name 'C:\EQ\TAKP PC V2.1c\TAKP PC V2.1' does not exist. (Parameter 'path')
```

Here's a snippet of the Event Viewer error.

I attempted to change the folder names and EQ Log Parser would attempt to load and immediately crash, not allowing me any way to change the log file path in the application.

I had to change the folder names to match their previous in order to get the program to load again.

It would be nice to be able to at least load the program, it tells me it cannot find the path and needs a new path to run.

EQ Log Parser rocks, thank you for making it.

**Comment by kauffman12** [comment]
The folder names to what? I don't understand what you're doing. It shouldn't crash if it's trying to monitor your last viewed log file at startup and you moved it if that's what you're talking about.

**Comment by tputs** [comment]
Sorry I didn't provide enough info. I'm trying to change my EQ folder path/name from:
C:\EQ\TAKP PC V2.1c\TAKP PC V2.1
to
C:\Quarm (or anything else)
After changing the EQ directory path, EQLP just doesn't load and crashes immediately with the error provided in event viewer.

I tried clearing all recent log history before making the change and it'll still crash for me.

I suppose I don't need to change the folder name, but for context I'd like to since they allow separate Mule accounts now and I'd like to have two separate Quarm EQ folders with easy to recognize names for each.

**Comment by kauffman12** [comment]
And you're using 2.2.10? I wasn't able to get that to happen so far.

**Comment by kauffman12** [comment]
I added some extra checks for this sort of thing. I think 2.2.11 should be good.
