### ISSUE TITLE
Triggers Not Firing or Delayed

### ISSUE THREAD

**Issue by SilvenaRogue** [kauffman12/EQLogParser#145]
Non-issue with 2.2.1.  Updated to 2.2.3 and 2.2.4 and now some triggers aren't triggering at all or (with spell casts) are delayed until another spell is cast.  IE  Spell resist trigger not firing on resist, but will fire when next spell is cast.

^{S1} resisted your (?!Surge|Obulus|Frostreave|Icerend|Fiery){s2}( Rk\. III?)?!$

Loading GINA, this trigger line still works.  Issue described above in EQLP 2.2.4.
Similar issues with interrupts.

Your {s} spell is interrupted.

Editing to add:  This isn't consistent behavior.  The triggers will work correctly a handful of times, then misbehave, then back to behaving.  Honestly just hoping it's something simple and silly that I'm missing and can correct.

**Comment by kauffman12** [comment]
Are they not showing up in the trigger log or is it like sounds not playing? Is there a lot of other triggers happening with higher priority? Just testing those regex with the trigger tester everything seems fine.

**Comment by SilvenaRogue** [comment]
They won't show up until I do something else.  And it can be the only trigger that would be expected to fire, and nothing until I do something else.  It's very odd behavior.

Example using a combat dummy with my necromacer.  Smoldering Bones resists, but the trigger doesn't log or sound off.  I waited over a minute one test before doing anything else.  Spell resisted, I waited.  I finally hit invis and the trigger showed up in the trigger log and the sound played.

![Screenshot_7](https://github.com/kauffman12/EQLogParser/assets/164565783/90ed0b4f-0ec7-4fe2-ba99-28e0e4479b68)


So the triggers are not registering until I do something after what should've triggered.   Cast invis.  Feign.  Hide.  Forage.  Another spell I've already cast wears off.   Same behavior with a spell interrupt, block, or overwrite.  

This only seems to be happening with triggers for spell casting.  Tells, group invites, taskadds all have their own triggers and are working just fine.  

So I'm not sure what is going on.  I thought I'd ask here to see if there is any insight.  Weird weekend lag.  Too many smished gnomes.  I'm at a loss.

**Comment by kauffman12** [comment]
Weird. I'll look at in a little bit. I've mostly been replaying full raids
so maybe didn't see that with reading the live log.

**Comment by SilvenaRogue** [comment]
Upon further testing.. it's not just having to do something on my part.  It's anything writing to the log that makes it update and finally notice the trigger.  Be it what I listed previously, someone else speaking in guildchat, or a simple /who.

It was oddly quiet earlier during original testing.

So probably a non-issue when things are constantly writing to the log.  Just odd when it's quiet.

**Comment by kauffman12** [comment]
I think it's a bug with Everquest. I'm pretty sure they've been trying to optimize the log file. 

Try setting /logint 0. When I do that it doesn't happen. If I set /logint 5 I start seeing what you're seeing. And if I open my log file in notepad the interrupt message I'm expecting is missing. So, it's not stuck in a buffer in the parser. Nothing I use shows the line until another action happens.

**Comment by SilvenaRogue** [comment]
Huzzah!  /logint 0 seemed to do the trick!  I appreciate you pointing that out for me.

**Comment by kauffman12** [comment]
Definitely a bug with EQ. Let's hope they have a fix in the next patch or two.
