### ISSUE TITLE
regex broke

### ISSUE THREAD

**Issue by Svann21** [kauffman12/EQLogParser#146]
I noticed one of my triggers stopped working and playing around with it I found that when regex is clicked on it doesnt work, but if I turn regex off it works.  I think this started in the last patch or 2.

**Comment by kauffman12** [comment]
What's the text you're using that isn't working?

**Comment by Svann21** [comment]
luck\s 
or even if I change it to 
luck farm
it works if regex is unclicked but doesnt work if regex is on.  It used to work.

**Comment by kauffman12** [comment]
Yeah I think I know what's breaking. I can fix that. But in general if you don't need regex then I'd avoid it. It'll be 100x faster if you can just do a simple string search for 'luck '.

**Comment by Svann21** [comment]
Well, for this trigger luck by itself tends to trigger off of lucky hits ALOT, so I added the \s whitespace after.  But more important is that Im thinking the issue also breaks raid triggers that use regex.  Hoping you can fix this before tomorrow night.  :)

**Comment by kauffman12** [comment]
Try 2.2.5. It could have broken some regex that didn't start with ^.

**Comment by Svann21** [comment]
Much thanks!

    On Saturday, March 23, 2024 at 02:13:14 PM MDT, kauffman12 ***@***.***> wrote:  
 
 


Closed #146 as completed.

**Comment by kauffman12** [comment]
No prob
