### ISSUE TITLE
.net 8 installed but Installer doesn't proceed

### ISSUE THREAD

**Issue by burdsjm** [kauffman12/EQLogParser#147]
I installed .Net 8 and restarted the install but it still reports that I don't have it installed.

**Comment by kauffman12** [comment]
Make sure you installed the x64 Desktop version. It should show up if you run this command. It's the last line.

![image](https://github.com/kauffman12/EQLogParser/assets/771335/ba821b6c-4872-4f3f-917e-21a0fee88853)

**Comment by burdsjm** [comment]
Should I get rid of the 9 preview?

![image](https://github.com/kauffman12/EQLogParser/assets/8239455/39dafa43-f637-46dd-b8fc-f2c7d7174932)

**Comment by kauffman12** [comment]
That might be confusing it. Just go to that directory and move it out of
shared for a second and see. You can put it back after install.

**Comment by kauffman12** [comment]
You can try 2.2.6 if you want. It should do a better job at finding version 8.

https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-2.2.6.msi
