### ISSUE TITLE
deleting shortcuts on the daily updates

### ISSUE THREAD

**Issue by Myystroe** [kauffman12/EQLogParser#148]
Is there anyway we can get it to stop deleting shortcuts every time you push an update?

**Comment by kauffman12** [comment]
I wish it were as easy as it sounds.

**Comment by kauffman12** [comment]
This should work going forward. You won't see it when you install 2.2.8 but when you go from 2.2.8 to anything newer it's using custom actions for handling shortcuts and hopefully doesn't touch them if they already exist.
