### ISSUE TITLE
Option to have Reset Timers for Cooldown tracking open in another overlay

### ISSUE THREAD

**Issue by DoubleStuffin** [kauffman12/EQLogParser#149]
Title ^ . Reset timers/Cooldown tracking is awesome, what I'm imagining is

Overlay#1 Active Raid Cooldowns -Things actively running
~Auspice
~Ancestral Aid
~Celestial Regen

Overlay#2 Timers that are resetting/people on cooldown - 
~5mins remaining
~3mins remaining

Pretty much a dropdown in the trigger for sending the reset to the same timer overlay or different overlay of your choosing to keep active triggers and recovering/cooldowns separated

**Comment by kauffman12** [comment]
The trigger configuration is already a little too complicated. What if you specify two different Timer overlays in the trigger as it already has a way to select multiple overlays. Then in the configuration for those overlays you set them up as cooldown. And maybe I can add some checkboxes like.  Show Reset, Show Idle, Show Active. One overlay would have Show Active checked and the other overlay would have Reset and Idle checked. Then I can just hide the timer bars when they're in a state that's not checked?

**Comment by DoubleStuffin** [comment]
I trust you eqlp man

**Comment by DoubleStuffin** [comment]
Out of curiosity, what made you setup the cooldown feature as a property of an overlay rather than a property of a timer? Using GINA I hated that there was no 'all in 1' way to do what you accomplished, so I like it a lot but this was the only part that confused me

**Comment by kauffman12** [comment]
I'm just trying to keep colors and fonts in the overlay. Anything UI related basically. The idea being there could be a lot of 'overlays' at some point with different ways to view what the triggers are defining. Cooldown just became options in the timer overlay because it's also using timer bars. I also didn't want to create a 3rd place to save settings. GINA was always too complicated to me.

**Comment by kauffman12** [comment]
Ok you can try this in v2.2.8. Go into the overlay config and uncheck the options you don't want to see. Then create a 2nd overlay with different options. Use the right-click update selected triggers and assign your triggers to the 2nd overlay so they have both. Then I think it'll do what you were asking for.

New settings for cooldown overlays:
![image](https://github.com/kauffman12/EQLogParser/assets/771335/5c98b6d4-bfbd-4634-baa1-ba1d829e01ae)
