### ISSUE TITLE
Latest Update Active/Reset/Idle Timers

### ISSUE THREAD

**Issue by DoubleStuffin** [kauffman12/EQLogParser#150]
Nice latest update, only problem I have is if I have a trigger selected to use 2 Timer Overlays for Cooldowns
Overlay#1
Active Only

Overlay#2 
Reset
Idle

Overlay#2 also ends up showing Active timers as well

**Comment by kauffman12** [comment]
Can you toggle those settings and re-save? I just tried this again and it seems to be working.  Unless does it show the active timer bar at some later point? For me it starts out fine and works when they switch to reset and idle. And if I trigger one of the timers again it only shows up in the one overlay like I have setup. But I didnt let it run for a long time and repeat.

**Comment by DoubleStuffin** [comment]
Yeah I just tested again after unchecking Active/Idle/Reset options.
It shows Active in both overlays immediately even though overlay#2 is set to only Idle/Reset . Now if the timer is running and I check and uncheck Active for Overlay#2, it correctly hides it from the 2nd overlay, but the very next trigger shows there again. Reset and Idle work as intended though
![image](https://github.com/kauffman12/EQLogParser/assets/111927539/52987111-4ce7-40d5-ac63-9ba1a7a68b02)

**Comment by kauffman12** [comment]
I can't reproduce the problem but I did rearrange some things that may help. Try this test version if you can. If it doesn't help then I guess check the error log and maybe post the settings for one of these triggers that isn't working right.

https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-test.msi

**Comment by DoubleStuffin** [comment]
I tried out the new 2.2.9 release, same thing. I feel like it's maybe just a me problem for something incredibly niche in the first place. I did try retoggling Active/Idle/Reset areas, Triggers are assigned to use both Active and Reset overlays I made, error log is clean (just log loaded in X seconds, rendering using software mode)
![image](https://github.com/kauffman12/EQLogParser/assets/111927539/39dc6772-1018-40b4-a5fa-186988e308e7)
![image](https://github.com/kauffman12/EQLogParser/assets/111927539/e75c8209-e293-4291-845e-43e58f361a7d)
And an example trigger (they all follow the same format)
![image](https://github.com/kauffman12/EQLogParser/assets/111927539/02a7bb4e-04bd-4f42-a500-bdef169e49c4)
![image](https://github.com/kauffman12/EQLogParser/assets/111927539/da83cbdb-1726-4aa2-a57c-a5fb065462ee)
In case I'm an idiot who missed something obvious.

**Comment by kauffman12** [comment]
Have you tried without the custom active color? That's one thing I haven't tested.

**Comment by DoubleStuffin** [comment]
You know I haven't, it didn't occur to me that could be throwing it off. I
can confirm it later tonight though will let you know

**Comment by DoubleStuffin** [comment]
Yep, its the custom color. RIP MY COLOR CODING <3

**Comment by kauffman12** [comment]
Ok I'll look at that when I get home in an hour or so. Shouldn't be a big issue to fix.

**Comment by kauffman12** [comment]
Ok try 2.2.10.

**Comment by DoubleStuffin** [comment]
Works as intended now, ty.
