### ISSUE TITLE
installer gets confused when both x86 and x64 dotnet runtimes are installed

### ISSUE THREAD

**Issue by ElfinRoosters** [kauffman12/EQLogParser#151]
I had both x86 and x64 .net runtimes installed. the x86 dotnet only has version 6.0.3 installed while the x64 has multiple runtimes installed.

When running the 2.2.11 installer, it is finding the x86 dotnet and prompting me to install the 8.0.4 x64 dotnet runtime which is already installed.

To resolve this, i downloaded the x86 dotnet runtime installer for 6.0.3 and used that to uninstall that specific runtime.

**Comment by kauffman12** [comment]
Interesting. It does look like the dotnet --list-runtimes command I'm using doesn't distinguish between x64 and x86. I'll look at other options. Thanks.

**Comment by kauffman12** [comment]
This should be fixed in 2.2.12. It directly checks Program Files now which should only ever have x64 versions.
