### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by Frobub** [kauffman12/EQLogParser#152]
When I launch EQLogParser, the program starts, but it never seems to initialize.  I am not sure if it is this computer or what the problem is.  So the program opens, but just stays in gray scale and never actually starts.  I have used the program on other computers and this does not seem to be an issue.

**Comment by kauffman12** [comment]
Grey scale? You have a screenshot? And check the log file if you can.

**Comment by Frobub** [comment]
![17134084367498673397571532567689](https://github.com/kauffman12/EQLogParser/assets/167382716/e510a56f-a1c5-4f0f-a902-d6c6cd1bc8b6)


Nothing more than this

**Comment by kauffman12** [comment]
I guess double check that dotnet 8 x64 Desktop is installed. The best way to check is look under:
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App
Make sure you see a directory like 8.0.3 or 8.0.4

Maybe delete the settings files here and let it start from scratch:
C:\Users\yourname\AppData\Roaming\EQLogParser\config\settings.txt

See what's in the log file. There's a logs dir above config. It is odd.

**Comment by Frobub** [comment]
So version 8.0.4 is there.  The second file you seemed to list does not exist.  I go to Users my name...then there is no folder called Appdata.  So I tried different routes and no appdata file anyplace on my computer.  I have tried reinstalling the parser a few times and that has not helped.  i assume that would have the same effect as deleting the settings.
    On Thursday, April 18, 2024 at 12:26:55 PM CDT, kauffman12 ***@***.***> wrote:  
 
 


I guess double check that dotnet 8 x64 Desktop is installed. The best way to check is look under:
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App
Make sure you see a directory like 8.0.3 or 8.0.4

Maybe delete the settings files here and let it start from scratch:
C:\Users\yourname\AppData\Roaming\EQLogParser\config\settings.txt

See what's in the log file. There's a logs dir above config. It is odd.

**Comment by kauffman12** [comment]
It's a hidden directly by default. You can type it into the address bar to get there or check the option under View -> Show -> Hidden Items. The install removes log files but not settings.

**Comment by Frobub** [comment]
Here is what the log file looks like

Yahoo Mail: Search, Organize, Conquer 
 
  On Thu, Apr 18, 2024 at 3:29 PM, ***@***.***> wrote:   


It's a hidden directly by default. You can type it into the address bar to get there or check the option under View -> Show -> Hidden Items. The install removes log files but not settings.

**Comment by kauffman12** [comment]
It doesn't look like the log was attached.

**Comment by Frobub** [comment]
Try this

Yahoo Mail: Search, Organize, Conquer 
 
  On Sun, Apr 21, 2024 at 3:20 PM, ***@***.***> wrote:   


It doesn't look like the log was attached.

**Comment by Frobub** [comment]
Yeah.  That isn't there.  Just very minimal info.  I will try it when I get home

Yahoo Mail: Search, Organize, Conquer 
 
  On Mon, Apr 22, 2024 at 10:05 AM, ***@***.***> wrote:   


I still don't see anything. Here's an example of what's Normal. If you see anything besides this especially if there are ERROR or WARNINGs showing up. Maybe just paste those manually if you can.

2024-04-22 10:59:02,357 [1] INFO EQLogParser.App - Using DotNet 8.0.4
2024-04-22 10:59:02,363 [1] INFO EQLogParser.App - RenderMode: SoftwareOnly
2024-04-22 10:59:02,532 [1] INFO EQLogParser.MainWindow - Window Pos (15, 77)
2024-04-22 10:59:02,532 [1] INFO EQLogParser.MainWindow - Window Size (1805, 968)
2024-04-22 10:59:03,405 [1] INFO EQLogParser.MainWindow - Initialized Components
2024-04-22 10:59:04,588 [1] INFO EQLogParser.MainWindow - Selected Log File: R:\eqlog_Kizant_xegony.txt
2024-04-22 10:59:06,408 [1] INFO EQLogParser.MainWindow - Finished Loading Log File in 2 seconds.

**Comment by kauffman12** [comment]
If you're on windows 10 try the latest. Someone else just found a problem with the install that doesn't happen on 11 for some reason.

https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-install-2.2.13.exe

**Comment by yeroca** [comment]
I had the same problem during an upgrade of EQLP on Win 11.  After installing the dot Net upgrade, when I ran EQLP, it would say there's a newer version, and I'd click "yes" to install it.  EQLP's window would disappear, but no installation window would pop up. I ended up downloading the installer directly, and running it.  That worked.

**Comment by kauffman12** [comment]
Any update on this? Did installing a newer version help? The latest link is this:
https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-install-2.2.15.exe

**Comment by Frobub** [comment]
IsDamageOverlayEnabled=TrueNpcShowTanking=FalseSelectedOverlayClass=All ClassesChatFontSize=16OverlayDamageMode=0WindowWidth=400OverlayLeft=1089.3333333333333WindowState=NormalWindowHeight=250LastOpenedFile=C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\Logs\eqlog_Drabab_bristle.txtMaxOverlayRows=6OverlayWidth=497.6WindowTop=92ChatFontFamily=Segoe UINpcShowHitPoints=FalseDamageSummaryColumns=Name,PercentOfRaid,Total,DPS,SDPS,TotalSeconds,Hits,Max,BestSec,BaneHits,Avg,AvgCrit,AvgLucky,CritRate,LuckRate,Special,ClassNameChatFontFgColorMaterialDark=#DDFFFFFFShowOverlayCritRate=TrueWindowLeft=1989HideOverlayOtherPlayers=FalseOverlayHeight=202.66666666666666OverlayFontSize=13OverlayTop=224.66666666666666

This is what my file said before.  I have not been home.  I am copying what you pasted in the file now.
    On Monday, April 29, 2024 at 10:11:21 PM CDT, kauffman12 ***@***.***> wrote:  
 
 


Any update on this? Did installing a newer version help? The latest link is this:
https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-install-2.2.15.exe

**Comment by Frobub** [comment]
Copying what you posted and deleting the stuff that was in there worked!  I like the new version.  Thank you
    On Monday, April 29, 2024 at 10:11:21 PM CDT, kauffman12 ***@***.***> wrote:  
 
 


Any update on this? Did installing a newer version help? The latest link is this:
https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-install-2.2.15.exe

**Comment by kauffman12** [comment]
Oh good! Yeah maybe some setting got corrupted or if you had a really old version there maybe was something that didn't upgrade right... Anyway glad to hear. I'll close this.
