### ISSUE TITLE
Feature Request - Daily Log Archive

### ISSUE THREAD

**Issue by lmarkus001** [kauffman12/EQLogParser#153]
Tools > Log Management > Log if file age > **1 DAY**

Currently the options leap from Any Age to Weekly.  I find it helpful to review a specific day's log as we do a number of raids on a specific day.  So having the log auto archive when I fire it up if the log is from the previous day or older would be ideal.  (This is a setting that is available in GINA.)

**Comment by kauffman12** [comment]
I was just updating this stuff so I added 1 day and 3 days. Give 2.2.12 a try.
