### ISSUE TITLE
EQLP will not launch after update

### ISSUE THREAD

**Issue by SilvenaRogue** [kauffman12/EQLogParser#154]
Went through with the auto-update and tried to launch EQLP.  What I get is the briefest flash on the windows taskbar and then nothing.  EQLP shows up in the Task Manager under Background processes.  Multiple times if try launching more than once.  I've even uninstalled to reinstall and I come to the same result.

What did I break?

**Comment by kauffman12** [comment]
Anything in the log? It's under.

C:\Users\username\AppData\Roaming\EQLogParser\logs\EQLogParser.log

**Comment by SilvenaRogue** [comment]
[EQLogParser.log](https://github.com/kauffman12/EQLogParser/files/15067016/EQLogParser.log)

**Comment by kauffman12** [comment]
Hmm. See if putting this file in your C:\Program Files\EQLogParser directory gives a different error or helps in any way.

I had to zip it so just unzip the file. You'll see it's System.Drawing.Common.dll and just drop it in the directory above. It sounds like some additional files may need to be installed but I don't know why.

[System.Drawing.Common.dll.zip](https://github.com/kauffman12/EQLogParser/files/15067095/System.Drawing.Common.dll.zip)

**Comment by SilvenaRogue** [comment]
Tada!  That got it working.  Much appreciated!

**Comment by kauffman12** [comment]
Cool. I'll add that to the install. I imagine other people must have the same issue. Do you have windows 10 maybe? I haven't had a chance to test on there recently.

**Comment by SilvenaRogue** [comment]
Yep, I am running Windows 10.
