### ISSUE TITLE
Feature Request: Bigger Font Sizes

### ISSUE THREAD

**Issue by alphablueofficial** [kauffman12/EQLogParser#155]
This is a small request, but would it be possible to increase the maximum font size up from 50 to something like 200?

My use case is that I want to show backstab numbers in giant numbers on screen for ease of viewing while playing / streaming.

Thank you!

**Comment by kauffman12** [comment]
Assuming you mean just for the text and timer overlays then sure. I could add some more.

**Comment by alphablueofficial** [comment]
That's exactly what I'd like! I want BIG, obnoxious text on an overlay when I backstab - so 50pt font size just isn't big enough!

**Comment by kauffman12** [comment]
This is in 2.2.14.
