### ISSUE TITLE
Feat Req: Allow choosing multiple log files to assign triggers

### ISSUE THREAD

**Issue by LamahHerder** [kauffman12/EQLogParser#156]
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/b5cad482-2b63-425e-ac5e-840373b36b6c)

Would like to replace GINA with eqlogparser and I run a few different groups at different times
Would be much easier to shift+select multiple log files to select triggers instead of going to each log file individually

**Comment by kauffman12** [comment]
So if you select two characters at the same time. What does the tree display? A state that combines them all where triggers are only checked if both characters have them? Or the tree of the last or first selected character. And then just the changes get applied to both? 

Is there anything else simpler that could be done? How different are your trigger selections for the 3 different necros? If they are all the same I could add a copy/paste sort of thing so you set one up and just paste the settings one at a time on the others.

**Comment by LamahHerder** [comment]
The issue is you cant shift+select multiple characters at the same time

This would be the UX flow desired, select multiple characters then configure assigned triggers for the multiple selected characters

**Comment by kauffman12** [comment]
Try 2.2.14 and see if it does what you want.

**Comment by LamahHerder** [comment]
> Try 2.2.14 and see if it does what you want.
FYI the README.md is linking to 2.2.13 that does not exist

Works perfect, selecting multiple and associated triggers
Thank you
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/1ba9a325-ddaa-471e-88d5-c3c6385e1642)
