### ISSUE TITLE
Feat Req: Trigger folder hiearchy inheritence

### ISSUE THREAD

**Issue by LamahHerder** [kauffman12/EQLogParser#157]
Would like to create a trigger folder and assign it to a log
When new triggers are added/moved to a folder they are automatically assigned the status of the folder

Currently today when you add a new trigger to a folder it is not enabled if the folder is checkmarked as active
Instead it changes the folder status to partial-active because it now has a new trigger that is not enabled

**Comment by kauffman12** [comment]
That probably makes more sense. I'll see if I can fix that and if anyone complains they liked it the old way I guess I could have a setting somewhere to decide how it should work.

**Comment by LamahHerder** [comment]
Thank you for considering

This is how it works with GINA and common experience/expectation from explorer.exe

It adds great functionality of quickly moving subfolders to enable/disable things which is especially helpful for raid triggers to reduce load

Example folder structure from GINA that I was using some time ago
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/9c1d945d-92d1-4454-8baa-3304a7f21183)

**Comment by kauffman12** [comment]
So for this you almost mention drag and drop? That isn't working yet for sure if you think everything dropped should change to enabled/disabled based on the folder it goes in?

**Comment by LamahHerder** [comment]
> So for this you almost mention drag and drop? That isn't working yet for sure if you think everything dropped should change to enabled/disabled based on the folder it goes in?

Yes thats the thought
The triggers would inherit the folder setting basically

**Comment by kauffman12** [comment]
I changed Create Trigger and Create Folder to inherit the parent's setting in the last version but looking more at drag and drop. It is a little weird. Right now, you can safely reorganize your entire tree structure without changing which triggers are actually enabled. I don't know if I'd want to break that.

**Comment by kauffman12** [comment]
What if this updating the state of what gets dropped requires holding the shift key in or some modifier like that?

**Comment by kauffman12** [comment]
Ok try this out in 2.2.15. Hold shift when you drop and it should take the state of the folder you dropped it in.
