### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by LamahHerder** [kauffman12/EQLogParser#158]
Sorry was running an older version 2.2.8, will confirm with latest version tomorrow and delete if no longer an issue

![image](https://github.com/kauffman12/EQLogParser/assets/22425296/db578fcd-3e13-4a96-9fc6-981c0e5ece97)
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/a40921cf-e0ea-4870-b302-e5f6f293872f)

Example of log file entries
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/aeba878e-3c93-43c2-be7a-2c472dbcc5cd)

**Comment by kauffman12** [comment]
It seems to be working for me in the latest but I can't think of what changed between now and 2.2.8 that would have caused the issue. If it's still happening maybe open the trigger log and click on the entry and make sure it selects this trigger. Just in case there's still an old one in memory somehow that isn't showing up in the tree. The parens in the timer name isn't something that the parser itself adds anywhere that I can think of.

**Comment by LamahHerder** [comment]
I shouldnt test things at night, sorry, please delete

I found the culprit, missed the alt text because of a copy/paste of a previous trigger...
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/29f09039-2c27-415e-9938-86a972750f03)

**Comment by LamahHerder** [comment]
I shouldnt test things at night, sorry, please delete

I found the culprit, missed the alt text because of a copy/paste of a previous trigger...
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/16824afd-7471-4c31-8493-53983f7b8d2f)
