### ISSUE TITLE
Mercenaries do not reliably parse

### ISSUE THREAD

**Issue by adetia9** [kauffman12/EQLogParser#16]
I'm not sure if this is an EQ issue, a settings issue or a parser issue.

It can be very tricky to get the DPS mercenaries that are fighting in our group to show up on the parse information.
If it isn't working I just close and reopen like a dozen times and eventually they start showing up, but most of the time they do not.

Is there a setting I can check on, or is anyone else seeing this same issue?

I use this parser exclusively now and have appreciated the thoughtfulness and work you've put into it, as well as the recent updates, so thank you for your hard work! :)

**Comment by kauffman12** [comment]
What's the name of your merc? It's supposed to at least look for joining the group messages to know who is possibly a player or merc but there could be some bugs with non player like names.

**Comment by adetia9** [comment]
05/30/21 10:04:08 PM	a clockwork fighter DCXLVIII has joined the group.

**Comment by kauffman12** [comment]
Try 1.8.31. It was ignoring names that don't look like player names but that's changed. If somehow an NPC gets counted as a player you can remove it from the player list. That shouldn't happen unless a merc has the same name as an NPC.

**Comment by adetia9** [comment]
this appears to be fixed!
hooray!

**Comment by kauffman12** [comment]
cool
