### ISSUE TITLE
Spell Cast Timeline Export

### ISSUE THREAD

**Issue by Kashmirre** [kauffman12/EQLogParser#161]
Can we get the same copy as on the Spell Cast Timeline as on the Spell Counts? Or at least the option to do all the data as the large image. Or can we get the same copy across the board?

IE Spell Counts
![image](https://github.com/kauffman12/EQLogParser/assets/88602424/73c49d69-ab57-45f4-8b86-7f56888f61bb)

Spell Cast Timeline
![image](https://github.com/kauffman12/EQLogParser/assets/88602424/187a4fe3-f55a-445f-ac51-4fafae381424)

**Comment by kauffman12** [comment]
Gamparse BBCode doesn't really make sense as it's specific to spell counts. I could add regular BBCode and Large Image but neither may work very well with thousands of lines. That's why they're not on there. The timeline is just typically so very long.

**Comment by Kashmirre** [comment]
That will work. I use the filters to get the data I need that lessen the results.


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kauffman12** [comment]
Check 2.2.16.

**Comment by Kashmirre** [comment]
Looks good. Thanks!
