### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by SilvenaRogue** [kauffman12/EQLogParser#165]
I had log management set to compress the files when archiving.  At first, no issues.  Had to check an archived parse, all good.  Everything saves and can be reopened in EQLP.

My problem seems to be EQLP archiving an already archived file (because I've opened it again?), resulting in .txt.gz.gz vs just .txt.gz when first archived.  When this happens, I can no longer open these files in EQLP.  Attempts to open them in a text format (notepad), either stalls, fails, or gibberish (to me at any rate).  

I added a copy of the EQLP log file showing when things were archived/opened.  Original archive working fine (eqlog_char in the EQ folder).  Then FileUtil archiving files already in my archive folder.  Log Management set for 1 day and to compress.  Haven't changed any of those settings.
![logmanage](https://github.com/kauffman12/EQLogParser/assets/164565783/b7058a3e-e28d-40a9-93ae-4076882ba072)

Not sure what I did this time.  But it's definitely wonky.  Is there a way to have it compress but not as a .gz?  Just leave it as a text file?

![txtgzgz](https://github.com/kauffman12/EQLogParser/assets/164565783/c638fc63-de0c-4083-846a-b535bd62334c)

![txtgzgz2](https://github.com/kauffman12/EQLogParser/assets/164565783/a099a696-c9fd-49f4-bfa5-3afe142b22fc)

[EQLogParser_new copy.log](https://github.com/kauffman12/EQLogParser/files/15286711/EQLogParser_new.copy.log)

**Comment by kauffman12** [comment]
Yeah sounds like a bug. I'd just use winzip or something to unzip the file
once. Turn the .gz.gz into a .gz. It's just compressing it a 2nd time.

**Comment by SilvenaRogue** [comment]
Okie dokie.

**Comment by kauffman12** [comment]
Try 2.2.17. Hopefully it won't happen anymore.
