### ISSUE TITLE
Bug: Client locksup when creating timer overlays

### ISSUE THREAD

**Issue by LamahHerder** [kauffman12/EQLogParser#166]
Opened eqlogparser, noticed new version
Closed eqlogparser, downloaded and updated 2.2.16 -> 2.2.18

1. EQ not running, opened eqlogparser
2. Right click overlay, choose new overlay
3. client becomes unresponsive, I had to close it then reopen

After reopen
1. Attempted to delete the new timer
2. Client became unresponsive
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/a5a08034-0fdb-448c-b609-8d8b68240a6e)
3. 2-3min later it deleted the new overlay

edit
I just tried to recreate after making this issue and it's not locking up client.....

**Comment by kauffman12** [comment]
Nothing in the logs?

**Comment by LamahHerder** [comment]
Im not sure if there is another log but ive never noticed anything weird in log
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/efc41a3c-1638-4d91-b6a0-5e558c6edfa5)

**Comment by kauffman12** [comment]
I haven't seen any way to duplicate this one but I made some changes that might keep the settings from getting messed up. Also do you ever run two instances of the parser at the same time?
