### ISSUE TITLE
"Biting" in tank summary isn't correct

### ISSUE THREAD

**Issue by jensenramsu** [kauffman12/EQLogParser#17]
The parser is not counting Blocks, Dodges, Parries, Misses, or Ripostes for the Bite attack in the tanking breakdown.

Examples:
[Mon May 31 20:29:41 2021] A bloodthirsty gnawer tries to bite Vandil, but Vandil ripostes!
[Mon May 31 20:29:49 2021] A bloodthirsty gnawer tries to bite Vandil, but misses!
[Mon May 31 20:29:49 2021] A bloodthirsty gnawer tries to bite Vandil, but Vandil parries!
[Mon May 31 20:29:50 2021] An explosive gnawling tries to bite Vandil, but Vandil's magical skin absorbs the blow!
[Mon May 31 20:29:50 2021] A bloodthirsty gnawer tries to bite Vandil, but Vandil blocks with its shield!
[Mon May 31 20:29:50 2021] A bloodthirsty gnawer tries to bite Vandil, but Vandil dodges!

**Comment by kauffman12** [comment]
Thanks. Try out 1.8.30 for the fix.
