### ISSUE TITLE
Req: Option to stack countdowns without logfile grouping

### ISSUE THREAD

**Issue by LamahHerder** [kauffman12/EQLogParser#170]
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/3af4ba4d-0eb8-4235-a287-bc86bf8733e6)
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/636c683c-5c78-4502-a361-55a4d4b402e3)

It seems like the countdown stacking is grouping by log file
Would like the option to have the stacking is just FIFO to the overlay

Current stacking method
Log1 - @ 1pm triggered
Log1 - @ 2pm triggered
Log2 - @ 1pm triggered
Log2 - @ 2pm triggered
Log3 - @ 1pm triggered

Preferred stacking option
Log1 - @ 1pm triggered
Log2 - @ 1pm triggered
Log3 - @ 1pm triggered
Log1 - @ 2pm triggered
Log2 - @ 2pm triggered

**Comment by kauffman12** [comment]
And that's worth Sort By set to Remaining Time in the overlay settings?

**Comment by LamahHerder** [comment]
> And that's worth Sort By set to Remaining Time in the overlay settings?

Wasnt aware of that option

But wouldnt that still group it by logfile instead of a global grouping in that overlay?

**Comment by LamahHerder** [comment]
sort by = trigger time in that screenshot

**Comment by kauffman12** [comment]
Yeah I'll look at that one. Just making sure which option was selected.
