### ISSUE TITLE
Timer Overlay fonts never update after selection

### ISSUE THREAD

**Issue by mfrerking** [kauffman12/EQLogParser#172]
I've been stuck with this same timer font for years and I don't understand it. I didn't see this addressed in any of the closed issues so I'm assuming it's a "me" problem, but any ideas why? The text overlay font changes without issue.

![explorer_2024-05-22_02-23-18](https://github.com/kauffman12/EQLogParser/assets/94870826/5e4ad6e4-af0f-4fb3-b736-ca9c1ef72986)

**Comment by kauffman12** [comment]
What do you mean stuck? The drop down has no other options?
