### ISSUE TITLE
Usability improvement: If a user used a regex-based trigger variable, automatically enable the 'use regex' option

### ISSUE THREAD

**Issue by martinb-uk** [kauffman12/EQLogParser#173]
Currently a user might add a regex based trigger variable {s} , {s1} etc into their triggers, and then totally miss the 'use regex' option (or not have any idea what a 'regex' is for the less technical).

I think it would be useful to have it automatically set if one of these special variables is detected in the trigger string.

![image](https://github.com/kauffman12/EQLogParser/assets/19375324/f2779820-4678-41c2-9174-7a65c18cb7ad)

**Comment by kauffman12** [comment]
I added a pretty simple version of this in 2.2.21. May be able to improve it later.
