### ISSUE TITLE
Parse archived/saved character as wrong class and as You

### ISSUE THREAD

**Issue by SilvenaRogue** [kauffman12/EQLogParser#175]
Saw it once before, thought I was just crazy.  

Had the parser running last night during an open raid, all was well.  Prior to archiving, I could just view select classes and I'd show up under the correct class with the character name.  Today, to do some comparisons.. I show up as You and the wrong class lol

![Screenshot_1](https://github.com/kauffman12/EQLogParser/assets/164565783/ce3a390a-0f35-47ae-ae84-8647e03e225c)

I played an enchanter (when I look at spell counts, etc, it definitely shows enc spells.)

What did that?

Error Log too.  
[EQLP Error Copy.txt](https://github.com/kauffman12/EQLogParser/files/15448063/EQLP.Error.Copy.txt)

**Comment by kauffman12** [comment]
It looks like it's not parsing the player name properly when opening the .gz files. Should be a small fix.

**Comment by kauffman12** [comment]
Should be fixed in 2.2.21.
