### ISSUE TITLE
Having a small problem with the "if triggered again" setting

### ISSUE THREAD

**Issue by esr-sudo** [kauffman12/EQLogParser#177]
I'm sure this is something I have set wrong on my side but I am having a complication with a trigger repeating the sound/text to speak field multiple times where it is not desired.   It is not an issue with the timer bar, just the initial sound/text to speak.

I am wanting it to say Acid when the trigger is first seen in the log as an audible reminder to go in, but it is spamming me with Acid Acid Acid Acid Acid from it hitting other people in the raid

![nexona](https://github.com/kauffman12/EQLogParser/assets/60377940/865660a3-7d6e-4bb1-9fd0-dcf1e58d9d3f)

Is there something I have set wrong?

**Comment by kauffman12** [comment]
Looking at the spell data maybe add Your at the start?
Your body burns as the acid hits you

**Comment by esr-sudo** [comment]
I'm wanting it to trigger if the log file sees it hitting other people.  Because if I happened to be ducked around the corner, it won't hit me, but I would see it hit the other people, so I know when to expect it to go iff.

I'm just not sure why the sound/text to speak is going off if it sees the same trigger again, while the timer is up and I have do nothing checked.

**Comment by kauffman12** [comment]
That's just how the Trigger settings work. The If Triggered Again only applies to Timers. It sounds like you'd want another setting for the Trigger section for some time delay before before the same trigger can be handled again.

**Comment by esr-sudo** [comment]
Sure, that would work.

**Comment by esr-sudo** [comment]
Sure that would work.

**Comment by kauffman12** [comment]
Ok try 2.2.23 and setting Trigger Lockout Time to 2 seconds or something.
