### ISSUE TITLE
Spell counts reporting Zero 2.2.23

### ISSUE THREAD

**Issue by Neclub** [kauffman12/EQLogParser#178]
v2.2.23

Spell counts are reporting 0.

Had someone else check their parse as well, with the same result.
![EQLogParser_KESoZ7lLHn](https://github.com/kauffman12/EQLogParser/assets/18217817/6c5c6583-6cef-43f5-b2f5-e732dadbb5e3)

**Comment by kauffman12** [comment]
Ok try updating to 2.2.24.
