### ISSUE TITLE
Sympathetic Hand of Holy Wrath

### ISSUE THREAD

**Issue by Myystroe** [kauffman12/EQLogParser#180]
Sympathetic Hand of Holy Wrath line is not showing up on parse on procs or heals (it does both) for priests, at least that ive seen.

**Comment by kauffman12** [comment]
I'll make a change to help with this problem but there's tons of spells with the same message. It most likely isn't going to get the right name if all it has to go by is the received/lands on message. So, you may have to look for Received Arms of Holy Wrath VIII Recourse or who knows what. I'll be in 2.2.26 sometime soon.
