### ISSUE TITLE
Jump to trigger definition from trigger log enhancement

### ISSUE THREAD

**Issue by BronsonMagnan** [kauffman12/EQLogParser#181]
It would be useful, when looking at a trigger log, to be able to right click menu on the trigger in the log, and open the trigger manager, for that character, at the spot where that trigger is defined and temporarily highlight it.

**Comment by kauffman12** [comment]
This is updated in 2.2.26 to work better when you have a bunch of characters defined. It now selects the character and then highlights the trigger. Note that it's not off the right-click. You open the Trigger Manager and click on rows in the Trigger Log and it selects the Trigger in the manager. The idea is that you can move the windows around and be looking at the log and manager at the same time as the UI from one updates based on the other changing.
