### ISSUE TITLE
Initial load of log slow

### ISSUE THREAD

**Issue by LamahHerder** [kauffman12/EQLogParser#185]
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/aef21fe1-61aa-40be-845d-6b3f49220dd2)

1 - open eqlogparser
2 - Click File, select a historic file, click NOW

**Comment by kauffman12** [comment]
Is there anything in the error log? It might get slow if it's constantly printing errors.

**Comment by LamahHerder** [comment]
Only occurs on first start, tested with older version and latest version of eqlogparser
Tested with logfile that was in recent list
Tested with a copy/rename of same log file
Tested with a bazaar mule that has no combat text
Tested with last hour and now
With all this testing I did notice a warn for a file that does exist that occurred one time...

SS is of a 95 meg log file that was listed as recent under FILE
1. open eqlogparser
2. File - > open previous - > Last hour

![image](https://github.com/kauffman12/EQLogParser/assets/22425296/e05fc071-3249-4d41-b0dd-4a404188e29f)
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/697f6e75-ff47-496e-8350-44d30f1a6ef2)
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/39b08894-0b85-4288-a3c1-e9b8574e67a1)

**Comment by LamahHerder** [comment]
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/bcc32135-7dc5-4b65-ba8c-371c30ca9a1b)
Also oddly trigger manager showing some files as RED when those files actually do exist....

**Comment by LamahHerder** [comment]
Does eventually find more of them...
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/58674ece-c867-47db-ae54-53a480529aa8)

**Comment by LamahHerder** [comment]
Maybe wrong rabbit hole... I am assuming those files got archived so the file does not exist
May want to create empty file after archive?
![image](https://github.com/kauffman12/EQLogParser/assets/22425296/e0c0ee3e-6977-4421-9399-6e0c841f64b3)

**Comment by kauffman12** [comment]
Yeah maybe I can do that. Was trying not to conflict with eq creating them
but if it fails I can prob just ignore it. Might be able to speed up trying
to start that many at once.

**Comment by LamahHerder** [comment]
> Yeah maybe I can do that. Was trying not to conflict with eq creating them but if it fails I can prob just ignore it. Might be able to speed up trying to start that many at once.

So when you load the file to be parse'd it is checking the list of enabled trigger files to see if they exist? So it is the timeout of those file checks that is slowing this down on first load?

**Comment by kauffman12** [comment]
Mostly it's cause the status is polled for every 5 seconds but I can change that to have each log reader publish updates when changes changes. Then it shouldn't have any delay. Plus when it opens a log file for a character it also creates a TTS synthesizer, loads and caches all the triggers, loads the overlay styles, etc. It takes a little longer than just opening the file for each one. Doing that for one character at a time is fast but 20 is a lot. If you look at process manager you might see the parser using 50+ threads at startup.

**Comment by kauffman12** [comment]
Try this version and see if at least gets the status on all those characters a little better. There will still be an initial delay but it's starting the file reading all at once now at the end of all the caching and stuff.

https://github.com/kauffman12/EQLogParser/raw/master/Release/test/EQLogParser-install-2.2.29-test.exe

**Comment by kauffman12** [comment]
Just try 2.2.30 now. I removed that test build.

**Comment by LamahHerder** [comment]
Much much faster on that initial load for sure, loading last hour on a log from few days ago just takes 2-3s

**Comment by kauffman12** [comment]
Ok then that's prob good enough for now.
