### ISSUE TITLE
Audio Trigges Text To Speech always uses first (default) Speaker, no matter what is selected

### ISSUE THREAD

**Issue by jensgreven** [kauffman12/EQLogParser#186]
Audio Trigges Text To Speech always uses first (default) Speaker, no matter what is selected in Character settings in "Advanced Mode"

**Comment by jensgreven** [comment]
Error seems to appear since version 2.2.27

**Comment by kauffman12** [comment]
Ah yeah I see. Try 2.2.28 in a minute.
