### ISSUE TITLE
Triggers talk over each other

### ISSUE THREAD

**Issue by Peon25** [kauffman12/EQLogParser#187]
The new version has trigger messages blend into each other, so I'm missing audible triggers while others are going off. Last night I consistently had 2 or more messages talking at the same time, instead of waiting in turn. I keep my sped up at 4 or 5 so the messages finish quickly, but last night it was overly difficult to discern if I missed an epic click, a runaway message, etc.

I play a vicious bard, so I rely on both visible and audible triggers for everything that I have going on with DPS and ADPS timing, events, and so on. The start of an event generally has 10-15+ timer bars firing off, if that's any indication!

**Comment by kauffman12** [comment]
Is it doing that in 2.2.27 or 2.2.28?

**Comment by Peon25** [comment]
.26 is what I downloaded before raids yesterday afternoon. I still had the parser open this morning to diagnose some of the newer bards and thought I'd make a report.

I'll update for tonight's raids and will let you know! I run paladin on Monday so a little less hectic.

Thanks sir!

**Comment by Peon25** [comment]
New version is great, I noticed you had also mentioned it in the update notes for v2.2.28. Thanks Kizant!

**Comment by kauffman12** [comment]
No problem!
