### ISSUE TITLE
Tanking DPS chart isn't relevant/useful for player/DPS

### ISSUE THREAD

**Issue by MartinBrown1983** [kauffman12/EQLogParser#19]
When investigating how effectively each character is tanking, I took a look at the tanking DPS chart and I see the following:

![image](https://user-images.githubusercontent.com/19375324/133887391-ad84fff2-96dd-49f9-a30f-996f91f8b72e.png)

As can be seen, the first tank (Tankpotato) has a realistic graph line drawn for him (Tanking from time 1 to time 2 as annotation on the screenshot). The second tank (Drakar) takes over at time 2, and his tanking DPS line starts at 0, and gradually increases. 

This obviously isn't representative of the true 'DPS' the tank is taking at this time.

It appears to me like the tanking DPS line is taking into account the full duration of the fight, rather than being bounded by a realistic time of 'when that character started tanking'. 

I wonder if you could do something to make this aspect more useful?

Many thanks.

**Comment by MartinBrown1983** [comment]
After using the tool a bit more, I can see this issue isn't isolated to tanking. It's also the normal damage DPS charts. As can be seen in this screenshot, this is what happens when a melee joins the fight late:
![image](https://user-images.githubusercontent.com/19375324/133908705-28e6d57f-105d-4ec3-a147-c5cfc0c63fef.png)

It makes it appear like the melee's DPS is increasing over time, but actually this isn't really the case. The tool is showing the effective DPS since the start of the fight which isn't what a user would expect to see. 

I guess you'd need to implement time buckets (e.g. within a 10 second period) and calculate the DPS within the time bucket to give a more representative graph (for both tanking and damage)

**Comment by kauffman12** [comment]
That makes sense I think. I'll take a look.

**Comment by kauffman12** [comment]
This should be addressed in 2.0.0 that I plan on updating within the next few days.

**Comment by MartinBrown1983** [comment]
Great - many thanks! Can't wait to test it
