### ISSUE TITLE
Update to 2.2.33, all triggers are gone...

### ISSUE THREAD

**Issue by BronsonMagnan** [kauffman12/EQLogParser#192]
Update to 2.2.33, all triggers are gone from software view, however the triggers.json file remains fully populated.
Is there a way to bring the details of triggers.json back into eqlog parser?

**Comment by kauffman12** [comment]
In your AppData directory is there a triggers.db file still?
C:\Users\user\AppData\Roaming\EQLogParser\config\triggers.db

If so what size is it? And are there any errors in the log file? I've downgraded and upgraded a bunch of times and haven't seen any issues. I assume you had 2.2.31 prior to this?

The json file is old and not used anymore. If you were to delete your triggers.db file it should read the json and import all those triggers. However, I wouldn't get rid of your triggers.db just yet. As long as it still exists it should be recoverable. Just need to figure out why it's not loading.

**Comment by kauffman12** [comment]
I switched back to the older version of LiteDB to see if that helps. It's the only change in 2.2.34.

**Comment by kauffman12** [comment]
Try copying this to your config directory where triggers.db exists and run this program I just made from a command prompt. It should print out the triggers it finds. Hopefully it finds them and then I could find a way to re-export them somehow. The triggers.db and this DBChecker.exe just need to be in the same directory so copy them wherever really.

https://github.com/kauffman12/EQLogParser/raw/master/Release/tools/DBChecker.exe

**Comment by BronsonMagnan** [comment]
it only found 4 records, plus I loaded in triggers from shares, closed .33 updated to .34 and those triggers are gone too. It switches back to basic mode, all the characters are gone from under the list. The phonetic dictionary is blanked out.

**Comment by BronsonMagnan** [comment]
The restore function loaded my settings from a backup, and that data is persisting through application restarts.

**Comment by kauffman12** [comment]
Hmm yeah it's not good if it only found 4 records. There might be a bug in that new version of LiteDB although it hasn't caused a problem on my two systems.

I guess the only thing you can really do if it even helps is just move the triggers.db files out and start the parser. It should at least re-import the json file into a new db.

**Comment by BronsonMagnan** [comment]
Downgrading from .34 to .33 replicates the problem, the triggers.db file shrinks way down in sizee.

**Comment by BronsonMagnan** [comment]
The Json did not import when I deleted the triggers.db on this test vm.
Or atleast  the outcome was not visible triggers in the application

**Comment by BronsonMagnan** [comment]
Yea, there is an exception in litedb: 2024-07-20 01:24:34,873 [1] ERROR EQLogParser.TriggerStateManager - LiteDB.LiteException: Detected loop in FindAll({0})
   at LiteDB.Constants.ENSURE(Boolean conditional, String format, Object[] args)
   at LiteDB.Engine.IndexService.FindAll(CollectionIndex index, Int32 order)+MoveNext()
   at LiteDB.LinqExtensions.<>c__DisplayClass2_0`2.<<DistinctBy>g___|0>d.MoveNext()
   at LiteDB.Engine.LiteEngine.<>c__DisplayClass5_0.<EnsureIndex>b__0(TransactionService transaction)
   at LiteDB.Engine.LiteEngine.AutoTransaction[T](Func`2 fn)
   at LiteDB.Engine.LiteEngine.EnsureIndex(String collection, String name, BsonExpression expression, Boolean unique)
   at LiteDB.Engine.LiteEngine.RebuildContent(IFileReader reader)
   at LiteDB.Engine.RebuildService.Rebuild(RebuildOptions options)
   at LiteDB.Engine.LiteEngine.Rebuild(RebuildOptions options)
   at LiteDB.LiteDatabase.Rebuild(RebuildOptions options)
   at EQLogParser.TriggerStateManager.Start()

**Comment by kauffman12** [comment]
Thanks I'll see if there's some problem with rebuilding indexes when there's no records yet maybe.

**Comment by BronsonMagnan** [comment]
Please review this release note for a change made to 5.0.18 https://github.com/mbdavid/LiteDB/releases/tag/v5.0.18 the rebuild methods seems to have had a breaking change.

**Comment by kauffman12** [comment]
Try 2.2.35 and see if it loads the json file this time. I think I know why that stopped working and yeah I took out the rebuild calls. It's hard finding a version of LiteDB with everything working..

**Comment by kauffman12** [comment]
Remember to close the parser and remove and triggers.db files. It's supposed to check if that file exists. If it doesn't it tries to load the json. Or it used to.

**Comment by BronsonMagnan** [comment]
initial load of 2.2.35 - triggers and characters are gone again. Deleting the triggers.db file DID bring back my older triggers from the JSON presumably. I will save a backup of this state.

**Comment by BronsonMagnan** [comment]
although the triggers are back, the characters are still gone from the advanced view
and the phonetic dictionary was blanked as well.

**Comment by kauffman12** [comment]
Back when json was being used the parser didn't have the dictionary or multiple characters.

So you had some characters created from 2.2.34. Installed 2.2.35 and they were gone? Without touching the triggers.db file yet?

**Comment by BronsonMagnan** [comment]
ok, so I exported those triggers. Then restored my backup, then imported those triggers from export file. the current state is usable.

**Comment by kauffman12** [comment]
I guess try installing 2.235 again to make sure it doesn't keep removing the triggers for some reason and if there's any more of those errors in the log.

**Comment by kauffman12** [comment]
Ok thanks.
