### ISSUE TITLE
Heal Parse: Exclude pets

### ISSUE THREAD

**Issue by WaringMcMarrin** [kauffman12/EQLogParser#195]
Would it be possible to update the healing parses to exclude pets as swarm pets can inflate the healing numbers produced by AE heals.

**Comment by kauffman12** [comment]
Have you tried turning this option off?

![image](https://github.com/user-attachments/assets/0509e41c-0c75-4956-a47d-1add345548ab)

**Comment by WaringMcMarrin** [comment]
Thanks for pointing out the option that I missed, I will check that out later
