### ISSUE TITLE
Countdown triggers not disapearing or counting down

### ISSUE THREAD

**Issue by LamahHerder** [kauffman12/EQLogParser#196]
ver 2.2.38
I see no relevant errors in the normal error log
`^(The Guildhall Portal has been aligned to {S1}|Zeflmin Werlikanin says, \'The teleport stone is currently aligned to {S1}\.\'|Teleportation Assistant says, 'The teleport stone is currently aligned to {S1}\.\')$`
![image](https://github.com/user-attachments/assets/5c8c9b8e-6cd1-4a63-9639-94e903cc722a)

* After the above didnt countdown, I rebooted PC, and restarted EQLogParser

Then have had multiples of this one since
`^(A|An) {S1} was given to {S2}\.`
![image](https://github.com/user-attachments/assets/21d54334-7b68-4c14-9236-514be09f59d8)
![image](https://github.com/user-attachments/assets/d9a9367c-436f-4cef-aeb3-3c7b76053dfa)
This has sat at 10mins for over 30mins
Not sure which entry it was as I see a lot of diamonds when grinding
![image](https://github.com/user-attachments/assets/1133dbe4-2003-4ff2-8ab6-c0c9a94b171f)

**Comment by kauffman12** [comment]
And that loot trigger is exactly what you were using with the End Early that looks broken? It seems like you would need S2 and S1 instead of that S1 and S0. And it works most the time but once in a while one of the timers just gets stuck?

**Comment by LamahHerder** [comment]
Both the GPORT and the loot trigger would sometimes NOT count down
Sometimes they would countdown

Didnt notice that issue on the S0 in end early... but maybe not related since both triggers I noticed did not start countdown

**Comment by LamahHerder** [comment]
I fixed that loot trigger, but still periodically seeing countdown's that get locked and are not finishing
Both Fast Countdown and Normal Countdowns

This screenshot the EPIC countdowns are working properly, but the CANT HIT countdown is stuck, it eventually went away after 5ish mins
![image](https://github.com/user-attachments/assets/8677a9f4-86e6-49e4-ad3f-6756f6a424a5)
![image](https://github.com/user-attachments/assets/67c3f68c-ed04-40af-820d-54b17e04a0d0)

**Comment by kauffman12** [comment]
Does the overlay have a 5 minutes configured for the Idle Timeout? It's basically closing the overlay if nothing happens over that period. 

The bug does sound like the timerbar is created OK but for some reason the timer isn't started to update it. Something is just out of sync where it doesn't think there's any bars left but there is one. It makes sense that it only happens when there's 1 left. Maybe a new one is being added at the same time the last one is being deleted.

I'm re-working all the layout and resizing code right now to add more font sizes and it's going to take a few more days to finish. Maybe a week I don't know. There's a ton of places that had trouble resizing nicely. Then I'll see if I can fix this one.

**Comment by LamahHerder** [comment]
Something is definitely wonky, just noticed a bit different behavior
This overlay is stuck displaying a time
When a new separate trigger countdown starts it will update the time

![image](https://github.com/user-attachments/assets/c1614b9c-1472-4be9-a40e-586d091d4900)

I'll watch it some more see if I can find a trend
It is happening on multiple different 'countdown' timers some have 'end-early' patterns some dont
I just recently added a few 'fast countdowns' (after I had noticed this issue) and seems to be happening on them sometimes as well

I think I may have some weird trigger somewhere that is causing an issue for other triggers

**Comment by LamahHerder** [comment]
Perhaps they are getting overloaded? I'm not sure if this is considered a long eval time or not
For fast spammy triggers like this do you have any recommendations on configuration?

![image](https://github.com/user-attachments/assets/1cb99a32-158c-4c11-b8a3-da3858d207f6)

![image](https://github.com/user-attachments/assets/5d5d7881-7021-4c95-bca4-7b972555a42e)
![image](https://github.com/user-attachments/assets/7639845d-9bed-4c6f-a2e9-af650532b749)

**Comment by kauffman12** [comment]
You could see if a 0.5 second lockout time helps.

**Comment by LamahHerder** [comment]
Tried the lockout timer
Have also disabled those short triggers so doubt its related.

If I unselect all triggers then go and reapply them it stops doing it for a while but eventually comes back and effects all countdowns on all logs

**Comment by kauffman12** [comment]
Yeah it should be fixed next version. I'm just in the middle of some big changes. Had to re-write the adps timeline and make a ton of small changes to get the extra fonts working.

**Comment by kauffman12** [comment]
Hopefully this is fixed in the latest 2.2.40.
