### ISSUE TITLE
REQ: Allow opening .Log file as well as .txt and .gz

### ISSUE THREAD

**Issue by LamahHerder** [kauffman12/EQLogParser#197]
Maybe a bit petty, but I rename my .txt files to .log when I archive them for easy file association with https://github.com/variar/klogg instead of my normal text editor

![image](https://github.com/user-attachments/assets/64564ec6-f41c-46dc-9914-e2a32cea2fe0)

**Comment by kauffman12** [comment]
Yeah that's a small chance and shouldn't hurt anything.

**Comment by kauffman12** [comment]
This should be in 2.2.40.
