### ISSUE TITLE
REQ: Sort Trigger Log table by NAME and EVAL

### ISSUE THREAD

**Issue by LamahHerder** [kauffman12/EQLogParser#198]
Low priority, but would be nice to sort the trigger log table by **NAME** and **EVAL** time
![image](https://github.com/user-attachments/assets/e2b5cbe0-b5ee-469b-b838-4d9705bc8cc3)

**Comment by kauffman12** [comment]
In 2.2.40 but it does keep the time sorting when new data comes in.

**Comment by kauffman12** [comment]
Also you don't have to name the triggers with variables in them like that. The alternate timer name is the field where you can enter that info and leave the node in the tree with something more meaningful. It's not a big deal but what you're doing is kinda working by accident.
