### ISSUE TITLE
Simultaneous trigger firing reductions, or an option to suppress triggers immediately following a zone change event

### ISSUE THREAD

**Issue by BronsonMagnan** [kauffman12/EQLogParser#199]
Greetings, 
I have setup a trigger to monitor for character that stop auto-following
However, when we zone as a group, they all fire off at once and blast me in my headset sounding off nearly simultaneously
What would be the best way to configure this so that I can tell when autofollow breaks without the audio pain.
Maybe a feature to group simultaneous firing of the same trigger together as one audio trigger?
Or something to prevent triggers from firing off during the zoning process, i.e. if 'LOADING, PLEASE WAIT' is present, the '^You are no longer auto-following {S1}\\.$' which occurs after, could be suppressed?

![image](https://github.com/user-attachments/assets/99c77b38-d167-4a19-ad8a-87cde73191b9)

**Comment by kauffman12** [comment]
Maybe I could add a Previous Pattern or something to check against the previous line. If you're sure LOADING is always the previous line.

**Comment by kauffman12** [comment]
So, I added a way to check against the previous line. Try doing this in 2.2.43:

![image](https://github.com/user-attachments/assets/07ed4169-b94a-4590-a8a8-a80385b70238)
