### ISSUE TITLE
Centralized logging for boxing mode

### ISSUE THREAD

**Issue by BronsonMagnan** [kauffman12/EQLogParser#200]
What do you think about, in the context of boxing, being able to instead of firing a trigger off per character, the 'trigger' applied to the character could instead perform the {C} substitution, and write that log entry to a "centralized log". This lets us send interesting logs to the central file, which then could be treated as a character in the advanced log monitoring section, and we could perform matching off of that. I think this type of log entry redirection could open up some interesting scenarios.

**Comment by LamahHerder** [comment]
I'd imagine that'd create additional work
The methodology I use is to plan for a driver and boxes when considering triggers which has worked beautifully
The issue with this is that existing trigger packs from GINA and others do not take into account boxing, so need to recreate and optimize

I'm working thru creating a better trigger pack for boxers for my guild and a couple other guilds
If you're interested can check it out on discord @ https://discord.gg/HRDxaXUaMR
I've made setup instructions and you can also get the current version of triggers
![image](https://github.com/user-attachments/assets/57353189-6e28-4873-a99d-14a119bb70ef)

**Comment by kauffman12** [comment]
It's something to consider.
