### ISSUE TITLE
Heals included to AE healing

### ISSUE THREAD

**Issue by ZipeXoop** [kauffman12/EQLogParser#203]
Hello,
If I disable "include Ae Healing" on the Healing settings I still can see heals as Celestial Regeneration, Elixir of Realization (MGB'ed group HoT), Tunare's Grace, Syllabe, Reverie of Renewal, Recourse, Ancestral Aid, etc.

While this are group heals, not Ae Heals, some can be MGB'ed and are leaving the parse kinda meaningless.

Is there any plans to update this option so it only includes single target heals, excluding any form of group/MGB'able/AE heals?

By the end, I guess, classleaders mostly use the parse with the disabled option to check for people that focused on single target healing, but including this spells is leaving this option as missleading.

Thank you for your time.

**Comment by kauffman12** [comment]
I could probably add a separate option for group heals.

**Comment by kauffman12** [comment]
Actually I forgot how this works. It's already trying to handle what you're looking for. If you turn off AoE healing and it sees a group heal. It only counts the first 6 heals. Someone must have asked for that before.
