### ISSUE TITLE
Regarding {counter}  and sound/text to speak

### ISSUE THREAD

**Issue by esr-sudo** [kauffman12/EQLogParser#205]
Does the sound/text to speak have the ability to read the variable from {counter}?   For example, I am using `The mob healed {counter} `  in the text to display field and it works fine.  But it doesn't work in the text to speak setting, it just says "The mob healed counter"

**Comment by kauffman12** [comment]
Hmm maybe.

**Comment by kauffman12** [comment]
This wasn't too bad. It's in 2.2.46. Just the text to speak to field not any of the others.
