### ISSUE TITLE
Variable issue

### ISSUE THREAD

**Issue by KyleKolash** [kauffman12/EQLogParser#208]
when I use {c} speaks with the voice of nightmares or {s1} the trigger will not trigger nor will it pick up the variable. In my own personel he triggers work fine.  I also tried {s1}  as well and still got hre same result using the variable.

![image](https://github.com/user-attachments/assets/d23fd4b0-37c3-42ec-921f-25ee09652070)

**Comment by kauffman12** [comment]
{c} gets replaced by your character name so that will never work.

Is Regex enabled? As long as it is then you should be able to use your option example:
{s1} speaks with the voice of nightmares

But you may want to search your log file for voice of nightmares to make sure you're seeing it in there.

**Comment by KyleKolash** [comment]
I tried it with {S1} first and it didn't work. I am using regex. I can see
the text in my chat logs and it is just not pulling it in.  I had a friend
check what i was doing and he got the same results I did.

**Comment by KyleKolash** [comment]
[image: image.png]

[image: image.png]

**Comment by kauffman12** [comment]
Not sure what to tell ya. Are you on the latest version? Here's a video example of what I'm doing.

https://www.youtube.com/watch?v=xRZHyWzw9hM

**Comment by KyleKolash** [comment]
Do you think it is an Advanced vs Basic issue? I am currently running in
advanced.   If you want I can jump onto Discord or something so you can
look at it directly.

**Comment by KyleKolash** [comment]
hmm. I just logged out and came back in and it is working properly now. I
set it up they way you have it which is only slightly different than what
you had. I also set it to Basic instead of advanced.

**Comment by KyleKolash** [comment]
Also do you have SK triggers you can send over?

**Comment by kauffman12** [comment]
I do not have any SK triggers. This is just a heroic I have for testing.

Using Advanced it still seems to work. This is a pretty basic feature and a lot of people use so I'd think a lot of people would be complaining if it weren't. Maybe try creating triggers for another character from scratch and just follow the steps in the video and see if it works.

https://www.youtube.com/watch?v=hUwFzWZlw_4

**Comment by KyleKolash** [comment]
It's working for both basic and advanced now. I am not sure why. I changed
like 2 small things. Nothing major. Maybe it just needed a reload,

**Comment by KyleKolash** [comment]
Thanks for responding and helping.

**Comment by kauffman12** [comment]
ok sounds good
