### ISSUE TITLE
Feature request:  Add a statistics window for /randoms

### ISSUE THREAD

**Issue by esr-sudo** [kauffman12/EQLogParser#21]
One of the few remaining reasons why I have to open up that other parser, is when there are a large amount of people and we are doing a /random to determine who wins something.

The only way I have found  in EQLP to support the /random function is to manually search for "It could have been any number from 0 to 5000" but as far as I can tell, there is no way to sort the output so a person could quickly see the order of who won.

It's easy to skim through it for the highest person of course, but when there are 30+ people randoming for items and you need to quickly identify not just who the highest roller is, but the highest 20 people in the order of high to low, it can get a bit tedious.

If possible to be added, this feature would be greatly appreciated!

**Comment by kauffman12** [comment]
This one is on the list of things to do. I might be able to get to something soonish.

**Comment by kauffman12** [comment]
The search menu will have a window for showing randoms in version 2.0.0. Should have it ready fairly soon.
