### ISSUE TITLE
ISBoxer overlay issue

### ISSUE THREAD

**Issue by Screedcom** [kauffman12/EQLogParser#210]
I am an ISBoxer user and I use a window layout with swapping.  I am finding the overlay does not stay on top when I swap between windows.  I have the "overlap windows taskbar" option turned off.  When I first launch the overlay is on top, as soon as I swap to another character, the overlay disappears.  If I click back to eqlogparser and then back to isboxer character it reappears.  I am not sure if this is an issue that has been reported by others.  It seems specific to ISBoxer, not sure if there is a workaround.

**Comment by kauffman12** [comment]
Are there any always on top settings you can turn off? Their docs mention something in window region options.

Maybe some other ISBoxer user has some suggestions. Nobody has brought this up before to me and I don't use ISBoxer. There isn't a lot I can do.

**Comment by Screedcom** [comment]
SOLVED! Thank you for the direction!  Made a change in the main window region and adjusted the "Always on top mode" to off.  The default is "on if a game window is in the foreground".  I only made the change for the main window.

![image](https://github.com/user-attachments/assets/7e262107-0706-477c-a4d9-4a65f5c22cb7)

**Comment by alanwj** [comment]
I have exactly this issue, although the suggested solution does not solve it.

If EQLP was the last window active before switching to EQ, then the overlay will show.  But if I swap to any other EQ window the overlay gets lost until EQLP is focused again.

GINA also has this problem, except that it quickly recovers.  I believe GINA must be doing something to force its overlays back on top every ~1 sec.  Could something similar be added to EQLP?

**Comment by kauffman12** [comment]
See if this version is any better:
https://github.com/kauffman12/EQLogParser/raw/master/Release/test/EQLogParser-install-2.2.68-test.exe

**Comment by alanwj** [comment]
Yes.  That version does work much better!

In some quick tests, it behaves more or less the same as GINA.  The overlay still gets lost when switching to a different ISBoxer window, but it recovers shortly (sometimes almost instantly, sometimes after a second or two).

**Comment by kauffman12** [comment]
Okay well test that out for a bit and see if any problems come up with it.
