### ISSUE TITLE
Installer is too restrictive on dependency requirement

### ISSUE THREAD

**Issue by doubledgedboard** [kauffman12/EQLogParser#213]
I just installed .NET Runtime 8.0.10 and it's still telling me I need 8.0.7. That's not how patch versions work... if you have a library requirement, it should be allowing for versions newer in the same Major/Minor, at the very least.

It's also not great to be denied to install outright, let me try and I can report the error than outright stopping an installer.

The UI is also not great:

![image](https://github.com/user-attachments/assets/d9b76ee8-fa9c-4965-873d-191c83e5f17d)

**Comment by kauffman12** [comment]
Are you sure you installed the .NET 8.0 Desktop Runtime? I have 8.0.10 installed and none of the older versions and the installer didn't show the error dialog.

Also, the link to 8.0.7 is just the last version I had tested with and they don't have a direct link to the latest download. It's either link to a specific version that will eventually be out of date or link to the main page like this:
https://dotnet.microsoft.com/en-us/download/dotnet/8.0

But then I risk users downloading the wrong one. Also, what resolution are you running at? It looks like the dialog is pretty smooshed.

**Comment by doubledgedboard** [comment]
thanks for the fast response hah!

> Are you sure you installed the .NET 8.0 Desktop Runtime? I have 8.0.10 installed and none of the older versions and the installer didn't show the error dialog.

You're right I have just the runtime not the desktop runtime. Not used to this category differentiation, thanks for the heads up.

> But then I risk users downloading the wrong one. Also, what resolution are you running at? It looks like the dialog is pretty smooshed.

4K, but windows scaling 2x, so probably an issue with whatever UI and how it handles native windows scaling (windows usually enables at least some scaling on high res displays, by default).

**Comment by kauffman12** [comment]
> 4K, but windows scaling 2x, so probably an issue with whatever UI and how it handles native windows scaling (windows usually enables at least some scaling on high res displays, by default).

Okay. I'll try scaling to see what it looks like and I maybe I can make it a warning message that can be ignored.

**Comment by doubledgedboard** [comment]
The rest of the installation dialog (which I could see after installing the desktop runtime as per above), seemed fine, scaling wise. Something specific to that requirements dialog which didn't scale well.
