### ISSUE TITLE
disable modal dialog

### ISSUE THREAD

**Issue by doubledgedboard** [kauffman12/EQLogParser#216]
The newer versions seem to now display a modal dialog on startup.

Please advise how to disable, or consider this a feature request to do so.

I'll try to moderate my frustration over it, but having it cover my screen while loading EQ is a non-starter, and I am confused by the perceived value of having it added in the first place.

**Comment by kauffman12** [comment]
Are you talking about the splash screen?

**Comment by doubledgedboard** [comment]
yes

**Comment by kauffman12** [comment]
2.2.52 has an option for hiding the plash screen. Look under the options menu.

**Comment by doubledgedboard** [comment]
thank  you very much, tested and works as expected!
