### ISSUE TITLE
Unable to Access Downloads Folder. Can Not Download Update.

### ISSUE THREAD

**Issue by hotleadsingerguy** [kauffman12/EQLogParser#217]
Anytime I select Yes to allow EQLogParser to update I get this error. I can run it as Admin or my user, various compatibility modes, etc... and it doesn't change a thing.

Installed from github release (running 2.2.49, dotnet 8.0.7), in Windows 11 Pro. All prereqs installed and the app runs perfectly, otherwise. This has never worked on my computers (4 of them), and nothing on my network seems to be getting blocked.

**Comment by kauffman12** [comment]
So, try this if you can. Bring up a command prompt and type:
echo %userprofile%\Downloads

On my system it prints out this:
C:\Users\kauff\Downloads

What does your say? Is it a directory that exists on your system or did you maybe change your default Downloads folder?

**Comment by hotleadsingerguy** [comment]
It's the profile\Downloads, but that directory doesn't exist on my computer. I changed it after installing Windows using the "Change Location" functionality.

**Comment by kauffman12** [comment]
Ok. I think I can figure out how that is configured.

**Comment by kauffman12** [comment]
2.2.52 has the fix. Hopefully going forward auto update will work.
