### ISSUE TITLE
Trigger Lockout time not working consistently

### ISSUE THREAD

**Issue by Zayix-Aradune** [kauffman12/EQLogParser#219]
Howdy,

I'm trying to capture an emote, and I'm getting mixed info on people getting each of two possible emotes.  I'm making a trigger that would trigger on either.  In the sunny day case, both emotes hit at the same time.  I don't want them to trigger twice.  I put a Trigger Lockout Time of between 1 and 30 and it seems to do nothing.  It still triggers twice.

`^(The potion and magic from the sarnak's breath meld and infuse.|The unstable liquid melds with the magic of the Kar`Zok's breath. You feel the substance infuse your skin. It tingles.)`

Tester:
[Sun Oct 27 22:13:24 2024] The potion and magic from the sarnak's breath meld and infuse.
[Sun Oct 27 22:13:24 2024] The unstable liquid melds with the magic of the Kar`Zok's breath. You feel the substance infuse your skin. It tingles.

Attached the trigger as an example.

[ExampleTriggerLockoutIssue.tgf.gz](https://github.com/user-attachments/files/17904244/ExampleTriggerLockoutIssue.tgf.gz)

**Comment by Zayix-Aradune** [comment]
Oh, and just to confirm - this is on latest.  v2.2.53

**Comment by kauffman12** [comment]
Try 2.2.54

**Comment by Zayix-Aradune** [comment]
Looks fixed, thanks!
