### ISSUE TITLE
Version 2.2.55 not working (need to install dotnet 8.0.11)

### ISSUE THREAD

**Issue by Vorgash** [kauffman12/EQLogParser#220]
Just updated to version 2.2.55 and it will not run, no error message just does not run at all.
Tried fresh install also but still nothing.

**Comment by kauffman12** [comment]
Try installing the latest dotnet 8 and see if that helps.

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.11-windows-x64-installer

**Comment by AVanStelle** [comment]
> Try installing the latest dotnet 8 and see if that helps.
> 
> https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.11-windows-x64-installer

this fixed it for me

**Comment by Vorgash** [comment]
Fel-bucket , typ 0
Händelsenamn: APPCRASH
Svar: Inte tillgänglig
Kabinett-ID: 0

Problemsignatur:
P1: EQLogParser.exe
P2: 2.2.55.0
P3: 67110000
P4: KERNELBASE.dll
P5: 10.0.22621.4391
P6: 7433a115
P7: e0434352
P8: 000000000005fa4c
P9: 
P10: 

Will try the dotnet

**Comment by kauffman12** [comment]
I updated the latest installer to check for 8.0.11 or newer so it should give a warning next time if it's not there. Hopefully that's all it is.

**Comment by Vorgash** [comment]
That fixed it, fired right up.

**Comment by kauffman12** [comment]
great!
