### ISSUE TITLE
timers disappearing

### ISSUE THREAD

**Issue by Svann21** [kauffman12/EQLogParser#224]
If you have timers going and you make any change to what triggers are chosen then all the timers disappear.  Even if I click a trigger _on_ they all go away.

**Comment by Dgc2002** [comment]
This is very inconvenient behavior and it's one of the reasons I haven't fully migrated from GINA.

**Comment by kauffman12** [comment]
I'll mark this an improvement but it's being done on purpose right now.

**Comment by kauffman12** [comment]
So I am still in the middle of re-working Trigger related things but I did make an update for this feature in the latest.

Try 2.2.62 and see if it's working like you'd expect.
