### ISSUE TITLE
Countdown timers dissapearing if 'warning' used

### ISSUE THREAD

**Issue by brahmaff** [kauffman12/EQLogParser#225]
I've been trying to setup some countdown timers for various discipline usage and I've noticed that if I set a warning (10, 15, 30 second marks are the ones I've tried) the countdown timer just ends as soon as I get the warning.

I've not been able to find anything that would cause this though it's possible I've missed something. I've tried it on several different disc timers and if I remove the warning time/txt they work with no issues but if I add it in they give the warning at the set time and then just stop.

Am I missing something or is this a bug?

**Comment by kauffman12** [comment]
Looks like a bug from the cleanup I was doing. Here try the latest:

https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-install-2.2.59.exe

**Comment by brahmaff** [comment]
Thanks! looks like it is working now.
