### ISSUE TITLE
Different color for 'self' on DPS overlay

### ISSUE THREAD

**Issue by brahmaff** [kauffman12/EQLogParser#226]
This is purely a QoL suggestion, but it would be really nice if there was a way to set the line for yourself on the DPS overlay to be a different color than all the others. It's one of the things I miss the most about Gamparse. It makes it really easy to see where you are at a glance.

**Comment by kauffman12** [comment]
This is in 2.2.62 so try the latest. There's just a 2nd color picker in the Damage Meter setup for this other color.

**Comment by brahmaff** [comment]
Sweet! perfect! thank you so much!

**Comment by kauffman12** [comment]
no prob
