### ISSUE TITLE
Just updated from .61 to .62, now it says it can't run on my PC

### ISSUE THREAD

**Issue by esr-sudo** [kauffman12/EQLogParser#230]
When I try to run the exe for .62, it says it can't run on this PC.  Everything was fine with the last few updates, I've been installing them every time.

If I try and load EQLP normally, nothing happens.

Windows 10 Pro V22H2 AMD 7800X3D, 4090, 32gigs ram, blah blah blah.

**Comment by kauffman12** [comment]
And you have dotnet 8.0.11 Desktop installed? That's been required for about a month now.
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-8.0.11-windows-x64-installer

I never uploaded .61 so .59 was probably what you had unless you were behind a little bit and didn't notice? Like .54 probably worked fine without updating to 8.0.11. From .55 onward if you didn't have 8.0.11 it would do what you're seeing. You try to run it and it just does nothing.

If it's not the dotnet version maybe check Windows Event Viewer. There's usually an 'Error' message under Application logs when something like this happens.

**Comment by kauffman12** [comment]
Here's where you'd look to see what's installed. The 8.0.11 folder is the important one.

![image](https://github.com/user-attachments/assets/4475bf96-0940-4d71-90d6-f579176e36a1)

**Comment by esr-sudo** [comment]
I updated to that when it was required a few weeks back.  I also just checked, no issues with .net

Event viewer  says that EQLogParser-install-2.2.62.exe" cannot start or run due to incompatibity with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available.

**Comment by esr-sudo** [comment]
![image](https://github.com/user-attachments/assets/957f33ea-20ce-48be-a3e9-7825561cf116)

**Comment by kauffman12** [comment]
Can you open that file it's giving the error about? It says it's empty. It should look like this.

![image](https://github.com/user-attachments/assets/2e957f09-767f-4725-99bc-b30124f4c834)

**Comment by esr-sudo** [comment]
It's only 1kb, and well...

![image](https://github.com/user-attachments/assets/71dca437-801f-4527-90e9-c78dac20c8b1)

**Comment by kauffman12** [comment]
Could you try deleting all those files in C:\Program Files\EQLogParser and re-install? Then see what that file looks like.

Here's a link to 62.
https://github.com/kauffman12/EQLogParser/raw/refs/heads/master/Release/EQLogParser-install-2.2.62.exe

**Comment by esr-sudo** [comment]
All good!

**Comment by kauffman12** [comment]
That is the original .62 installer. So, you're saying it all starts OK now? Maybe the auto update install was messed up somehow?

**Comment by esr-sudo** [comment]
Yeah, everything works fine now. PS, I noticed there's a backup utility in the create backup and restore from backup option in the tools menu.  Does that back up everything including triggers, overlays, and preferences?    I've been exporting that stuff manually!

**Comment by kauffman12** [comment]
So, for a full backup you can use the option under the Tools menu. There's a Create Backup File and a Restore Backup. It does everything and you don't need to run anything from command line.

The BackupUtil.exe does basically the same thing but from the command line. Without the parser running you can run that and specify a location to create the backup file. Someone wanted a way to automate their backups. If you run it without arguments it should list what the options are. I doubt many people need to go that far.

**Comment by esr-sudo** [comment]
Awesome!

**Comment by kauffman12** [comment]
Sure no prob.

I also created 63 just in-case something is somehow corrupted in that last version. I just tried the auto-update and it worked for me. Hopefully it's works. I''m not sure what could have caused the corrupted file you were seeing.
