### ISSUE TITLE
Wizard Magic spells not showing in Spell Count or Spell Damage Statistics

### ISSUE THREAD

**Issue by limpinjezus** [kauffman12/EQLogParser#24]
Lightning Shock specifically does not show in Spell Count or Spell Damage Statistics. 

Log entries:
[Sun Dec 12 09:49:57 2021] You begin casting Lightning Shock.
[Sun Dec 12 09:50:00 2021] You hit a delirious miner for 570 points of magic damage by Lightning Shock.
[Sun Dec 12 09:50:02 2021] You begin casting Lightning Shock.
[Sun Dec 12 09:50:06 2021] You hit a delirious miner for 570 points of magic damage by Lightning Shock.
[Sun Dec 12 09:50:08 2021] You begin casting Lightning Shock.
[Sun Dec 12 09:50:11 2021] You hit a delirious miner for 570 points of magic damage by Lightning Shock.
[Sun Dec 12 09:51:18 2021] You begin casting Lightning Shock.
[Sun Dec 12 09:51:22 2021] A delirious miner resisted your Lightning Shock!

**Comment by kauffman12** [comment]
Looks like a bug where it's flagged as a proc. Check the show procs options for now to see it.

**Comment by kauffman12** [comment]
Try this in 1.8.52. It should be fixed.
