### ISSUE TITLE
Finishing Blow

### ISSUE THREAD

**Issue by mfrerking** [kauffman12/EQLogParser#25]
Could you please add an option for Finishing Blow like you have with Headshot and Assassinate? Currently Finishing Blow is counted in damage and it is throwing off averages and maximums. 

Thank you!

**Comment by kauffman12** [comment]
The Headshot and Assassinate columns just show how much damage total came from those actions. They still count toward the min/max hits. They could be moved out to their own rows in the table so they're counted completely separately if that makes sense?

**Comment by kauffman12** [comment]
Ok now if you really want to hide Finishing Blow. Try 1.8.60 and under Options -> Damage you can turn Finishing Blow off completely.
