### ISSUE TITLE
Show AE heals:Cleric, shaman and druid spells

### ISSUE THREAD

**Issue by ZipeXoop** [kauffman12/EQLogParser#26]
Hello,
I love this parser and one of the reasons we started using it is to filter AE heals. Now a days we are using it for all its other features too! 

Show AE heals filter is quite outdated now since it isn't filtering out a lot of AE heals. From my point of view, if we filter AE heals means we want to focus on direct target heals or group heals so we can better observe the data involving heals that are not mindlessly thrown into all the raid. With the current Parse filters, Show AE Heals turned off isn't filtering out data from Healing wards and HoTs (that most of the time are MGB'ed). This heals inflate the healing number by a lot, leaving the healing parse on a not reliable state.

Terror of Luclin clerics spells that are AE heals and should be filtered out:

Celestial Regeneration XXXIX: And all older versions->This is usually MGB'ed.
Elixir of Benevolence (TOL), Elixir of Transcendence (TOV) -> This is usually MGB'ed.
Issuance of Conviction Effect (TOL), Issuance of Serenity Effect (TOV)->Spell cast healing ward.
Exquisite Restoration XVII: and all older versions-> AA cast healing ward.

Shaman spells:
Ancestral Aid XXXVII: and all older versions-> This is usually MGB'ed.
Ancient Restoration XX: and all older versions -> AA cast healing ward.

Druid spells:
Spirit of the Wood XL: And all older versions-> This is usually MGB'ed.
Nature's Restoration XXXII: and all older versions -> AA cast healing ward.

Did I miss anything? I understand that deciding to filter out AA and Spell group hots because they are usually MGB'ed may be a very subjective decision, but in my humble opinion it must be done if we want to properly see data of healing done without AE heals under raid scenarios. I also understand that some may argue that if we are leaving Group hots out we should also leave group heals out. But I think that group heals aren't an issue since they usually used (specially by shaman and druid) to emergency heal group members, so they are casted on demand and their data is actually useful. And most importantly, group direct heals aren't MGB'ed, Group hots are.

Thanks for your time and that awesome parser.

**Comment by kauffman12** [comment]
1.8.55 now counts Issuance and Wards as AEs. To handle normal group spells being used with MGB I might be able to count the unique number of players healed by a single spell cast and if the number is > 6 then count it as an AE. But that's something for a future update.

**Comment by ZipeXoop** [comment]
That's awesome. Thanks.
Can't wait for the other upgrade, as I said on my original post; having Celestial Regeneration MGB's not count as AE's makes the filter unreliable.

**Comment by ZipeXoop** [comment]
Hey,
It's fantastic to see that data filtered! I see some HoTs that are not MGB'd in, which is awesome because now we can finally see the effectiveness of casting a HoT without MGB... Thanks!

I checked Shamans and druids too and looks like you still haven't implemented their AA HoT, right?

**Comment by kauffman12** [comment]
Oh yeah those two aren't working yet. Forgot to make an update for them. Shouldn't be too difficult.

**Comment by kauffman12** [comment]
Try 1.8.58.

**Comment by kauffman12** [comment]
I made one more tweak to improve how it counts so give 1.8.59 a shot. Hopefully it's fine but if there's another spells that it's not counting you can re-open.
