### ISSUE TITLE
Request: Regex based TTS patterns

### ISSUE THREAD

**Issue by fryguy503** [kauffman12/EQLogParser#28]
Request: Regex based TTS patterns

Subfolder: Patterns
Contents: formatted text files, separated triggers, all files read in subfolder.
e.g. ~/patterns/default.txt, ~/patterns/oowRaids.txt, ~/patterns/foobar.txt

Contents:

the format for a pattern is:
any line that begins with two slashes (//) is a comment and ignored. empty lines are also ignored.
1st character is the separator between the following pattern and the result.
2nd character to the separator is a regular expression pattern. 
after the separator is the result pattern; commands, backreferences and substitution are allowed.
further separators and results can follow.
double slash (//) comments can be used at the end and are ignored.

example:
```
// ~\[.+\]\s(.+)\syawns\.~$1 has been slowed.
// the very first character is a tilde (~), it will be used to separate the line between pattern and result
// \[.+\]\s(.+)\syawns\.  <--- this is the regex pattern
// the second tilde (~) is the separator
// $1 has been slowed.  <--- this is the result; substitution would happen automatically and $1 is replace by the name of what was slowed

~(\w+) invites you to join a group~grupe invite from $1
~has been awakened by (\w+)~mezz break by $1
~^\[[a-z]{3} [a-z]{3} [0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} [0-9]{4}\] You have slain (?<defender>.+)!$~/dump ${defender}
```

Additional Features:
Create an allow list of in game player names that can use chat based functions to add patterns to all players that have approved them. Useful for raid leaders adding new patterns to raid attendees.

```
~!init~/patinit            // (re-)initialize patterns (/patinit)
~!add\s+(.*)'~/patadd $1   // add a pattern (/patadd)
~!save~/patsave            // save added patterns (/patsave)
```

Credit: Much of this is based on a very old parser called: Tango that was fantastic but very undercooked and abandoned 10+ years ago.

**Comment by kauffman12** [comment]
I've wanted to add something similar at some point and this looks like a simple way to get started. But does none of the eqemu players use GINA? That's the main reason I haven't bothered yet.

**Comment by limpinjezus** [comment]
> I've wanted to add something similar at some point and this looks like a simple way to get started. But does none of the eqemu players use GINA? That's the main reason I haven't bothered yet.

I use GINA heavily

**Comment by fryguy503** [comment]
I use it a ton in Tango (Similar features to GINA plus the raid leader send to others functions)

**Comment by kauffman12** [comment]
So would you just prefer to use one application instead of two? Or is there some features you want that neither Tango or GINA do and it's no longer possible to get those updated? Just curious.

**Comment by fryguy503** [comment]
I personally prefer one program which just a toggle to disable.

I think GINA just does TTS. May want to allow a way to assign a wav file as well (similar to in-game audio triggers) in addition to TTS.

**Comment by kauffman12** [comment]
ok thanks

**Comment by kauffman12** [comment]
Are there a lot of people that use triggers in this Tango format you described in the first post? I'm adding TTS and can import GINA triggers. It probably wouldn't be bad to add an import of those pattern files but if only a couple people use it may not be worth it.
