### ISSUE TITLE
EQemu Beastlord pets not showing up in parse

### ISSUE THREAD

**Issue by Skretch0** [kauffman12/EQLogParser#29]
Recently switched to eqlogparser with some of my guildies.  It however will not show my beastlord's warder in the parse.  Any help would be appreciated I really like the parser.
![image](https://user-images.githubusercontent.com/98045733/150179733-064919b4-9129-4bcb-a9b9-9f5f8a831d1b.png)
![image](https://user-images.githubusercontent.com/98045733/150180382-01d89154-1ae4-4133-944a-bb177bed57a4.png)

**Comment by kauffman12** [comment]
I think Warder is lowercase on live servers. I'll check if that's all it is. Should be a simple enough fix if so.

**Comment by Skretch0** [comment]
Awesome thank you!!

**Comment by kauffman12** [comment]
Ok I'm pretty sure that's all that was wrong. Try 1.8.59 and if it's still broken you can re-open this one.
