### ISSUE TITLE
Reset Chart layout

### ISSUE THREAD

**Issue by zoopadoopa** [kauffman12/EQLogParser#3]
After zooming or sliding the charts, there is no way to reset the layout to default zoom level without changing your current view (i.e. doggling from DPS to Damage, and then back to DPS). 
Potentially added a Reset View button on the page would assist

**Comment by kauffman12** [comment]
Try double clicking on the chart to reset the view. I may add a button or maybe right-click when I get to giving the charts one.

**Comment by kauffman12** [comment]
1.7.10 has a right-click Recenter option to do this in addition to double-click.
