### ISSUE TITLE
Setting pets fails for some users

### ISSUE THREAD

**Issue by fryguy503** [kauffman12/EQLogParser#30]
I have noticed when setting pet owners via the Pet owners side panel, you select the owner and it refreshes but does not retail the selection.

![image](https://user-images.githubusercontent.com/5864295/150562161-b1210e7d-c12c-47fb-9dc3-68d9213e63f2.png)

Also should having players to /pet leader so they output their leaders name automatically map them? That does not seem to be functioning.

**Comment by kauffman12** [comment]
What version? Also, it does try to read /pet leader but it may get confused sometimes. Like if you're using an enchanter pet with random names it's not going to save it. You'd want to get that potion to give the pet a good name.

**Comment by kauffman12** [comment]
What does the pet leader message look like on eqemu? On live it's this:
[Sat Jan 08 14:47:18 2022] Darkside says, 'My leader is Reddhuman.'

Any differenes with quotes or commas or anything?

**Comment by fryguy503** [comment]
Sorry, I was on v 1.8.59

	Line 30856: [Fri Jan 14 21:42:06 2022] Konarab says 'My leader is Alacazama.'

**Comment by kauffman12** [comment]
Looks like that message is slightly different. Not sure why manually adding isn't working but fixing this might be a good workaround for now.

**Comment by kauffman12** [comment]
I updated the pet leader message in 1.8.61 and added a little bit of logging. See if the error log shows anything when you see problems manually adding a pet.

**Comment by fryguy503** [comment]
Thank you. Our next get together is around 5:30pm eastern and I can check then.

**Comment by fryguy503** [comment]
@kauffman12 so the /pet leader is working great now. However the manually assigning pets via the "Pet Owners" tab on the right is not working. When you select "Unknown Pet Owner" and select the appropriate owner, it refreshed the pet owners and damage summary window but reverts to "Unknown Pet owner"

<img width="255" alt="image" src="https://user-images.githubusercontent.com/5864295/150724351-fd33429b-2d1a-48a0-8b34-a0a1bd618833.png">

**Comment by kauffman12** [comment]
If you got to Tools -> View Error Log does anything interesting show up?

**Comment by fryguy503** [comment]
2022-01-24 21:23:18,757 [1] ERROR EQLogParser.MainWindow - Error adding pet=Unknown Pet Owner to owner=Unknown Pet Owner. The player name and pet name can not be the same.

**Comment by kauffman12** [comment]
ok try 1.8.62. Keep in mind that it should let you assign but it isn't going to save the setting since those are randomly generated pet names.
