### ISSUE TITLE
AE effects and duplicate entries in the fight list

### ISSUE THREAD

**Issue by esr-sudo** [kauffman12/EQLogParser#31]
For some  time now, when I pull up the fight list, I have seen several entries in the fight list that should not be present.  Many of them are dots or effects that players or npc's cast, and sometimes they are duplicate blank entries for something that is correctly placed in the fight list.

Some examples from raiding Planes of Power would be:
rabies
Spreading Crud
Poxed Web
Mists of Enlightenment
Cataclsym of Ro
Adler Fuirstel
Poisoned Flames
Plagued Earth
Epoch Conviction
Glacier Breath
Seething Hatred
Aura of Fear
Call of the Faceless
Black Plague
Several duplicate entries for targets that are killed, should be (and are) in the fight list under a prior entry.

Here is an image of what I mean:

![image](https://user-images.githubusercontent.com/60377940/150613188-382592bd-390f-4533-8970-359d5afd455e.png)

Since there is no value when we click on that entry for them in the fight list, I'm wondering if these sorts of entries could be cleaned up if there was a filter that we could set in the fight list that would not add an entry if that "fight" didn't have a certain threshold of damage applied to it.   "That other parser" has a setting in that regard, and maybe that's a way to fix it here.

If you need, I would be happy to submit a log file as an example, but I would prefer to only do so privately.

**Comment by esr-sudo** [comment]
Nevermind!

I deselected the Tanking button, when I noticed the tooltip for it is "include fights with only tanking data".

Presto!

**Comment by kauffman12** [comment]
No prob. Having those is helpful sometimes when you want to see who is getting hit by an aura or something they probably should be avoiding.
