### ISSUE TITLE
[Bug] Emulator: Looted Items window not populating

### ISSUE THREAD

**Issue by fryguy503** [kauffman12/EQLogParser#32]
Looted items window is not populating, I assume this is due to wording on loot vs current live.

Example:
`[Fri Jan 14 21:05:46 2022] --Triplex has looted a Muramite Sleeve Armor.--`

**Comment by kauffman12** [comment]
Yeah there's always a from part of the statement to say what it was looted from.

**Comment by kauffman12** [comment]
Try 1.8.61.
