### ISSUE TITLE
Beastlord Clobber rk 1 not counted

### ISSUE THREAD

**Issue by JacLucFV** [kauffman12/EQLogParser#33]
I've noticed that the Rk. 1 Clobber ability for the Beastlord does not show in the spell count by the parser.  I upgraded to rk.2 and it was counted fine.   Also, Bite of the Asp XXXI (my current rank) does not show up in the spell couny.

**Comment by kauffman12** [comment]
Bite of the Asp is a spell proc. It's not showing up if you check the Spell Procs checkbox at the top of the spell counts tab?

**Comment by kauffman12** [comment]
1.8.63 has a fix for Clobber.

**Comment by JacLucFV** [comment]
I just checked, and it does show up under spell procs.  I was just confused because the Tiger Claw proc shows without spell proc check enabled, so i thought Bite would be the same.
Thanks you for the response.


Sent from Yahoo Mail for iPhone


On Tuesday, January 25, 2022, 4:22 AM, kauffman12 ***@***.***> wrote:




Bite of the Asp is a spell proc. It's not showing up if you check the Spell Procs checkbox at the top of the spell counts tab?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JacLucFV** [comment]
Thank you.  I have 1.8.61, will look for 63.


Sent from Yahoo Mail for iPhone


On Tuesday, January 25, 2022, 9:41 AM, kauffman12 ***@***.***> wrote:




1.8.63 has a fix for Clobber.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kauffman12** [comment]
Tiger Claw might be the bug then. I'll look at the beast spells on our raids.
