### ISSUE TITLE
EQEmu - Class not populating in Damage Summary

### ISSUE THREAD

**Issue by fryguy503** [kauffman12/EQLogParser#34]
Not sure if a bug, but should doing `/who` in zone add all visible classes to the verified player list for the damage summary?

e.g.:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/5864295/151288296-89de9057-25a5-4aea-8a3e-1800d43c8c19.png">

Sample `/who` output

> [Wed Jan 26 22:41:48 2022] Players in EverQuest:
> [Wed Jan 26 22:41:48 2022] ---------------------------
> [Wed Jan 26 22:41:48 2022] [65 Maestro (Bard)] Metal (Gnome) <Unity>   
> [Wed Jan 26 22:41:48 2022] [65 Archon (Cleric)] Worstheals (Halfling) <Unity>   
> [Wed Jan 26 22:41:48 2022] [65 Overlord (Warrior)] Strikingone (Ogre) <Unity>   
> [Wed Jan 26 22:41:48 2022] [65 Maestro (Bard)] Jaun (Gnome) <Unity>   
> [Wed Jan 26 22:41:48 2022] [65 Lord Protector (Paladin)] Tatsumaki (Dwarf) <Unity>   
> [Wed Jan 26 22:41:48 2022] [65 Storm Warden (Druid)] Alane (Wood Elf) <Unity>   
> [Wed Jan 26 22:41:48 2022] [65 Forest Stalker (Ranger)] Snuffleupagus (Wolf) <Unity>   
> [Wed Jan 26 22:41:48 2022] [65 Fury (Berserker)] Uwuu (Barbarian) <Unity>   
> [Wed Jan 26 22:41:48 2022] [65 Transcendent (Monk)] Yonkec (Skeleton) <Unity>   
> [Wed Jan 26 22:41:48 2022] [65 Overlord (Warrior)] Jenfo (Halfling) <Unity>   
> [Wed Jan 26 22:41:48 2022] [65 Forest Stalker (Ranger)] Bombadil (Halfling) <Unity>

**Comment by kauffman12** [comment]
I can add that. On live there's plenty of info in spells/abilities that looking for /who isn't needed.

**Comment by kauffman12** [comment]
Ok try 1.8.65. It should save the class as well so hopefully you don't have to do /who all the time. I'm only going to save classes when doing things like /who that can't be wrong.
