### ISSUE TITLE
Request: Thoughts on Adding GINA like features?

### ISSUE THREAD

**Issue by hammackj** [kauffman12/EQLogParser#35]
Thoughts on Adding GINA like features? Seems like a great framework you have here, could really become a one stop shop with that.

**Comment by kauffman12** [comment]
Possibly. I may do something simple for starts like requested here:
https://github.com/kauffman12/EQLogParser/issues/28

Simple text to speech from a pattern should be easy enough. After that I could look at adding more GINA like features but don't expect that too soon.

**Comment by kauffman12** [comment]
2.0.41 has a start on audio triggers you can try out if you want. There's no overlays yet for the timers but you can at least setup triggers and import from GINA. I'll probably be adding more to it slowly over the next few months.
