### ISSUE TITLE
Mercenary damage not reported

### ISSUE THREAD

**Issue by lmarkus001** [kauffman12/EQLogParser#36]
I fight with 3 toons and 3 mercs, a tank merc and a dps merc.  Their damage is not being reported.

**Comment by kauffman12** [comment]
Is it caster or rogue DPS and what are their names? I can check if they're NPC names or something that could throw it off.

**Comment by lmarkus001** [comment]
My group makeup is Rrowzing(bard), Snipit(druid), Bufotenine(cleric) and 3 mercs.
a lizardman brawler (melee dps)
Fathein (cleric)
And a tank named one of these two:
a clockwork defender DCCLXXXVI
an Alaran spirit defender

Sometimes the parser catches some of them, but many times their contributions do not show at all.
Here is a sample parse with a single fight with them in it.  For this fight the mercs did show, but this seems a anomaly from my recent experiences.

https://app.box.com/s/dkwtzwjx49meymlsirl3cs0glpvbplay

**Comment by kauffman12** [comment]
Got this half working again but it'll take a bit more work. Maybe sometime next week I'll have a fix to try.

**Comment by kauffman12** [comment]
Try 1.8.69. It's not counting received spells for the spell counts and adps charts but I think damage should show up fine. Just make sure you have messages in your log for the mercs joining your group. I'll probably a right-click Set As Merc option at some point and try to get all the spell count stuff working.

**Comment by kauffman12** [comment]
I may add more for this in the future but damage should be showing up better now.
