### ISSUE TITLE
Request: Damage Log Column

### ISSUE THREAD

**Issue by dmb041** [kauffman12/EQLogParser#38]
When viewing damage log, please add column with class. I dump out multiple toons damage logs to excel and create pivot tables from there. Would be helpful to have class as an additional pivot option without having to add it manually.

**Comment by kauffman12** [comment]
Try 1.9.3. Unless there's major issues I'm going to stick with this new version that needs .NET 6.0. If you haven't tried it yet you'll need to download that manually for now.

**Comment by dmb041** [comment]
Works perfect. Thank you

**Comment by kauffman12** [comment]
no prob
