### ISSUE TITLE
Not reading log for certain creatures

### ISSUE THREAD

**Issue by Phynster** [kauffman12/EQLogParser#39]
not sure if this is a known issue or not, but I've been fighting in ToFS on the second floor against a ghostly scholar, a ghostly student, and an angrier librarian and for some reason the parser just won't read the fights.

**Comment by kauffman12** [comment]
Is anyone charming them? There's an Options -> Ignore Charm Pets you could turn on to make sure that's not it. Could make sure they're not showing up in the verified pets list too. They can be removed from there if you see them.

**Comment by kauffman12** [comment]
Other NPCs show up ok? I have a recent install and they show up so I think it must be configuration related.


![scholars](https://user-images.githubusercontent.com/771335/175357493-415636a8-11ea-459e-8706-e9e5f646202b.jpg)

**Comment by Phynster** [comment]
in every other zone, and on every other mob ya it works fine. Its just those 3 types of mobs on that one floor of ToFS.
for some reason occasionally it will pick up one of my mercs as the target being hit by the ghosts, but I don't use mercs often so instead it will just go inactive or until I pull one of the ph mobs

![parse](https://user-images.githubusercontent.com/39542850/175392521-a202c28f-4f90-418a-920d-02d516c9f067.png)
![parse 2](https://user-images.githubusercontent.com/39542850/175392531-2d80516f-a271-47d8-8640-51f937217e31.png)
![parse 3](https://user-images.githubusercontent.com/39542850/175392543-f6688b09-91fc-40ed-8f7f-341300050bff.png)
.

**Comment by kauffman12** [comment]
What I would do is download 1.8.78. Then open the Verified Players and Verified Pets windows and double check that none of those NPCs got stuck in there somehow. You can hit the X to remove them.

![pets](https://user-images.githubusercontent.com/771335/175487647-6df32168-fbcf-48ef-bc4a-7bd79cf48a2a.jpg)

**Comment by Phynster** [comment]
fuck that was it.... they made it onto the verified players list somehow... one place I didn't check because I didn't think it would have been an issue.

**Comment by kauffman12** [comment]
Ok yeah there might have been some bugs with trying to handle mercs with NPC looking names. That code was changed a decent amount in recent versions. Hopefully it doesn't happen anymore with the latest.
