### ISSUE TITLE
Issue: Overlay not staying on top

### ISSUE THREAD

**Issue by darkdelusions** [kauffman12/EQLogParser#40]
When using EQLogParser I am experiencing issues with the overlay staying on top, I am playing in windowed mode and don't seem to be having an issue with GINA Timers. If the EQ Window is not the active window the overlay will show. 

Version 1.9.11

**Comment by kauffman12** [comment]
The two main reasons for that are running multiple parsers and having the Overlap Windows Taskbar setting enabled. Try turning off that setting if you see it checked? It's on the Display tab under the Video Modes button. If it's neither of those then I'm not too sure what else to try.


![overlap](https://user-images.githubusercontent.com/771335/175972023-789e01c6-44f2-4f36-b23d-bf084874b4eb.jpg)

**Comment by darkdelusions** [comment]
Turning off Overlap Windows Taskbar resolved the issue
