### ISSUE TITLE
Some items not hitting parse

### ISSUE THREAD

**Issue by Kashmirre** [kauffman12/EQLogParser#41]
Having this weird issue where the logs are catching healing, but not whos doing the casting
![image](https://user-images.githubusercontent.com/88602424/176582069-9de4493d-b3d3-4ca9-b2aa-4a6924d6a6a0.png)
![image](https://user-images.githubusercontent.com/88602424/176582153-4da9f859-f8d8-4e2c-8bf6-ffe93be3b8c0.png)

**Comment by kauffman12** [comment]
Make sure you have the latest version installed, the PC Spells filter turned on, and you're standing relatively close to the players casting the spells. There isn't a lot that I can think of that would cause this.

**Comment by Kashmirre** [comment]
we stand right under sontalaks belly. I have spell filters going to a different tab, but they are on. It had worked fine earlier in the night.

**Comment by Kashmirre** [comment]
This was the raid we did just before - 
![image](https://user-images.githubusercontent.com/88602424/176584990-a45e3f12-c30c-41d3-b8a7-6002af318585.png)
![image](https://user-images.githubusercontent.com/88602424/176585093-c0d867db-d15f-4818-89e9-1ac56c83c287.png)

So I'm not sure what's going on. If I were to open this in Gamparse, it catches everything. I just have to go digging around for it. It nowhere near as clean ad yours.

**Comment by kauffman12** [comment]
You could try opening the spell counts from the Damage Summary and opening them from the Healing Summary to see if they're different. They kinda go by different blocks of time.

**Comment by kauffman12** [comment]
And I suppose try going back to 1.8.78 if nothing works. 1.9 has a lot of changes and maybe something got messed up. Although, I'm seeing the right counts when I try it. 

Besides that the only other thing I an think of double checking is loot at the Verified Players list and make sure the player is in there. I guess if it thought a NPC was casting the spells it might not show up.

**Comment by Kashmirre** [comment]
There was something with one of the versions in the 1.8 series that got me to upgrade, but I can't remember what it was now. I'll revert back to one of the older versions. But probably something that should be left open. As for Verified players, I have over 1300 verified players on that list, and all of the PCs are there.

**Comment by kauffman12** [comment]
On the odd chance it's configuration related you can delete the directory related to the server your character is on. Like this one for me:
C:\Users\john\AppData\Roaming\EQLogParser\config\xegony

Or just move it temporary. Try the parser without it and if doesn't help you could put it back. And if 1.8.78 doesn't work I can make a debug build to print some stuff out to see what's going on.

**Comment by Kashmirre** [comment]
Lemme give it a go, I'll report back in a bit

**Comment by Kashmirre** [comment]
Same result after clearing the config\server I'll roll back for now and see where it stops failing at. Happy to test any changes/debug you put in place.

**Comment by Kashmirre** [comment]
I've gone gone back to version 1.8.69, and still have the issue. I wouldn't mind sharing my parse with you via a onedrive or google drive share if you need/want it for troubleshooting.

**Comment by kauffman12** [comment]
Interesting. Yeah if don't mind sharing the parse somewhere I could take a look. Can link it over on Discord if you use that:

kizant#6840

**Comment by Kashmirre** [comment]
Sure, I'll get something setup for you when I get back to the PC

**Comment by Kashmirre** [comment]
After some troubleshooting and talking with Kizant on discord, I think we have it figured out. Going to close this issue.
