### ISSUE TITLE
Feature Request: Range filter on fight timer

### ISSUE THREAD

**Issue by AndrewDHokie** [kauffman12/EQLogParser#42]
For the timer in the summary bar:
![image](https://user-images.githubusercontent.com/1014553/176912973-53b2bebb-9b44-40f3-b6e8-06bf3d3153fb.png)

Would be cool if you could see a range of the fight.

So possibly add a second box for beginning and ending time.

Potential use case - If you wanted to just parse the end of close the gate 50->0 or the occasional events where you burn like 80-40 then have to stop for some reason.

Thanks,

**Comment by kauffman12** [comment]
Sure that's a good idea.

**Comment by kauffman12** [comment]
This will be in version 2.0.0. Hope to have it in a few days.
