### ISSUE TITLE
Export to html, csv, text

### ISSUE THREAD

**Issue by Kashmirre** [kauffman12/EQLogParser#43]
Export to html or csv for the data that can be drilled down. Things like the spell casting #, timelines, damage breakdown. 

For casters like wizards/mages, maybe a special type of export that that they could submit to your dps site that become an auto fill in.

**Comment by kauffman12** [comment]
Everything now has a copy as CSV option. Plus anything in a table can be copied directly with control-c/control-v.

In the future I may get back to the File -> Export as HTML and have it generate more spell casts and breakdowns but I don't see me getting to that anytime soon.
