### ISSUE TITLE
Taunt Count in Tank/or other breakdowns

### ISSUE THREAD

**Issue by Kashmirre** [kauffman12/EQLogParser#44]
Unless I'm missing it somewhere, I can't find how to get the taunt ability to parse. 

You have failed to capture npc's attention. - Taunt Failure
You capture npc's attention! - Taunt Success

A(n) NPC is focused on attacking tank due to an improved taunt. - Improves Taunt Success

**Comment by kauffman12** [comment]
Yeah that's not parsed at the moment.

**Comment by kauffman12** [comment]
So, I can parse regular taunt attempts and failures for maybe the spell counts table. But where does improved taunt fit in? It  already shows up in spell counts as the spell that caused it. Like Unrelenting Affirmation for paladins.

**Comment by Kashmirre** [comment]
Improved taunt is a passive aa, that I think just improves the taunt ability for less failure/increased hate. But I also don't think it has a failure message, or at least I did not see one.

Regards,

Jason Weichinger
P: (708)846-2578
E: ***@***.***

Sent from my mobile device. Please excuse any spelling or grammar errors.
________________________________

**Comment by kauffman12** [comment]
Just FYI I have looked into it a bit. The improved taunt messages do come from AAs or combat abilities that give 100% at taunting a single target. Bard has Dissonant Chord that gives a the same message as the one paladins use. It's not from a passive ability. 

I'm thinking I could add a taunt stats table like the one for spell damage. It doesn't really fit well with spell counts or damage breakdowns.

**Comment by kauffman12** [comment]
There will be a new UI under View -> Statistics -> Taunt Usage start in version 2.0.
