### ISSUE TITLE
Custom Install Directory

### ISSUE THREAD

**Issue by Kashmirre** [kauffman12/EQLogParser#45]
I've replicated this a few different times with the current installer (1.9) on different PCs. I want to install to G:\Program Files\EQLogparser
The installer even with the custom directory will install to C:\Program Files\EQLogParser\

**Comment by Kashmirre** [comment]
If there is an install log somewhere, let me know and I can post it.

**Comment by kauffman12** [comment]
I've been testing this and it seems to work fine for me on Windows 10.  Are you using Windows 11 maybe?

**Comment by Kashmirre** [comment]
Nope,. Win 10 Pro. I'm out on vacation til the 14th. I can get you more info after I'm back.


________________________________

**Comment by kauffman12** [comment]
OK thanks. I guess the only thing to do when you're back is run from the command line to create a log file. Plus I guess uninstall first so it doesn't try an upgrade or anything weird.

Example:  c:\>EQLogParser-2.0.0.msi /log output.txt

**Comment by Kashmirre** [comment]
Will do
________________________________

**Comment by kauffman12** [comment]
Ok thanks. I'll see if I can add a note about that. That selection is kind of a built in thing for the installer that I can't change much.
