### ISSUE TITLE
Attempted Hits?

### ISSUE THREAD

**Issue by The-Desthin** [kauffman12/EQLogParser#46]
Would it be possible to get a column for #Attempted hits (and possibly "Undefended" hits?) specifically in the Tanking Breakdown tab but could probably be useful in the Damage breakdown too.

**Comment by kauffman12** [comment]
How are you counting Attempted hits? Is that just everything like if I add Hits + Absorbs + Blocked + Dodged + Invuln + Missed + Parried together?

What is Undefended exactly? Is that like Hits minus Strikethrough or something like that? I'm just guessing.

**Comment by The-Desthin** [comment]
Exactly right, all incoming attempts(attempted hits), and hits minus strikethrough(undefended hits), guess I could have made that more clear the first time.

**Comment by kauffman12** [comment]
Ok. I only play DPS so it helps to be specific for tank things. I'll add
them for version 2.0 I plan on having in a few days.
