### ISSUE TITLE
V2.0.0 Spell Count crashing

### ISSUE THREAD

**Issue by The-Desthin** [kauffman12/EQLogParser#49]
> 2022-08-13 20:56:25,260 [1] ERROR EQLogParser.SpellCountTable - System.Collections.Generic.KeyNotFoundException: The given key 'Desthin' was not present in the dictionary.
>    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    at EQLogParser.SpellCountTable.<>c__DisplayClass14_0.<Display>b__0(String player)
>    at System.Collections.Generic.List`1.ForEach(Action`1 action)
>    at EQLogParser.SpellCountTable.Display(Boolean clear)

I'm getting this almost every time I try to check Spell Counts, from the Damage Breakdown tab.
Example above is from "Desthin" log trying to check "Desthin", but I also can get it when checking other characters from "Desthin" log file.
Happens regardless of if I do "Selected" or by class

**Comment by kauffman12** [comment]
Thanks. I just managed to reproduce this one. That player either didn't cast a spell or hadn't received a spell and it's failing to check for that possibility. I'll have a fix in an hour or so. Going to see anyone finds anything else.

**Comment by The-Desthin** [comment]
I believe in the ones I was testing "Infusion of Rage" was cast multiple times, and it does show up in my cast counts before changing any of the settings for procs etc. In the current parse I'm working with, my bard has cast/recieved things but it will crash whereas I will not. Spell count timeline is showing both has having things cast

**Comment by kauffman12** [comment]
Well either way try 2.0.1 and see if it helps. I did get the exact same error you posted so I think it should fix the problem.

**Comment by The-Desthin** [comment]
Seems to be working now. Thanks much!

**Comment by kauffman12** [comment]
No prob!
