### ISSUE TITLE
Option to change parse separator

### ISSUE THREAD

**Issue by SeanLatimer** [kauffman12/EQLogParser#5]
Would it be possible to have an option to change the separator used in the Preview Parse?

Example
```
Lord Nagafen in 357s | 100.12K Damage @280 | Kirith = 10.94K@38 in 282s | Fackin = 9.22K@31 in 290s | Socal = 8.99K@27 in 329s | Ryac = 6.31K@20 in 315s | Tobar +Pets = 6.18K@17 in 356s
```

Possibly a dropdown or textbox here?
![Preview Parse Area](https://user-images.githubusercontent.com/11656396/90344216-0e728300-e007-11ea-86c0-8153722576fa.png)

Appreciate the work on this software, been really useful

**Comment by kauffman12** [comment]
What type of separator were you think of using? Just one character or being able to type in something complicated? Like +++ or something?

**Comment by SeanLatimer** [comment]
Single separator should be fine, I'd think. So for `|` it'd display like I mentioned above.

Come to think of it, an option to hide the time beside players would be nice also.
So instead of `Fackin = 9.22K@31 in 290s` an option to have it be like `Fackin = 9.22K@31`

**Comment by kauffman12** [comment]
Ok I'll add that to the list. Been buy lately so not sure when I'll get to it.

**Comment by kauffman12** [comment]
In 1.7.16 I just changed the default to | since that's what most people wanted originally anyway. There's also a checkbox for not showing time and it should remember the settings after restart. If you really think other delimiters are worth it I could look more into adding options.
