### ISSUE TITLE
Fight timers

### ISSUE THREAD

**Issue by The-Desthin** [kauffman12/EQLogParser#50]
Would it be possible to have a button activation for updating the Damage Summary with the fight timer functions? I've noticed on bigger fights(raids) that it will start trying to update before I have the time set.

Side note wasn't sure if relevant to open a diff ticket for it: Tabs used to open to the right and now they open to the left, is this intentional?

**Comment by kauffman12** [comment]
How long do you generally need to type in a value? As long as you're typing or clicking the arrows it should wait until you stop before refreshing. It has to see nothing happening for 1.2 seconds as it is now but I could increase that to 3 seconds if that would help. I'd like to avoid adding more controls to that summary if possible.

The left/right thing is just a different default with this new docking manager. I think I can switch it to add to the right instead.

**Comment by The-Desthin** [comment]
Ok I think I found what my problem was, just messing with like a 5000s parse and say i type in 4200s at the end point, as its calculating it will blank out and drop both to 0, I think that was making me think I had messed it up and then trying to fix it while it was still loading. I think 1.2s was a fine time it was user error.

![unknown6](https://user-images.githubusercontent.com/106119316/185704944-e77ce7b4-52aa-481e-846e-d606cd74cb50.png)

I can't speak for others, but I really preferred having my Summaries stuck in the left corner and not getting pushed out by new tabs
.

**Comment by kauffman12** [comment]
I see. Hmm maybe I can get them to not switch to 0 temporarily and add an indicator so you know how much time you have until it will requery.

**Comment by kauffman12** [comment]
Yeah this will be fixed in 2.0.4. Probably have something tomorrow.
