### ISSUE TITLE
Request:  Add Composite Fury to the ADPS chart.

### ISSUE THREAD

**Issue by AndrewDHokie** [kauffman12/EQLogParser#51]
https://everquest.allakhazam.com/db/spell.html?spell=61591
https://spells.eqresource.com/spells.php?id=61591

The zerker Composite Bloodsplash is tracked, so I think tracking the BeastLord ability should be in line with the purpose of that chart.

Thanks,

**Comment by kauffman12** [comment]
The spell messages are incorrect in game so check if it's showing up as Dissident Fury. Plus a lot of people still use Dicho so look for that too. 

If no Fury is showing up compare it to what Spell Counts says for Received Spells and maybe do a log search for 'is imbued with dissident fury' or 'is imbued with dichotomic fury' to make sure you're seeing the messages. It should be working.

**Comment by AndrewDHokie** [comment]
OK Odd - Went to go grab screenshots - And now I'm seeing it.

/boggle - Sorry will close this out.
