### ISSUE TITLE
Merge Pets, Always Grayed Out?

### ISSUE THREAD

**Issue by DoubleStuffin** [kauffman12/EQLogParser#52]
The option to right click a name and "Set Jasekar as Pet" is permanently grayed out it seems, can you add a more clear way to merge pets with their owners outside of using /pet leader ingame to have it auto update? Sometimes for older parses It would be nice to do in the program rather than the game

**Comment by kauffman12** [comment]
The option is probably disabled because it already knows that it's a pet. You can assign an owner in the Pet Owners window. Here's an example:

![petowners](https://user-images.githubusercontent.com/771335/186287020-a8006d8b-d3bc-432f-bb10-001d18fe4b58.png)

**Comment by DoubleStuffin** [comment]
Ah okay, from that point of view it makes sense. I just figured there'd be a click through on the actual parse window to say "Hey yeah this pet -> Player 1, this pet? -> Player2

**Comment by kauffman12** [comment]
I may be able to do something like that. Right now, it's mainly just to get it to show up in the pet list instead of the parser thinking it's a player.

**Comment by DoubleStuffin** [comment]
Yep yep, just tried your method and worked well, it'd be cool to have it assignable within members of the same parse/log/damage summary because it dramatically shortens the lists but as long as it can be done this way its all good.

**Comment by kauffman12** [comment]
Version 2.0.6 now has an updated right-click menu.
