### ISSUE TITLE
Healing Breakdown Twincast%

### ISSUE THREAD

**Issue by The-Desthin** [kauffman12/EQLogParser#53]
Looks like Healing Breakdown TC% doesn't pick anything up, but in the Healing Log it shows that Twins are actually happening.

As an aside I've been working on some healing stuff recently and I was wondering if a column could be added in the Healing Log tab for Heal and Over Healed combined? can't think of a good name for it, but I think it would be useful to see what the spell actually attempted to heal for in addition to it being broken up into how much actually got used and the leftovers, would make it much easier to sort the heals by size.

**Comment by kauffman12** [comment]
These will be in 2.0.7. Should be by tomorrow.
