### ISSUE TITLE
Windows-direction snap feature doesn't seem to work

### ISSUE THREAD

**Issue by esr-sudo** [kauffman12/EQLogParser#54]
It might just be me, but I have noticed I cannot use the windows snap function with eqlogparser.   I can't think of any other app that doesn't support it.    

If the window is not in full screen, you can windows-up to full screen it, and press windows-down to restore it to the prior setting, but I don't seem to be able to use windows-right to move it to automatically take up the right side of my screen.

**Comment by kauffman12** [comment]
Version 2.0.13 should have a fix for this.
