### ISSUE TITLE
Defensive Timeline

### ISSUE THREAD

**Issue by The-Desthin** [kauffman12/EQLogParser#55]
Only have Warrior Info avail to me for this but:
Seems to only pick up Dual Wield Proficiency, not Defensive or Two Handed

Not sure how detailed and all encompassing you want this timeline to be, so I'm not sure how much digging I should do into stuff that doesn't show up there.
Example:
Looks like Group Armor of the Inquisitor(and possibly self version) don't show up

**Comment by kauffman12** [comment]
Group Armor will only show up if you're the Paladin casting it. It doesn't have a message when someone else gets the buff.
![message](https://user-images.githubusercontent.com/771335/189499276-6fe393dd-129e-4870-bcb0-4ba59f721481.png)

It looks like Defensive Discipline has the same message as Pain Tolerance. So, you may be seeing it show up as that. It just picks the highest level or first one it seems in some cases when things have the same message. I might be able to tweak that one to pick a different name.

I don't know what Two Handed is so not sure if there's an issue with that.

**Comment by The-Desthin** [comment]
Sorry, I did it again where I'm not giving enough information.
I was meaning:
![image](https://user-images.githubusercontent.com/106119316/189501866-b0da0a0e-6266-43b5-b8f4-b522b7dc7f2e.png)
![image](https://user-images.githubusercontent.com/106119316/189501895-f8cde0c7-fda5-4443-bb87-22c8c4dacf19.png)
![image](https://user-images.githubusercontent.com/106119316/189501906-e944aee8-5920-4ebf-89d0-934e0041b2c7.png)
Of which only the dual-wielding one is currently working. Also looks like the other proficiencies don't show up in the spell counts for others at all, but they do show up in my logs, and per EQResources they appear to have unique spell emotes.

So is the Defensive Timeline just set to not pick up anything that other's can't see? I guess that would make sense to avoid confusion, I know there is the check box in the spell counts where it defaults to hiding everything that others can't see(which is the only way to see self receiving the group inquisitor.

**Comment by kauffman12** [comment]
Defensive Proficiency wasn't showing up because I wasn't checking for the shield block or mitigation SPAs. I can fix that.

Two-Handed isn't showing up because there's really nothing on there that is defensive. But it does show up on the ADPS timeline. I could count the negative Dodge and Parry values as defensive but that might be a little odd. Would you consider it DPS disc or no?

**Comment by kauffman12** [comment]
Try 2.0.14. If it sees the player activate Defensive Disc I think it should show the right name. Defensive Proficiency and Dual-Wielding should show up on the Defensive Timeline. Check for Two-Handed on the ADPS Timeline. And maybe I could combine them both if it's useful to see DPS stuff with defensive.

**Comment by The-Desthin** [comment]
I guess I was thinking it would be useful to see stuff that was negative to defensive stuff(especially being able to see when a player dies, might be able to backtrack to reasons why), but that might be a headache to keep track of with how many variables there would be, I think you have the right of it as it is now.

I personally like the Timelines being separate to keep from overcrowding.

Would it be possible to get the "Self Only" checkbox functionality added to the defensive timeline like it is for the ADPS timeline? That might work out for the stuff like (Group) Armor of the Inquisitor

**Comment by kauffman12** [comment]
So, currently the tank timeline is just showing everything. It doesn't care if something is self only. It looks like I'm missing SPA 1 and SPA 120 in my list for tanking buffs. That's probably why it's not showing up. I'll have to add those and probably add checks that they values aren't negative too. Some others are probably missing the negative value check.

I'll update something tomorrow but I'm probably missing some others too. Not sure how to track down all the needed SPAs until I see a spell people want. The current this I have is this:

55, 69, 114, 162, 168, 174, 175, 178, 197, 320, 323, 393, 405, 450, 451, 452, 505, 515, 516

**Comment by kauffman12** [comment]
Try 2.0.15. It has the checkbox and additional SPAs. Hopefully it's covering everything now.
