### ISSUE TITLE
Overlay Screen

### ISSUE THREAD

**Issue by shawnf1971** [kauffman12/EQLogParser#56]
Can you possibly put a timer onto the overlay screen that can be adjusted for it to stay on screen longer? A user inputted value in seconds?
It goes too quickly for me, then I have to go into the application to see the info.
If this is already available, I can't seem to find an option.

**Comment by kauffman12** [comment]
Have you tried changing the Reset on Kill setting to be like Reset 60s? Or do you want to keep it resetting after each kill but leave the window up longer?

**Comment by shawnf1971** [comment]
Thanks for the reply.
I wanted it to reset after each kill but leave it on the screen a bit longer so I have time to read the info with my old eyes. (Not as fast as I use to be)

I only started to use your application yesterday. I normally use GamParse with it set to 12 seconds to display the overlay after the fight.
I like your app better as it seems to be able to combine the BST’s warder in with the BST’s DPS.

I can’t work out how to do that with Gamparse, or I wouldn’t have gone looking 😊. I can only combine pet’s with their players like Necro, mage, ench pets.

**Comment by kauffman12** [comment]
Ok well for now I added a minimum time so in 2.0.15 it should stay up longer. If it needs to be longer I can try to make that configurable.

**Comment by shawnf1971** [comment]
Thanks. Much appreciated
I would think that different people would have a different requirement depending on how they play the game.
So one solution won’t fit all, as I presume in your case the time it displayed for was suitable to yourself.

**Comment by kauffman12** [comment]
Made a few more updates. I'll just leave it like this unless some others wanted the time shorter. I don't think many people have a strong opinion on this setting.

**Comment by shawnf1971** [comment]
Thanks.
