### ISSUE TITLE
Opening a log file while in a fight doesn't ignore inactive time

### ISSUE THREAD

**Issue by zoopadoopa** [kauffman12/EQLogParser#57]
If you open a log file for lets say the last 24hrs while you are already engaged in a fight, it will roll all the data up as if it just occurred in the live dps window ignoring the **Reset** timer

What I would expect to happen here is that any "Inactivity" section should follow the Reset setting (i.e, if your live dps window is set to reset after 60s, then any break 61s or larger should reset the live view immediately)

**Comment by kauffman12** [comment]
This should work in 2.0.21.
