### ISSUE TITLE
Export other options

### ISSUE THREAD

**Issue by SusanTN** [kauffman12/EQLogParser#6]
It would be nice to be able to copy and paste to a spread sheet for both the summary windows and most importantly the other sub windows you can open such as ADPS chart, spell cast timelines, damage breakdowns etc.

The copy should grab the header line, and all the selected rows.

You could alternatively give the option to open as a spreadsheet.

Is would also be nice if in a raid that the program can display group numbers to allow examination of group makeups.

**Comment by kauffman12** [comment]
There's a right-click Copy As CSV from the ADPS chart you could try. I can add more options like that to the other windows at some point.

**Comment by kauffman12** [comment]
The latest now has CSV from the spell cast timeline and I may be able to do the same for the summary windows soon.

**Comment by kauffman12** [comment]
Added Copy CSV/Image to the three summary tables. It does the whole summary though not just the selected.

**Comment by SusanTN** [comment]
Thanks!

**Comment by mahtayD** [comment]
how do I load the parser so its on my desktop

**Comment by kauffman12** [comment]
Open file explorer and go to:
C:\Program Files\EQLogParser

right-click EQLogParser.exe and select Create shortcut. It'll ask if you
want it on the Desktop. Click yes.

Once it's on the desktop you can right-click rename and change it to
something sensible.
