### ISSUE TITLE
Performance issues over time

### ISSUE THREAD

**Issue by martinb-uk** [kauffman12/EQLogParser#60]
After having EQLogParser running for a period of time, I notice that the PC starts to respond sluggishly.

From looking at the process listing, I don't notice EQLogParser using too much CPU or having any kind of memory leak - but I suspect there must be some kind of resource leak occurring to cause this style of lag.

The main way I see an issue is that my multiplicity (Software KVM) seamless mouse switching between screens starts to not work smoothly. There is a delay as I try to move the mouse between machines. 

I am very confident this issue is isolated and caused by EQLogParser as when I close the program, the system performance/sluggishness is immediately gone.

I am using the in-game overlay but I will also test without it enabled to see if the same kind of issue occurs. 

Please let me know if you can think of any way I can help to debug this issue.

**Comment by kauffman12** [comment]
How many rows end up in the fight list?
When you see it slow down. If you reload the log file and pick something short like the last 24 hours. Does the issue go away?

**Comment by martinb-uk** [comment]
The fights list has a relatively low number of records in it (a few hundred) when I start seeing the issue. Reloading the log file (last 8 hours) does stop the issue.

Next thing I'll try is running with the in-game overlay disabled to see if it's related to that.

**Comment by martinb-uk** [comment]
I ran the parser for a number of hours tonight while XPing and didn't see the issue at all. Therefore I highly suspect its something to do with having the overlay enabled.

**Comment by kauffman12** [comment]
Well the Overlay does try to stay as the top window. That's the only odd thing it does assuming it's not CPU related. Have you had any issues with Gamparse overlays or GINA overlays doing something similar? I don't think they're too different.

**Comment by martinb-uk** [comment]
I have used Gamparse and GINA overlays for years and have never experienced any issues like this. I will keep trying to debug on my side.

**Comment by kauffman12** [comment]
Try this version. I removed the forced top most window setting that was getting run every few seconds.

https://github.com/kauffman12/EQLogParser/raw/master/Release/Debug/EQLogParser-2.0.23.1-debug.msi

**Comment by martinb-uk** [comment]
Great I'll give it a try!

**Comment by martinb-uk** [comment]
Tested this a bit tonight and unfortunately it didn't seem to help. Over time (After playing for around 3 hours it started to become really noticeable) the sluggishness of the PC increased and mouse movements became slightly laggy. Exiting EQLogParser immediately fixed the issue. For the time being I can use a workaround of using GameParse for the live overlay, and EQLogParser for the rest (As I much prefer it!) but I'd love to get to the bottom of it....

**Comment by kauffman12** [comment]
Is the overlay up the entire 3 hours or are there breaks where it closes?
I'll do 3 hours of raids without an issue but I don't usually check memory
usage or anything. My parser is a lot more processor and memory intensive
than Gamparse but maybe something isn't being cleaned up. How much memory
does your system have free when you're playing?

**Comment by kauffman12** [comment]
I could see it starting to slow down if the Overlay isn't set to reset after each fight and you pull constantly so the mob count it displays gets to be pretty big. Like over 100 and especially on a slower system. If that's what's going on I can probably fix that.

**Comment by kauffman12** [comment]
Ok try 2.0.24 and see if it's any better.

**Comment by martinb-uk** [comment]
I'll give the new version a try. I do have the default setting of reset on kill for the overlay so it shouldn't be related to that aspect.

**Comment by kauffman12** [comment]
Yeah this change would probably only help reset on kill a very little bit. Maybe it's something with opening/closing the window a lot. I can test that next.

**Comment by kauffman12** [comment]
Alright I made a tester to loop through 6 or 7 kills in real time so I don't have to play for 3 hours. I'll just let this run and see what happens.

**Comment by kauffman12** [comment]
Well I think I know what's happening. The Overlay leaks some GDI objects every time it's open/closed and it's happening the Syncfusion library I'm using. I'll make a bug report with them and see if they can fix it. Otherwise I can try to use one window that I just show/hide instead of opening/closing but I'd rather not make that change yet.

**Comment by martinb-uk** [comment]
Interesting find - thanks for putting to effort into figuring that one one. That makes a lot of sense as I suspect multiplicity (software kvm) acting laggy could well be caused by a GDI leak. I'll pay attention to the GDI handle count and try and experience the growth myself.

**Comment by kauffman12** [comment]
Yeah I think you'll see the DC ones leaking. There's 1 I can fix but like 5 others that leak every time. It still should take a long time to run out but I could see things slowing down as it gets closer. I might just change the window to hide instead of close each time but I have to rework a few things to do that.

**Comment by martinb-uk** [comment]
After this many leaks things seem to start getting very laggy!

![image](https://user-images.githubusercontent.com/19375324/199115873-4c62c6de-373a-4a44-b16b-9b864bd3cc8c.png)

**Comment by kauffman12** [comment]
Thanks. That makes sense. I'll probably have some sort of fix in a week or so. Going to give Syncfusion some time to look at it.

**Comment by kauffman12** [comment]
Well Syncfusion needs to the 10th to look at the issue. I changed it to re-use the window but it doesn't help. The problem occurs every time the Height or Width is changed too...

**Comment by kauffman12** [comment]
Try 2.0.27. I changed the main overlay window to no longer use that Syncfusion class. However, the configuration window and the main parser window still use it so avoid moving/resizing things too much or it'll have problems. Hopefully Syncfusion will have a fix in a week or two but this should fix what you were seeing.

**Comment by martinb-uk** [comment]
Awesome. I'll give it a try tonight! Thanks.

**Comment by martinb-uk** [comment]
Working great! Many thanks for the fix.

**Comment by kauffman12** [comment]
No prob. I'll close this one for now and hopefully Syncfusion will fix the bigger issue for me and that'll be out in a couple weeks.
