### ISSUE TITLE
Incorrect identification of a warrior as a monk

### ISSUE THREAD

**Issue by dewey2461** [kauffman12/EQLogParser#61]
Version: v2.0.27 

We had a warrior get identified as a monk in the parse tonight. 

Attached is cropped log file. Gromm is a warror but identifies as a monk.

[eqlog_gromm_bertox.zip](https://github.com/kauffman12/EQLogParser/files/9952639/eqlog_gromm_bertox.zip)

**Comment by kauffman12** [comment]
Ok I'll check. You can also get some information about that in the parser now and set the class manually. Open the Verified Players window and hover over the class for that player and it'll say whether it was set manually, it was from a unique action like seeing slay undead to know it's a paladin, or it'll list a spell that was cast the most.

**Comment by kauffman12** [comment]
Try this in the latest.
