### ISSUE TITLE
Cleric Syllable of Invigoration not getting reported in class spell counts. 

### ISSUE THREAD

**Issue by dewey2461** [kauffman12/EQLogParser#62]
Version v2.0.27 

Cleric Syllable of Invigoration not getting reported in class spell counts. 

Steps to reproduce: 
1 - Select all entries for a fight
2 - Right click on damage or healing summary and select spell counts cleric

Using the log search tool searching term #1 "cleric name" and "casting Syllable" shows 13x casts. 

Healing Log shows "Syllable of Invigoration" being cast. 

Healing break down shows entry for "Syllable of Invigoration"

[eqlog_Burkeena_bertox.zip](https://github.com/kauffman12/EQLogParser/files/9953007/eqlog_Burkeena_bertox.zip)

**Comment by kauffman12** [comment]
It was being counted as a proc but that's fixed in 2.0.30.
