### ISSUE TITLE
Request: Death log parsing

### ISSUE THREAD

**Issue by Setsuni** [kauffman12/EQLogParser#63]
Hello,

I would love to see the ability to parse the last few seconds of a death. I want to know what exactly killed XYZ person. Was it the boss riposte? Was it an aoe, if so which one etc. 

![deathnote](https://user-images.githubusercontent.com/34042458/202983031-29693149-657c-4172-87bf-1835423b139b.png)

Attached is an example from wow.

**Comment by Setsuni** [comment]
Maybe it can be simpler to start. Perhaps a view last 10 seconds of the log that affects xyz player. So i can see that I died and I want to view the last 10 seconds of the log from where I did and anything that affected me. 

From there it can be added in where you can see emotes, boss casts etc that show a bigger picture. 

I hope this makes sense! ;)

**Comment by kauffman12** [comment]
It makes. Just trying to decide how it should work. Maybe it's an option
from the summary tables that opens a log search window with the right terms
and filters set instead of a new UI.

**Comment by kauffman12** [comment]
There's a really basic one in 2.0.38. I plan on adding more to it but it may take a little while.

**Comment by Setsuni** [comment]
Thanks. It look's good so far. For the death to melee damage it's nice to see what killed someone. 

Little wonky on spells, but I think that may be my range issue haha. 

Thanks again for looking into this.

**Comment by kauffman12** [comment]
Yeah EQ doesn't always have much to go by.
