### ISSUE TITLE
Damage overlay bug after restarting EQ/sleeping computer?

### ISSUE THREAD

**Issue by martinb-uk** [kauffman12/EQLogParser#64]
Whenever I restart EQ each day (or maybe its related to sleeping the computer in between?), after fighting any mobs, instead of seeing the Damage overlay, I see the following:

![image](https://user-images.githubusercontent.com/19375324/204671060-13939188-5531-4d16-8b35-fe88a09a1bb3.png)

None of these buttons function and trying to click on them results in an 'EQLogParser is not responding' windows popup.

To fix this I have to restart EQLogParser.

**Comment by kauffman12** [comment]
This was working for me in 2.0.35 but letting my PC sleep for 30 minutes or so but I did add some extra checks to 2.0.36 that may help if you're seeing a problem. I just manually close/restart the Overlay on resume/suspend events. Hopefully that does it. So, try the latest.

**Comment by martinb-uk** [comment]
Still no luck with 2.0.36. Same issue. 

When in this state, the cog icon does actually work, and I can open up the settings overlay and move it around, save/cancel etc. But the X button will not work at all. I tried everything I can think of and only restarting EQLogParser fixes it

**Comment by kauffman12** [comment]
Does it do it if you only leave your PC sleeping for a few minutes?

**Comment by martinb-uk** [comment]
I am still having a hard time understanding when it occurs. Sometimes after a sleep it does work. Other times I get the broken overlay. I'll keep trying to figure it out...

**Comment by kauffman12** [comment]
It may he related to a memory leak of sorts. I've been waiting for a fix
from Syncfusion which should be soon.

**Comment by Trice2022** [comment]
Also having the same issue. When I start ELP and run EQ in full windows mode, I get the config overlay box options (cog, copy, exit buttons) but only the cog will work. To get the overlay to come up in full windows I usually just hit the X on the Config overlay tab and the actual overlay would show. However, now I can't get it to show.

**Comment by kauffman12** [comment]
See if 2.0.39 helps with the sleep issue. Also, the Overlay doesn't really work in full screen. The fact it could was a bug in either .net or windows or EQ or something. I can't really support full screen without a big update and the Overlay would be tied to the game window. Not really planning on adding an option for that right now.

**Comment by martinb-uk** [comment]
I'm still seeing the bugged overlay issue with 2.0.39 unfortunately. 
EQ is in windowed mode.

**Comment by kauffman12** [comment]
There is a completely new damage meter in 2.1.0 that should be out soon that hopefully has this problem fixed. Look for it tonight or sometime on the 13th.

**Comment by Trice2022** [comment]
I really like the look of that. Great job!
    On Sunday, February 12, 2023 at 02:13:34 PM MST, kauffman12 ***@***.***> wrote:  
 
 


There is a completely new damage meter in 2.1.0 that should be out soon that hopefully has this problem fixed. Look for it tonight or sometime on the 13th.

**Comment by kauffman12** [comment]
Thanks!

**Comment by Trice2022** [comment]
After playing with it some more after last patch I noticed that in the main window, under the Fight List, it doesn't show the HPs for each mob anymore. Is this by design? 
    On Monday, February 13, 2023 at 07:08:58 PM MST, kauffman12 ***@***.***> wrote:  
 
 


Thanks!

**Comment by kauffman12** [comment]
Looks like it's a bug from renaming some things when I added the tank tab
to the damage meter. I'll have an update with some small fixes today or
tomorrow.

**Comment by Trice2022** [comment]
Awesome and thanks :)

    On Tuesday, February 14, 2023 at 02:18:02 PM MST, kauffman12 ***@***.***> wrote:  
 
 

Looks like it's a bug from renaming some things when I added the tank tab
to the damage meter. I'll have an update with some small fixes today or
tomorrow.
