### ISSUE TITLE
Clear Pet ownership from table

### ISSUE THREAD

**Issue by ritslacker** [kauffman12/EQLogParser#65]
Is it possible to remove a bunch of the unknown pets from the table?

More specifically, more than one player is listed as a pet of an unknown player, which messes with the graphs for that player a bit (DPS chart still seems to be fine, and tracks their pets as well) But I'd like to remove him until he says "Goofball Says, 'My leader is Kauffman12'" again.

Thanks

**Comment by kauffman12** [comment]
You can select the Player in the Pet Owners window and choose the Unknown Pet Owner option. Is that all you're trying to do? It's not super obvious that this is possible.

![RemovePet](https://user-images.githubusercontent.com/771335/204934604-1f9e1d9c-3d93-4be8-a300-601f7e3ba1c7.png)

**Comment by ritslacker** [comment]
Not quite.  The issue is I have Players listed as pets.  
![image](https://user-images.githubusercontent.com/13002182/204939440-73abad7d-a956-433d-837c-906079288439.png)

Madmonk and Tatsu are monks, and Xoog is a Beastlord, not pets.  But they got listed as a pet somehow and now I can't remove them from there.  This causes issues on the graph.
(these are the graphs for Xoog only, with the different selections)
![image](https://user-images.githubusercontent.com/13002182/204938666-f46764fb-3319-4438-a760-8c2d00887af5.png)
![image](https://user-images.githubusercontent.com/13002182/204938763-5389fb96-1c87-48a6-845d-b95f96d3b797.png)
![image](https://user-images.githubusercontent.com/13002182/204938988-a20baaff-c721-43e4-a066-8c7d5bec68b0.png)

In the chart, the data appears correct, with Xoog listed as a beastlord, and it assigns his pets to him, but since it thinks that Xoog himself is a pet of someone, it causes issues.
![image](https://user-images.githubusercontent.com/13002182/204939251-fa58f2fe-34f7-4085-9fe5-c406c9958993.png)

**Comment by kauffman12** [comment]
What about removing them from the Verified Pets UI? You would have to hit the X to delete them and probably reload the log file to see the change in the current fight list/parse.

![VerifiedPets](https://user-images.githubusercontent.com/771335/204989715-677cedd2-d074-4870-83dc-751839607d6b.png)

**Comment by ritslacker** [comment]
Strangely enough, it does not allow me to click the X.  I can unverify some of the random pet names like Lartik and such, but not them.

**Comment by kauffman12** [comment]
Hmm. I can't see how that would happen unless the player wasn't really in the list somehow. You do have the latest version right? 
I can add some debug to 2.0.35 to see what's going on.

**Comment by kauffman12** [comment]
Try removing them in the 2.0.35 and if it still doesn't work close the parser and manually edit the files. Just look under your user directory/server name.

Example. Under a directory like this there are two config files for players and pet mappings. Just remove the names from both.
C:\Users\john\AppData\Roaming\EQLogParser\config\xegony

**Comment by ritslacker** [comment]
Updating to 2.0.35 did the trick, thanks.   Did not even need to remove them.
