### ISSUE TITLE
Request: Instantaneous DPS graph

### ISSUE THREAD

**Issue by cpagega** [kauffman12/EQLogParser#66]
I would love a damage chart showing my instantaneous DPS rather than the average. I've attached an example from warcraft logs from my mage, you can see the roughly 90s burn cycle. This is what I mean, just in case I'm misusing the term instantaneous.

![dps graph example](https://user-images.githubusercontent.com/17533263/205451308-91b68c80-8a14-4eb7-babc-55298f1bf7ed.JPG)

**Comment by kauffman12** [comment]
If you're using the latest there's two DPS options. The one labeled DPS is similar although it doesn't smooth things out like that. Every point is the DPS at that second. It looks like warcraft logs DPS chart is showing a point every 2 seconds. I'll see what that looks like and maybe change it or add another option.

**Comment by cpagega** [comment]
Hey, thanks for getting back to me. I'll check out those charts. I didn't realize you had added some different options already. Appreciate your work on this.
