### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Kashmirre** [kauffman12/EQLogParser#69]
Been getting a lot of these crashes since the last update. 

Faulting application name: EQLogParser.exe, version: 1.0.0.0, time stamp: 0x6377dc84
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2364, time stamp: 0x5b7d4d22
Exception code: 0xe0434352
Fault offset: 0x000000000002cd29
Faulting process id: 0x5cf4
Faulting application start time: 0x01d929524685e95a
Faulting application path: C:\Program Files\EQLogParser\EQLogParser.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6c03a830-06bb-4c08-9b74-e4a9d7ae2960
Faulting package full name: 
Faulting package-relative application ID:

**Comment by kauffman12** [comment]
Does it happen when its active with the Overlay running or at startup or anything particular that triggers it?

**Comment by Kashmirre** [comment]
Been happening with the overlay active, fights stopping, but I know it's been repeatable.

**Comment by DoubleStuffin** [comment]
That looks like a really old version of EQLogParser unless the version wasn't brought up to date in the crash reporting tool

**Comment by Kashmirre** [comment]
> That looks like a really old version of EQLogParser unless the version wasn't brought up to date in the crash reporting tool

All I can say is I'm running the latest version 2.0.39

**Comment by kauffman12** [comment]
Try 2.0.41. Updated the product I'm using again. Hoping it helps.

**Comment by kauffman12** [comment]
2.0.43 has been working for everyone now that I'm aware of plus Windows 11 is good again too. I'd try that.
