### ISSUE TITLE
Unable to download V2.0.41

### ISSUE THREAD

**Issue by Trice2022** [kauffman12/EQLogParser#70]
When I hit download I get a box telling me there was a problem. This is what i'm getting in the error log: 

2023-01-22 05:29:26,093 [1] INFO EQLogParser.MainWindow - Initialized Components
2023-01-22 05:29:26,102 [1] INFO EQLogParser.MainWindow - Selected Log File: C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\Logs\eqlog_Trice_povar.txt
2023-01-22 05:29:27,045 [1] INFO EQLogParser.MainWindow - Finished Loading Log File in 1 seconds.
2023-01-22 05:29:38,972 [1] ERROR EQLogParser.MainActions - Error Installing Updates
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'.
   at System.Net.Http.HttpClient.CheckDisposed()
   at System.Net.Http.HttpClient.CheckRequestBeforeSend(HttpRequestMessage request)
   at System.Net.Http.HttpClient.GetStreamAsync(Uri requestUri, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStreamAsync(String requestUri)
   at EQLogParser.MainActions.<>c__DisplayClass9_1.<CheckVersion>b__1()

**Comment by kauffman12** [comment]
Hmm I see how that could happen. Odd that it was working before.  I guess manually download for now but I should have a fix for the next version.

**Comment by Trice2022** [comment]
Tried downloading it from the site but after it downloads, it won't let me open it to install. I get the message from windows installer: "This installation package could not be opened. Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid windows Installer package". 
    On Sunday, January 22, 2023 at 10:51:59 AM MST, kauffman12 ***@***.***> wrote:  
 
 


Hmm I see how that could happen. Odd that it was working before. I guess manually download for now but I should have a fix for the next version.

**Comment by kauffman12** [comment]
Here's a direct link to the latest. It should work unless anti-virus or something blocks you from running it or is deleting it on you behind the scenes.
https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-2.0.42.msi

**Comment by Trice2022** [comment]
Got it downloaded but and installed but when I try to run it, nothing happens. /shurg
    On Sunday, January 22, 2023 at 02:21:36 PM MST, kauffman12 ***@***.***> wrote:  
 
 


Here's a direct link to the latest. It should work unless anti-virus or something blocks you from running it or is deleting it on you behind the scenes.
https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-2.0.42.msi

**Comment by kauffman12** [comment]
It might be missing speech libraries. I'll try it on another system to see what happens.

**Comment by kauffman12** [comment]
Also what version of Windows do you have?

**Comment by Trice2022** [comment]
I had to disable my antivirus to get it to download. Can you send me a link or something to the last version? Maybe that one will still work. 

    On Sunday, January 22, 2023 at 03:41:54 PM MST, kauffman12 ***@***.***> wrote:  
 
 


It might be missing speech libraries. I'll try it on another system to see what happens.

**Comment by Trice2022** [comment]
I'm running Windows 11. 
    On Sunday, January 22, 2023 at 10:51:59 AM MST, kauffman12 ***@***.***> wrote:  
 
 


Hmm I see how that could happen. Odd that it was working before. I guess manually download for now but I should have a fix for the next version.

**Comment by kauffman12** [comment]
Yeah I just a Windows 11 VM and it doesn't work. I probably need a different version of the speech library to install with it maybe.

I guess try this older version. And you may want to install it then install it again and run repair to make sure it puts everything back ok. It's annoying but repair should work for sure.
https://github.com/kauffman12/EQLogParser/raw/master/Release/Previous/EQLogParser-2.0.37.msi

**Comment by Trice2022** [comment]
Got 2.0.37 installed and it's working. Thanks!
    On Sunday, January 22, 2023 at 03:51:39 PM MST, kauffman12 ***@***.***> wrote:  
 
 


Yeah I just a Windows 11 VM and it doesn't work. I probably need a different version of the speech library to install with it maybe.

I guess try this older version. And you may want to install it then install it again and run repair to make sure it puts everything back ok. It's annoying but repair should work for sure.
https://github.com/kauffman12/EQLogParser/raw/master/Release/Previous/EQLogParser-2.0.37.msi

**Comment by kauffman12** [comment]
Ok try install the latest. It should work with Windows 11 or at least it worked on the VM I have. Here's a direct link.

https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-2.0.43.msi

**Comment by Trice2022** [comment]
Got the windows installer message that says to verify that the package exist and that you can access it ect........
    On Sunday, January 22, 2023 at 07:50:49 PM MST, kauffman12 ***@***.***> wrote:  
 
 


Ok try install the latest. It should work with Windows 11 or at least it worked on the VM I have. Here's a direct link.

https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-2.0.43.msi

**Comment by kauffman12** [comment]
That's probably the antivirus software again. That's not really an error the installer can give.

**Comment by Trice2022** [comment]
It was my virus scan again. Got it installed and it's working. Also went to playing EQ in windows mode so I could get the overlay. Thanks for the help!
    On Monday, January 23, 2023 at 12:41:48 PM MST, kauffman12 ***@***.***> wrote:  
 
 


That's probably the antivirus software again. That's not really an error the installer can give.
