### ISSUE TITLE
Trigger Manager tutorial request

### ISSUE THREAD

**Issue by esr-sudo** [kauffman12/EQLogParser#71]
I'm surprised to see gina style triggers be added into the parser.   Can  you provide some instructions on how to use it?  I'm familiar with GINA.

**Comment by kauffman12** [comment]
It's still a work in progress so expect to have to recreate/import things if you start playing with it now. It should all be ironed our in a week or two.

I'll come up with something better but for starters given you use GINA. Just open Trigger Manager from the View menu. Right-click on the Triggers folder and select Import. You can choose a GINA triggers file. Then after Import just check the folder to enable them like GINA. 

You also have to be reading a log file for it to let you turn on the triggers. Once you load a log file hit the start button at the top of Trigger Manager. And that's really all there is too it. It should work. You can then right-click on the Overlays folder and create a timer or text overlays. There's properties on the right that you can change. And a quick way to assign an overlay to a bunch of triggers is just right-click on their folder and select Assign Triggers. It'll set the Overlay you pick on everything under the tree you selected.

Anyway that's just a 2 minute writeup for how to get started. It;'s similar to GINA to so you'll probably figure it out quick enough. And I'm still adding the basics so there's no new features yet. One on the list of things to add is Timers that reset based on a cooldown time so you can track when to use your ADPS. Then we'll see about other stuff.

**Comment by esr-sudo** [comment]
Sounds good.  I'm definitely curious!

**Comment by martinb-uk** [comment]
Very excited to see the new Triggers & Overlays functionality coming to EQ Log Parser and it's great you immediately implemented to be able to import from GINA!

One thing which would be awesome to consider is how EQ Log Parser could implement GINAs ability to parse multiple logs concurrently. I use this extensively and have GINA reading all of my box logs so that triggers/overlays appear on my main PC rather than on the box.

**Comment by LamahHerder** [comment]
> Very excited to see the new Triggers & Overlays functionality coming to EQ Log Parser and it's great you immediately implemented to be able to import from GINA!
> 
> One thing which would be awesome to consider is how EQ Log Parser could implement GINAs ability to parse multiple logs concurrently. I use this extensively and have GINA reading all of my box logs so that triggers/overlays appear on my main PC rather than on the box.

Concur on all points

**Comment by ehuntercommer** [comment]
Reading multiple logs would be awesome. Gina works, but it does like to crash occasionally with Windows 11. Having everything in one program would be awesome but multiple log files is a must to do that

**Comment by kauffman12** [comment]
That's something I may be able to add but it won't be done anytime soon. Maybe in a few weeks I can get back to the parser.

**Comment by kauffman12** [comment]
There's a few videos now on youtube. Everyone can just search there now. Maybe one day I'll put some official ones together but what's out there looks decent. Here's one for example that's worth checking out:

https://www.youtube.com/watch?v=OcaXCBLW2Gs
