### ISSUE TITLE
Not counting some pet heals

### ISSUE THREAD

**Issue by ritslacker** [kauffman12/EQLogParser#73]
It is not counting heals for some pets, but is for others.  It seems to avoid warders with standard names and swarm pets.  (To be honest, I am note even sure if swarm pets get healed from anything) 

Mage pets seem to be counted, renamed warders also seem to be counted. (Hedwig is a mage pet, Dracomir`s Warder is my Beastlord Pet)

![Not counting some pets for healing](https://user-images.githubusercontent.com/13002182/218648121-4e7354a6-eecb-4a36-bf77-38100363b188.PNG)

I do have healing for pets turned on:  Example line from log:
[Mon Feb 13 22:12:22 2023] You healed Dracomir`s warder for 77441 (102782) hit points by Salve of Blezon Rk. III. (Critical)

**Comment by kauffman12** [comment]
Part of it is our healers wanted to ignore swarm pets as to not inflate their healing parses. I may just add an Option -> Healing Settings to turn that on or off.

**Comment by ritslacker** [comment]
Could it differentiate between Beastlord Warders and Swarm Pets?  I suppose I could just bite the bullet and get a potion of forgetfulness and rename my pet, I suppose...

**Comment by kauffman12** [comment]
Yeah ideally. The warder is named different than your swarms. I'll see if something is messed up with parsing those.

**Comment by kauffman12** [comment]
ok try version 2.1.1. The only issue left is that if a merc healer has a name with spaces in it then it prob won't show up.

**Comment by ritslacker** [comment]
Looks good (sorry for the late reply)  Thanks!
