### ISSUE TITLE
Assigning unique pet name to Enchanter

### ISSUE THREAD

**Issue by HankFV** [kauffman12/EQLogParser#75]
Good morning!

     I am unable to assign my enchanter's pet, the enchanter does not show up as an available owner. Is there a way to force this?

**Comment by kauffman12** [comment]
1. Load a parse where both the Enchanter and pet are showing up in the DPS Summary.
2. Open View -> Verified Pets and make sure the Enchanter isn't showing up in there for some reason. If so hit the X button and remove them.
3. On the DPS summary right-click on the Pet and it should give you an option to Assign it to the Enchanter.
4. Normally all you need to do is have the Enchanter do a pet leader command. Is it some low level Enchanter who isn't doing much to be picked up by the parser as a real player? They should show up in the Verified Players list when they do things.


![image](https://user-images.githubusercontent.com/771335/219397716-f4bfdd0c-839a-4de4-bc55-1564f73d2579.png)

**Comment by HankFV** [comment]
Thanks for the quick reply sir! I did the leader command someone told me about and problem solved! He's a 120 BIS enchanter doing melee, but all better now.

**Comment by kauffman12** [comment]
Sure no prob.
