### ISSUE TITLE
Storing "LastTriggered" in exported triggers file

### ISSUE THREAD

**Issue by yeroca** [kauffman12/EQLogParser#77]
I was curious about the format used for triggers.  I saw that it's using JSON instead of XML from Gina.  Then I used jq to browse through the contents.

I notice that there's a field called "LastTriggered", which I figure is a timestamp.  I don't think it's a good idea to store that field in the exported file, because it's likely to change every time.  If someone tries to compare their trigger file with one created at a different time, they will likely compare unequal, even though there's no actual change in the triggers.

I realize this is a very minor issue.

**Comment by kauffman12** [comment]
Next version should have that field removed for export. It's not important to share with anyone.

**Comment by yeroca** [comment]
Confirmed the field is no longer there in 2.1.11
