### ISSUE TITLE
Minor issues with short-duration timers

### ISSUE THREAD

**Issue by yeroca** [kauffman12/EQLogParser#78]
Gina supports timers with a duration of fractional seconds, but it seems the time in EQ Log Parser is only integer seconds.  I use short duration timers for "melee out range" and similar warnings.  When I imported the Gina triggers, the timer duration got set to 0 because my Gina timer was 0.7 seconds.

I tried using a 1-second timer, but the result doesn't look good.  The animation of a 1-second countdown timer is a bit clunky.

I realize these are minor issues, but I wanted to report them in case they are easy to fix :D  (at some point)

Thanks

**Comment by kauffman12** [comment]
It may look extra clunky since the timer progress is only updated every 500ms right now. I'll look at adding support for them. I don't think it'll be a big change but I do want to handle them differently than the rest.

**Comment by kauffman12** [comment]
In fact, can you explain what other cases that you use short timers? I imagine they don't need support for warning messages or ending early? What's the minimum duration you use? Like if the Duration field for a short timer allowed values between 200 and 2000ms would that be plenty?

**Comment by yeroca** [comment]
The only use I have for the short ones at the moment, are like for things like "you can't hit them from here", "you can't see your target", "You need to select a target".  They are all set to 700ms.   Maybe you could make the update rate dependent on the duration for each timer.   For example slice the duration into 20 pieces.  For a 700ms timer, that would be updating every 35ms, so maybe that's too often.    Maybe a minimum cap of 100ms.  Just throwing an idea out there.

**Comment by kauffman12** [comment]
Ok try version 2.1.11 and either re-import from GINA to test if that works or switch your trigger setting to say Short Duration instead of Basic which is now the default Timer choice.

**Comment by yeroca** [comment]
Working great!  Thank you

**Comment by kauffman12** [comment]
Great good to hear!
