### ISSUE TITLE
Suggestion: in addition to sound trigger priorities, sound queuing could be useful

### ISSUE THREAD

**Issue by yeroca** [kauffman12/EQLogParser#80]
Sometimes I want a sound to play, but not interrupt the currently playing sound.  So being able to queue a sound to play when its priority allows would be a cool feature.

Some time ago, I wrote a log parser that chose another alternative, and that is to mix the sounds (I used FMod lib to do the mixing), rather than interrupt.  This is pretty good, because I seldom missed an audio trigger this way, but if two sounds with wordings play at the same time, it's not great, as you might imagine.  So I wouldn't advocate for this solution, though it had some upsides.

**Comment by kauffman12** [comment]
Yeah I think GINA kinda did that but I tried to stay more like EQ's audio triggers for playing wav files. I could make it a global option to queue or not queue while keeping the priority checks to cancel currently playing sounds if needed. Not sure if I'd want to make that setting per trigger as it just makes things extra complicated. I don't know.

**Comment by yeroca** [comment]
Yeah, it occurred to me it's a bit complicated, because what happens if a low priority message is interrupted by a higher priority message... in that case do you requeue the lower priority message to play again after the high priority one?  In some cases it might get requeued several times, if it gets interrupted more than once.  I guess you could maintain a max requeue count, and stop requeueing after say 2 times.  Ugh.

**Comment by kauffman12** [comment]
Audio was just re-worked and I think I'm going to leave things as they are unless there's a specific problem people are having.
