### ISSUE TITLE
MSI Installation on Windows 11 failure

### ISSUE THREAD

**Issue by Neclub** [kauffman12/EQLogParser#81]
The following error occurs in Windows 11. 

I have disabled Windows Defender and anti virus software while trouble shooting this. 
Both automatic update and direct downloads from git hub have been tried.
I have also tried to install to a different directory and a different drive.

Any thoughts on what may be causing the issue?

Thanks
![msiexec_yJ6QrjcxV8](https://user-images.githubusercontent.com/18217817/222971154-3dd36323-c75d-437f-8bff-fcfe884a5317.png)

**Comment by kauffman12** [comment]
If you want you can try installing from the command line and creating a log file:
msiexec /i EQLogParser-2.1.17.msi /L*vx install.log

I haven't seen a problem installing on Windows 11 using build 22621.

**Comment by kauffman12** [comment]
Also check from the command line that the dotnet command works.

![image](https://user-images.githubusercontent.com/771335/222982876-68731f13-3943-408f-9484-b1a80388b1d7.png)
