### ISSUE TITLE
Changing voice rate causes crash in v2.1.14

### ISSUE THREAD

**Issue by yeroca** [kauffman12/EQLogParser#82]
If I bring up the Trigger Manager, then change the voice rate from Default Voice Rate to Increased Rate 1, the app crashes.  It happens every time.

**Comment by kauffman12** [comment]
Yeah that's a known bug that will be fixed in the next version. For now to work around this you have to change the voice. Then once it has a saved voice you can change the rate.

**Comment by yeroca** [comment]
Ah, ok, That works, thank you.
