### ISSUE TITLE
Request: Twitch Integration

### ISSUE THREAD

**Issue by Phynster** [kauffman12/EQLogParser#84]
Hello sir, I hope this finds you well. I am a Streamer on Twitch who plays a lot of EQ when streaming and I was wondering, if it was possible, to get a Twitch Integrated Overlay or something that I could add to my channel so that people could see my dps meter when I am streaming.

**Comment by kauffman12** [comment]
Can't you just share your desktop?

**Comment by Phynster** [comment]
That is severely unsafe. I've known a many Twitch Streamers who have shared their desktop and something as simple as a Copywritten Icon that showed the content of a photo was enough to get someone a strike against their account. That would also show my own Stream Studio's Overlay ontop of my stream which would look extremely messy and cluttered lol. Plus, I'm trying to get into streaming professionally, and it just looks cleaner when you're not showing everything.

**Comment by kauffman12** [comment]
Yeah that's often why people have a streaming PC so there's nothing on it that would be bad to show by accident.

Anyway, I'll look at the options for doing something twitch specific. No idea at the moment if it's something that could be done soon.

**Comment by kauffman12** [comment]
So I don't know if you're interested in this anymore but was this really only about the DPS meter? I think I can have a setting where the DPS meter shows up as its own window so you can select it in OBS. It would also probably show up if you alt-tab. If that sounds like all you need?

**Comment by kauffman12** [comment]
2.1.66 has the stream mode option for DPS overlay as mentioned above.
