### ISSUE TITLE
Empty white 2nd window?

### ISSUE THREAD

**Issue by LamahHerder** [kauffman12/EQLogParser#85]
I often/always? have an empty white window opened when I start eqlogparser

![image](https://user-images.githubusercontent.com/22425296/223658731-e692488f-3b91-4504-a388-23e39669a781.png)

**Comment by kauffman12** [comment]
Maybe turn off the damage meter and restart to see if that's what is doing it. What version of Windows is it?

**Comment by LamahHerder** [comment]
It does go away once the overlay kicks in

Windows 10

**Comment by LamahHerder** [comment]
> Maybe turn off the damage meter and restart to see if that's what is doing it. What version of Windows is it?

Still there if I disable meter, close app, reopen app

![image](https://user-images.githubusercontent.com/22425296/224113615-f97c117c-7825-45ab-ba99-327660a91be5.png)
