### ISSUE TITLE
Request:  Log search

### ISSUE THREAD

**Issue by TatankaEQ** [kauffman12/EQLogParser#86]
I've moved over to using EQLogParser, from GamParse, but I find I still need to keep GamParse around for the log search feature, because many of the messages I want to check/track don't happen during fights, so they aren't tracked by EQLogParse.

One example is Mortal Coil.  I don't see it tracked by EQLogParse, because it triggers right after the mob dies.  But a log search can show when it was triggered.

Thanks!

**Comment by kauffman12** [comment]
Does the existing log search not do what you need?

**Comment by Rhiven** [comment]
The existing log search can be found here:

![Screenshot 2023-03-13 020229](https://user-images.githubusercontent.com/4743450/224620231-f421c413-647d-4051-824e-02a0dfafbe2c.png)

**Comment by TatankaEQ** [comment]
Lol, I never noticed it in that menu. Thanks for pointing it out, I'm sure
that will do nicely. Feel free to delete my request and thanks for the
prompt response

**Comment by kauffman12** [comment]
Sounds good.
