### ISSUE TITLE
What causes my player name to be replaced with "You" ?

### ISSUE THREAD

**Issue by DoubleStuffin** [kauffman12/EQLogParser#87]
Causes issues when I go back and look at older parses, separates out swarm pet damage etc from being properly assigned to me it seems like. 

Instead of "Charactername" its just "You" shown in the parses (Which makes it kind of silly to try and link/show to people)

**Comment by DoubleStuffin** [comment]
Okay got it. Yep it was a renamed logfile (Just to remember what events were involved) Its a recent log from the past few days though. Odd that on the renamed file though it labels me "You" and on standard EQ format it keeps char name, if anything I thought it'd be the inverse

**Comment by yeroca** [comment]
The parser has no way of knowing the character's name other than looking at the name of the log file, because your character's name is not inside the log  anywhere.  The log file only refers to "you"
