### ISSUE TITLE
Damage Meter Issue

### ISSUE THREAD

**Issue by Jigglebilly94** [kauffman12/EQLogParser#89]
![image](https://user-images.githubusercontent.com/129041877/227870776-c5c9a265-de75-4f87-b7bc-819e52146672.png)

I am unable to change the settings on my damage meter and am stuck with what seems to be a default.

**Comment by kauffman12** [comment]
Are you able to click the drop downs or move the window or anything? The close buttons looks disabled like some change was made. Next you would hit Save to keep the change. If that doesn't work after hitting Save look at the error log and see if there's anything that stands out. You can view it from the Tools menu.

**Comment by Jigglebilly94** [comment]
Weird, I logged on today and it's working fine. Thank you for your quick response, but it looks like it fixed itself! Great program!

**Comment by kauffman12** [comment]
Ok
