### ISSUE TITLE
Berserkers Shriveling Strikes

### ISSUE THREAD

**Issue by Krookz89** [kauffman12/EQLogParser#9]
Shriveling Strikes is not being picked up by Parser. Sapping Strikes is which is the old version we used.

**Comment by kauffman12** [comment]
Is that with 1.7.14? I was just testing this and Shriveling Strikes is showing up in the cast counts and hit frequency chart for me. I'm looking at other Zerkers using it though. Is it maybe not working for yourself?

**Comment by kauffman12** [comment]
Closing this for now. I think it's showing up in the latest.
