### ISSUE TITLE
Trigger Manager - adding Drop Shadow to text in overlays like GINA?

### ISSUE THREAD

**Issue by CrzyHlfAzn** [kauffman12/EQLogParser#90]
Request to add drop shadow or the ability to toggle drop shadow on text that are displayed in an Text Overlay.  GINA has drop shadows on their text and it helps to see the text better in certain colors in the game.

**Comment by kauffman12** [comment]
2.1.25 has a drop shadow but it's not configurable. I may do that after I re-work triggers later this year.
