### ISSUE TITLE
Beastlords pet not appearing

### ISSUE THREAD

**Issue by derakorV** [kauffman12/EQLogParser#92]
My box group has a beastlord and their pet does not appear in the DPS parses at all. I confirmed that the pets damage is showing in the log file.

**Comment by kauffman12** [comment]
Have you done the pet leader command?

**Comment by derakorV** [comment]
Yes I tried that a couple times. Do I need to monitor the beastlords log file or should any log file work?

**Comment by kauffman12** [comment]
Does it show up in the NPC list? There is an option to change it to a Pet if so. Plus check the Verified Players list to make sure it's not in there.

![image](https://user-images.githubusercontent.com/771335/235328800-a31ff8ed-c317-4c3b-9dc2-c04089480b20.png)

If none of that helps. What's the name of the pet?

**Comment by kauffman12** [comment]
Closing until I get more info. It seems to work for other people.
