### ISSUE TITLE
Setup Damage Meter just shows the Examples and does nothing

### ISSUE THREAD

**Issue by redmondgiant** [kauffman12/EQLogParser#93]
I am not sure I am doing something wrong, but when I click on the gear icon in the upper left on the damage meter overlay, it just displays the Examples but offers no interaction and no way to go back to just viewing the live meter. I have to re-monitor my log to get it to reset and go back to showing a live meter.

**Comment by kauffman12** [comment]
Are the buttons at the bottom showing up? Normally you just click Save/Cancel for your changes and then click the Close button for it to go away and start monitoring again.

![image](https://github.com/kauffman12/EQLogParser/assets/771335/c02b650c-63b0-4706-a5f7-3d7af5290d34)

**Comment by redmondgiant** [comment]
OK now I see it, had to make the window bigger. Thanks.
    On Tuesday, May 9, 2023 at 08:43:54 PM PDT, kauffman12 ***@***.***> wrote:  
 
 


Are the buttons at the bottom showing up? Normally you just click Save/Cancel for your changes and then click the Close button for it to go away and start monitoring again.
