### ISSUE TITLE
Copy as image bug

### ISSUE THREAD

**Issue by Primal420** [kauffman12/EQLogParser#94]
when i use eq log parser and i sort spell counts by class, in the app i see all of the data.  The problem arises when i select all and copy as image or larger image it produces a cropped image without all the columns.  This only happens on the spell counts breakdown

**Comment by Primal420** [comment]
![image](https://github.com/kauffman12/EQLogParser/assets/134641230/867e190b-dd64-4c9d-8fcc-c9c141b6686a)

**Comment by kauffman12** [comment]
How many columns are you seeing when it stops working? Are you selecting all players and view all spell counts at once?

**Comment by Primal420** [comment]
it seems to be cropping at this sized no matter how many columns im seeing in the app. ill post a few more copied images from the app and some screen snippets to sh ow you where its cropping at

**Comment by Primal420** [comment]
![image](https://github.com/kauffman12/EQLogParser/assets/134641230/bb068e21-8f26-4169-8901-26783ed3508c)

**Comment by Primal420** [comment]
vs a screen capture via snipping tool 
![image](https://github.com/kauffman12/EQLogParser/assets/134641230/433dcdc6-5586-46a1-9925-7bb3392fef49)

**Comment by Primal420** [comment]
so i am selecting all then copying as image.  copy as image and copy as larger image makes no difference it is the same result

**Comment by Primal420** [comment]
vs screen capture via snipping tool 
![image](https://github.com/kauffman12/EQLogParser/assets/134641230/0e1f0d8a-aec4-4c93-b5af-ae08535abd43)

**Comment by Primal420** [comment]
i have uninstalled and reinstalled twice same results with copying as image

**Comment by Primal420** [comment]
i can also do a screen share via discord if you would like to see what im doing to try to narrow down the issue

**Comment by kauffman12** [comment]
Copy image should copy everything that's visible and going by your screen grabs it doesn't look it is. It's been working ok for me so maybe it's a software version difference.

Doy you use Windows 10 or 11? And if you run dotnet --list-runtimes what versions of Microsoft.WindowsDesktop.App do you see? It uses the latest 6.0.x that you have installed. At the very bottom here you can see 6.0.15 which is what mine should be using. Also I guess a last thought is what resolution do you use? I can try changing that too. Maybe I'm calculating something that changes with res or windows scaling.

![image](https://github.com/kauffman12/EQLogParser/assets/771335/df9402de-4047-4065-ba75-50500f4568e5)

**Comment by Primal420** [comment]
![image](https://github.com/kauffman12/EQLogParser/assets/134641230/f792003e-c3da-4854-b69e-6605b49488e5)
 windows 11 and im running 4k resolution on a 43 inch monitor

**Comment by kauffman12** [comment]
Well so far I've tried a windows 11 VM with .NET 6.0.7, changing resolutions, windows dpi scaling. and having the parse be partially off screen. Everything has worked. The only thing I'm missing is an actual 4K display to test with. Maybe I can make a debug build you could try that prints some extra stuff out but not too sure yet. It is a weird issue.

**Comment by Primal420** [comment]
it is for sure strange.  i do appreciate all the help btw.  i dont know if this helps your or not but when i copy it as a file (cmv?) and send it as a link for someone else to import ...they get the full info and can copy it as image.  its for sure some conflict with my pc and im running out of steam trying to narrow it down lol

**Comment by kauffman12** [comment]
Do you happen to use 2 screens/monitors where one of them is using windows scaling so it's not the default DPI?

**Comment by Primal420** [comment]
only one monitor its just a giant monitor i set windows scaling down to 100 percent from 125 ...same cropping issues

**Comment by kauffman12** [comment]
Interesting. I think DPI is related though. If I hard code 120 instead of the 96 DPI this windows API is giving me I get an image just like yours. There's space between the title and the table and cuts off the right side. I may have to find other ways to figure out the current DPI to use.

![image](https://github.com/kauffman12/EQLogParser/assets/771335/c0a64021-e50e-4de7-9169-8fce00d1d736)

**Comment by kauffman12** [comment]
Try this version:
https://github.com/kauffman12/EQLogParser/raw/master/Release/Test/EQLogParser-test.msi

The log file should print the DPI it tries to use. Hopefully it's something other than 96 when you copy image.

**Comment by Primal420** [comment]
still cuts it off when i copy as image ...copied this from the error log file though 

2023-06-10 02:54:15,697 [1] WARN EQLogParser.UIElementUtil - Default DPI = 96
2023-06-10 02:54:15,705 [1] WARN EQLogParser.UIElementUtil - VisualTreeHelper DPI = 120
2023-06-10 02:54:18,189 [1] INFO EQLogParser.MainWindow - Initialized Components
2023-06-10 02:54:18,194 [1] INFO EQLogParser.MainWindow - Selected Log File: C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\Logs\eqlog_Primal_mischief.txt
2023-06-10 02:54:19,342 [1] INFO EQLogParser.MainWindow - Finished Loading Log File in 1 seconds.
2023-06-10 02:54:56,732 [1] INFO EQLogParser.MainWindow - Selected Log File: C:\Users\Public\Daybreak Game Company\Installed Games\EverQuest\Logs\eqlog_Primal_mischief.txt
2023-06-10 02:54:57,473 [1] INFO EQLogParser.MainWindow - Finished Loading Log File in 1 seconds.
2023-06-10 02:55:17,301 [1] WARN EQLogParser.UIElementUtil - Default DPI = 96
2023-06-10 02:55:17,302 [1] WARN EQLogParser.UIElementUtil - PresentationSource DPI = 120

**Comment by kauffman12** [comment]
Ok try this one. What might be happening is .Net 6 is doing some scaling behind the scenes and I should just be hard coding 96.0 instead of trying to query the current value.

https://github.com/kauffman12/EQLogParser/raw/master/Release/Test/EQLogParser-test2.msi

**Comment by Primal420** [comment]
i think you might have got it fixed on that last download

all copy as image both regular and larger image size are copying the full table of data with no cropping issues

**Comment by kauffman12** [comment]
OK. If that didn't work I was out of options. I'll include it with some other small changes in a real update later today/tomorrow. I'll skip to version 2.1.20.

**Comment by Primal420** [comment]
thank you for taking so much time to figure out my issue

**Comment by kauffman12** [comment]
No prob.
