### ISSUE TITLE
Syncfusion License expired

### ISSUE THREAD

**Issue by alexmk92** [kauffman12/EQLogParser#96]
## Description
Since upgrading to the latest version of EQLog Parser the UI library license seems to have expired.  The application force quits after acknowledging the alert.

## Reproduction version
[V2.1.21](https://github.com/kauffman12/EQLogParser/releases/tag/2.1.21)

## Reproduction steps
1. Either update 2.1.20 to 2.1.21 or download and install 2.1.21 from the releases page
2. Start EQLog Parser
3. SyncFusion License expiration modal appears

## Screenshots
![image](https://github.com/kauffman12/EQLogParser/assets/3603112/b99c5c7c-5cc4-418f-86e7-49367bb6dbe1)

**Comment by kauffman12** [comment]
Ok I got a newer license key. Try this one:

https://github.com/kauffman12/EQLogParser/raw/master/Release/EQLogParser-2.1.22.msi

**Comment by alexmk92** [comment]
This worked, thank you! 😄
