### ISSUE TITLE
Audio trigger not working

### ISSUE THREAD

**Issue by OkieDan** [kauffman12/EQLogParser#97]
Are there any examples for matching text for audio triggers available?  Either this isn't working or I'm just doing it wrong.  Here's an example that isn't working:

![image](https://github.com/kauffman12/EQLogParser/assets/137017569/a260513b-7ff2-454b-80e1-320d3706a21f)

**Comment by kauffman12** [comment]
Oh I see. Click the Activate Triggers button at the top. 

It kinda looks like a tab so it's a little confusing but I wanted a way to turn everything on or off easily so there's a big activate/deactivate button. When Triggers are enabled it looks like this:

![image](https://github.com/kauffman12/EQLogParser/assets/771335/d576c9e3-3ed8-499d-97da-b50b746fa9e0)

**Comment by OkieDan** [comment]
Thank you, yes it kinda looked like a tab!
