### ISSUE TITLE
Persistence of fight overlay

### ISSUE THREAD

**Issue by esr-sudo** [kauffman12/EQLogParser#98]
Hello!

I am not sure if this is an "issue" with EQLP, a setting within EQLP that I should adjust, or just how windows functions, but often times I find myself frustrated that the EQLP overlay does not stay visible when I am in combat.  Obviously the overlay is intended to fade away when combat is not active after a period of time that the user can set, that is not what I am referring to.  

If I am playing for a full game session I will load gina, eq, discord, eqlogparser, which I'm sure a lot of people do.  That is three overlay applications obviously, so I'm not entirely surprised I am having complications.  However, it seems to only be eqlogparser that doesn't behave in the manner that I believe is intended. 

Often times when I am playing I will turn on EQLP and it works just fine for a while, but at some point the overlay stops appearing.  It is still running, and if I alt-tab to eqlogparser to see the fight list, the overlay will appear.  But it disappears when I tab back to make everquest the active window, even though my raid combat is still going on.

Is there a setting somewhere that I have set incorrectly that is causing this?   If it helps diagnose what I am referring to, I would be happy to post a sample video to youtube.

**Comment by kauffman12** [comment]
None of your other overlay windows overlap with the DPS meter? You don't switch to full screen at all, right?

**Comment by esr-sudo** [comment]
Correct.  None of the overlay windows overlap, and full screen everquest would be gross.

**Comment by kauffman12** [comment]
Last thing I guess is make sure Overlap Windows Taskbar is turned off in EQ. If that doesn't help I might be able to force the window to try and be the top window every time it tries to update.

**Comment by esr-sudo** [comment]
Will give that a shot.  I'll post a reply here in a couple of days.

**Comment by esr-sudo** [comment]
I think your recommendation worked.  I've not noticed that problem since then.  I'll keep an eye on it!
