### ISSUE TITLE
Tanthi, Tantho, and Tanthu bosses in Asylum of Anguish do not show normal melee damage in parses

### ISSUE THREAD

**Issue by b-higginbotham** [kauffman12/EQLogParser#99]
The melee attacks from these bosses are "stabs" and are not being displayed in the tanking summary, tanking breakdown, or death logs.

Example:
`[Wed Jul 19 20:20:00 2023] Tanthu the Tormentor stabs YOU for 2210 points of damage.`

**Comment by kauffman12** [comment]
Interesting. I'll have an update for that in a few days.
